### ISSUE TITLE
Aggregator add stage size

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#101]
![image](https://user-images.githubusercontent.com/3471363/71258602-e8d99080-2336-11ea-9cf7-0ef79a1a84db.png)

If the window is too small to fit all options, this happens

**Comment by tothradoslav** [comment]
Can you scroll those options? It should be possible.

**Comment by Christilut** [comment]
Oh yeah it does scroll now. I opened this issue with one version older though. I'm on the latest now
