### ISSUE TITLE
Context submenu's overlaps

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#103]
If you right click a document and move the mouse quickly over the right click menu, the sub-menu's will overlap.

**Comment by tothradoslav** [comment]
Yep. This is kind-of intended. Let me explain: We wanted to prevent hiding the submenu immediately when you accidentally leave it with mouse pointer for a millisecond. So we added a delay in hiding. If I removed this feature, you'd probably be reporting that it's very sensitive and hiding immediately :)

And this is done using CSS, so there's this side-effect we couldn't avoid.

**Comment by Christilut** [comment]
I just checked how Windows does it, maybe emulate that?
They also have a delay until the submenu closes, but then immediately opens the new menu when the old one closes.

I'd just make it the way people are used to, that's most intuitive

**Comment by tothradoslav** [comment]
Yes I will look at it but its a bit tricky using css :)

**Comment by Christilut** [comment]
[I know hahaha](https://tenor.com/view/family-guy-css-open-window-annoyed-pissed-gif-12014506)

**Comment by tothradoslav** [comment]
Family guy is awesome :)
