### ISSUE TITLE
Recognize ObjectID

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#105]
It would be really awesome if Mingo can auto-recognize ObjectId's where-ever they are typed. 

For example a query like this:
```
{ library: ObjectID('5dff4467b92d23460037a809') }
```

I usually type it like this because I copy a string from my debugger or vuex store:
```
{ library: 5dff4467b92d23460037a809 }
```

And then I have to add ObjectID, but I always confuse it with ObjectId because that's what Robo3T uses... Anyway, super annoying. Every Mongo GUI so far is really annoying about it.

ObjectID's are always a certain length. Maybe they can be auto corrected to `ObjectID('5dff4467b92d23460037a809')` when submitting the query?

**Comment by tothradoslav** [comment]
Sure this can be done. I personally think that agains all the advantages od objectids, they were a mistake on mongodb’s side...

**Comment by tothradoslav** [comment]
LoooL i just realized you can just paste the id into the query field and mingo will try to find the value (even object id) in all indexed fields. 

So in your case if “library” is an indexed field just paste the id string and submit. This automatically applies to all _id fields since they are indexed always. 

This would not work if “library” is not indexed or you want to query by multiple fields.

**Comment by Christilut** [comment]
I think in my case it was an indexed field so that would work but it's a bit untransparent. I'd get a result and wouldn't know for which field it was..

Maybe it can expand the query after it finds results from 
```
5dff4467b92d23460037a809
```
to
```
{
  library: ObjectID("5dff4467b92d23460037a809")
}
```

**Comment by tothradoslav** [comment]
Great comment, implemented as requested. Works on ObjectID, string IDs or any of the indexed fields.

The thing I'm concerned about is how to promote this great feature to people. How to make sure they not only understand it but first of all "know" that it exists...

**Comment by Christilut** [comment]
Onboarding is an art by itself :)

I like the Protips, if I can click them whenever I feel like it and they aren't intrusive then I'll read them sooner or later.
And a lot of users won't use fancy features, they'll use the basics and are happy with it. Humans are creatures of comfort, if they know a way that works they'll keep using it.

**Comment by tothradoslav** [comment]
Good. We’ll work on the pro tips. 

Yes, Mingo is here to bring higher level of comfort, essentially :). Fortunately, developers seem to be more willing to learn than general public :)
