### ISSUE TITLE
Tooltip stuck

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#106]
![image](https://user-images.githubusercontent.com/3471363/71355867-a4d9cc00-2580-11ea-94ab-f4c4e3153629.png)

Got stuck after an undo action from the undo modal

**Comment by tothradoslav** [comment]
Hi, @Christilut , just released the latest version (still as hidden, same version number) with most current issues resolved. Leaving for a trip for 2 weeks so I wanted to wrap it up and publish for you you guys. 

Thanks for the valuable feedback you are sending! Enjoy the end of the year :)

**Comment by Christilut** [comment]
Thanks, enjoy your trip!
