### ISSUE TITLE
Append current query on different field than _id

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#111]
![image](https://user-images.githubusercontent.com/3471363/71640822-eb6eab00-2c91-11ea-8ae4-28224891c1d8.png)

I'm doing `Append current query` on the `library` field but this results in the following query:
```
{_id: ObjectID("5e0b37a48e2e5804a8f92419")}
```

But I would expect this:
```
{library: ObjectID("5e0b37a48e2e5804a8f92419")}
```

**Comment by tothradoslav** [comment]
Thanks sir, you found a really niche issue. Will be included in the next release.
