### ISSUE TITLE
CTRL+R overrides other applications

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#112]
Well this one drove me nuts a bit...

I use `CTRL+R` in VSCode and it stopped working but couldn't figure out why at all.

Then I closed Mingo and `CTRL+R` started working in VSCode again...

I guess Mingo hotkeys are a little bit too aggressive right now ;)

**Comment by tothradoslav** [comment]
Yeah I noticed too, so removed it. Reload does not work with local shortcut. So We have to stick with shift ctrl R.

**Comment by tothradoslav** [comment]
I just uploaded a new version, because I know this is super annoying :)

**Comment by Christilut** [comment]
Haha thanks, I was afraid to ask for a new version just for this
