### ISSUE TITLE
Long string value in locked db

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#113]
![image](https://user-images.githubusercontent.com/3471363/71763907-fae43300-2ee1-11ea-876d-6eb9f664a6ad.png)

I couldn't read this full value. I have to edit it to see the full value but this db is locked and I'd rather not unlock it to only read data.

**Comment by tothradoslav** [comment]
Did you use the shortcut (space) or right-click and select `Show full value` ?

Space does not work as it became the "select document" shortcut. I removed that. But the context-menu link worked for me fine.

**Comment by Christilut** [comment]
Ah ok. I didn't realize the option `Show full value` existed

**Comment by tothradoslav** [comment]
But still, this is a usability issue. Maybe a link at the end of string (by ellipsis) `Show all` ?

**Comment by Christilut** [comment]
Yeah good idea. Maybe full text length as well `Show all (1400)`
