### ISSUE TITLE
Launch with deeplink

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#114]
This may be very specific to me but I can see it being more useful to other developers.

Deeplinking with parameters such as an objectId. For example: `mingo://users/123` could open Mingo with the `users` collection open and `123` prefilled & executed as query.

We'd probably need to be able to pass in much more advanced data in the deeplink but with a stringified JSON or base64 a lot is possible and developers shouldn't be too afraid of that.

My use case currently is that I'm building my own administration system and sometimes I want to lookup a user in Mingo and it would be quite cool if I can make a button in my user detail screen that says "Open in database".

**Comment by tothradoslav** [comment]
Yes, we were thinking of this too. For now i’m using copy id from admin and use Paste&go ctrl+G

The url would first have to specify the connection (and db). But how? 

The url could contain collection+ query. Or just an ID which Mingo could look up in any collection. However we still need connection and db. Db is easy. But how about connection?

**Comment by Christilut** [comment]
Maybe `project` + `environment` combination?  Or `connection name` if it's not in a project, assuming connection name is unique.

**Comment by tothradoslav** [comment]
Ok, here's my suggestion:

mingo://project/environment/Collection/query/sort
or
mingo://connection/database/Collection/query/sort

project, environment, connection, database - deburred versions of names
query, sort - url-encoded

Also, query could take any query Mingo would accept, so, could be `aksjdflaksdfjasdf` (as _id quicksearch) or `#today` for dates

Examples (from my projects):

`mingo://uns/live/Users/gPSDBtvWvG8Z63ETS` (find user in project UNS, env LIVE)
`mingo://localhost/taskee/Messages/{createdAt: #today}/{read: 1}` (find all messages in connection LOCALHOST, database TASKEE, sort them by READ ascending);

This is assuming, all deep links would lead to documents viewer in Mingo (not the aggregator, etc). Maybe we could include `documents` in url somehow for possible future improvements (I personally don't consider this too important.):

`mingo://localhost/taskee/documentsMessages/{createdAt: #today}/{read: 1}`

**Comment by Christilut** [comment]
This won't work with a regex or any query containing a `/` though, that's why I thought maybe base64 encode the query.
Other than that, seems like a good idea

**Comment by tothradoslav** [comment]
Ok, this is prepared (can't push a new version, still on trip, slow connection), but:

- used this format: `mingo://localhost/taskee/documents/Messages/{createdAt: #today}/{read: 1}`
- query and sort have to be encoded using encodeUriComponent (JS function) (base64 has problems with unicode characters)
- I added the `documents` as this may be useful for future features
- if you want to search by _id, you could use `mingo://localhost/taskee/documents/Messages/j8niTmhsLAQxnxqjD`
- deeplink focuses the workspace (project, connection) unless already focused and opens a new tab for the link
- query params can be added to the deep link for additional info, for example ?useCurrentTab=true will not open a new tab in mingo
- other query params could be added in future

Let me know if you have any thoughs, will launch this version at jan 11, probably...

**Comment by Christilut** [comment]
Very cool! Going to add it to my admin system right away :) Really useful

**Comment by GriffinSauce** [comment]
Wow, this is awesome stuff guys! A lovely way to add superpowers to my admin pages!

**Comment by tothradoslav** [comment]
Hi guys, @Christilut @GriffinSauce  I just released a new hidden version. This is the most important issue from this release, I guess, please test it. It acted weird on mac until I closed and ran Mingo again, then it worked fine. Please let me know.
