### ISSUE TITLE
Query duration

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#116]
Would be nice if the status bar would display duration of the query.  Same for aggregator.

![image](https://user-images.githubusercontent.com/3471363/71822197-8e5d6580-3094-11ea-9ae6-139165aa82ed.png)

**Comment by GriffinSauce** [comment]
Idea: a tiny button next to the timing to rerun it in the shell with `.explain()`

**Comment by Christilut** [comment]
And more bonus points if you make the explain results more readable and show the user what he really wants to know with an option to show the original json explain results

**Comment by tothradoslav** [comment]
Sure, this can be done easily. Two questions:

1. executing a query in simple mode without explain will not return the duration it took to execute, so I can only show the amount of time it took to execute and get the results into mingo. Will that be sufficient for you? (this time is connection-speed dependant)

2. what is it that you think should be shown in "readable" manner? I will go through the `Explain Results` and see what they give, but if you could send me your ideas, would be great.

**Comment by Christilut** [comment]
I'm not really that familiar with the explain command, but MongoDB Atlas has it's own interpretation of it and it sends warnings to users when it recognizes certain problems.

But it could show the winning plan and rejected plans at least and maybe the amount of documents examined. I'm not totally sure what the most important info here is though.

**Comment by tothradoslav** [comment]
This is prepared, with the explain link, too, but without advanced explain. We'll do this later, must think it through...
