### ISSUE TITLE
[aggregation] Add stage - keyboard shortcuts

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#120]
Click the add stage button in aggregation -> massive list pops up.

I know (most of) the stages already, the list is so long that I'm scanning a lot to find one. It would be nice to be able to type and select one. Interaction like a HTML <select> perhaps? Or a visible filter input that is focused immediately?

**Comment by GriffinSauce** [comment]
It's probably good to keep the list for discoverability of unknown stages, that's great. But it shouldn't impede you when you know what to do.

**Comment by tothradoslav** [comment]
Thinking of the best user experience. 

How about adding links to the most recent (most used) stages to the right from the `add stage` button. Probably 5 of them would fit. Would this work?

**Comment by tothradoslav** [comment]
I added links to the most used ones for now, let me know what you think (I'll close this issue when version uploaded)

**Comment by GriffinSauce** [comment]
Curious to see it, will report back :)
