### ISSUE TITLE
Bug: Deeplink

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#123]
![image](https://user-images.githubusercontent.com/3471363/72201918-d0eabd80-3459-11ea-975e-31608cf605bd.png)

```
`mingo://${connection}/rekordcloud/documents/users/${this.user.id}`
```

The above error happens when Mingo is already open.

If Mingo isn't open, it just starts Mingo but doesn't open any tab

**Comment by tothradoslav** [comment]
There should be some logs in console after you try to open a deep link. Could you send it to me?

**Comment by Christilut** [comment]
I think you're after this one:
` ["--allow-file-access-from-files", "--original-process-start-time=13223224268190019", "mingo://localhost/rekordcloud/documents/users/undefined"]`

**Comment by Christilut** [comment]
Clearly I messed up sending in `underfined` as userId there :P But I still have the bug though

**Comment by Christilut** [comment]
`["--allow-file-access-from-files", "--original-process-start-time=13223224445057813", "mingo://localhost/rekordcloud/documents/users/5d35e53e097faa07ac0fd88a"]`

`{type: "warning", text: "Deep link incorrect: TypeError: r.replace is not a function", id: "BMhKNfIqKTbFTOWKT", tabId: "hdqORV73BTew3sHBk"}`

**Comment by tothradoslav** [comment]
I have updated the windows version, please download and try now. This was only a windows issue. Thanks.
