### ISSUE TITLE
Deeplink opens all tabs

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#125]
![image](https://user-images.githubusercontent.com/3471363/72247779-f4e30600-35f5-11ea-8fa5-7a9d86dee71f.png)

It opened all my collection tabs this time. After trying it a few more times, it only opened a `users` tab.

**Comment by Christilut** [comment]
Most of the time it opens 1 tab. I had it once that it opened the `users` tab twice.

**Comment by Christilut** [comment]
And when mingo is closed and I open it with the deeplink, no new tabs are opened. Maybe has something to do with the `argv` error?

**Comment by tothradoslav** [comment]
So when mingo is closed, it opens the app but ignores the deep link ? (no new tab is added / opened)

**Comment by Christilut** [comment]
Yep

**Comment by tothradoslav** [comment]
added some more logs, will let you know when released. Should be OK now.
