### ISSUE TITLE
Deeplink for a project?

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#126]
How do I select a project in the deeplink? It uses my `localhost` connection without project now but that connection name also exists under my `Rekordcloud` project which is the one I actually want to use.

**Comment by tothradoslav** [comment]
use /project-name/env-name in url (first 2 params) instead of /connection-name/database-name

let me know

**Comment by Christilut** [comment]
That works for my `localhost` database but not my `Production` database:
```
deep link params (5) ["rekordcloud", "Production", "documents", "users", "5d35e53e097faa07ac0fd88a"] {}

Notification {type: "warning", text: "Deep link incorrect: TypeError: Cannot read property 'id' of undefined", id: "ONqc4vtgxH0xgqe8I", tabId: "hMw3qcJe10iNEg7T2"}
```

![image](https://user-images.githubusercontent.com/3471363/72250707-82295900-35fc-11ea-8808-6fdd87b70ac5.png)

Side note: it's kind of annoying to copy/paste logs here because they are JS objects that I need to expand first but then formatting is all messed up if I copy them. Maybe log to file? I'm also missing the startup logs, anything that happens before the renderer is ready is lost now

**Comment by tothradoslav** [comment]
if your env is called `Production`, the url should have `production` (deburred, lower cased), try please.

I will create a log file.

**Comment by Christilut** [comment]
Yep, works
