### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by tothradoslav** [mingo-app/mingo#129]
Hi guys, just starting planning dark mode. If you have any comments / ideas before we start, please let me know here, thanks!

@GriffinSauce @Christilut

**Comment by Christilut** [comment]
Not sure if it's possible in electron, but would be cool if it automatically uses `prefers-color-scheme` to determine if Mingo should use dark mode.

And for future proofing it would be really nice if you use css variables, that would make theming super easy

**Comment by GriffinSauce** [comment]
Cool! Be careful not to destroy the hierarchy of information by flattening the colours/contrast too much. (so, don't make _all_ backgrounds black, use dark greys/colours too)

Variables would be great for maintainability (and customizing), requires a little more planning and/or refactoring along the way though.

**Comment by tothradoslav** [comment]
OK, we use scss with variables so should be fine. I'll check if `prefers-color-scheme` works in electron, but should...

**Comment by Christilut** [comment]
Might be easier with css variables though... then you won't need an extra build step if you add theming later. But up to you, should work well either way

**Comment by tothradoslav** [comment]
We used Foundation for CSS templates (which was probably a mistake, but...) so it would be a lot of work to move over to CSS variables, but I agree it would be much much better...

**Comment by Christilut** [comment]
Well something for later then. Focus on getting Mingo ready and out there 👍

**Comment by dotvhs** [comment]
Just curious if there are any updates on this?

**Comment by tothradoslav** [comment]
sure, this is just being finished and will be out with next release :)

**Comment by tothradoslav** [comment]
added in v1.4.3, please give feedback for improvements, thank you
