### ISSUE TITLE
Connection - accept any URI

### ISSUE THREAD

**Issue by tothradoslav** [mingo-app/mingo#13]
- with extra params
- multiple hosts
- rs

**Comment by GriffinSauce** [comment]
FYI: connecting to a replicaset works with the newer `mongodb+srv://` connection string.

**Comment by GriffinSauce** [comment]
If you need help testing with a RS feel free to ping me. :)

**Comment by tothradoslav** [comment]
Sorry, just noticed your comments here. Could you drop me an email at info at mingo.io? Thanks, Rad

**Comment by tothradoslav** [comment]
@GriffinSauce have you received my email? thanks :)

**Comment by tothradoslav** [comment]
This seems to be working. I tried mLab connection with mongodb+srv:// and worked. Could you confirm @GriffinSauce ? Thanks.
