### ISSUE TITLE
Compare & Sync

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#135]
I'm not sure what Compare & Sync does but wanted to try it...

I selected one collection but got an error

![image](https://user-images.githubusercontent.com/3471363/72527589-64acf700-3869-11ea-8310-ad8e4b9011cf.png)

```
Error: Command failed: mongo mongodb+srv://admin:<PASSWORD>@clusterx.mongodb.net/production --quiet --eval 'TSH=s=>{for(var i=0,h=6;i<s.length;)h=Math.imul(h^s.charCodeAt(i++),387420489);return h^h>>>9};db.getCollection("occasions").find({}).limit(100000).map(d => {return {_id: d._id.str || d._id, hash: TSH(JSON.stringify(d))}});'
> was unexpected at this time.

    at ChildProcess.exithandler (child_process.js:308)
    at ChildProcess.emit (events.js:203)
    at maybeClose (internal/child_process.js:1021)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283)
```

Also the error contained my password again...

**Comment by tothradoslav** [comment]
It compares the selected collections and syncs the docs from source to destination. Almost like dump / restore but this only updates / inserts / deletes the changed files. So in most cases it's faster.

Your issue is that it could not find `mongo` executable. This is probably a windows related issue. Do you have 'mongo' availabe on your local computer? That's a requirement for this feature. Maybe only the path is incorrect.

I removed the log and changed it, sorry. Thanks.

**Comment by tothradoslav** [comment]
Also, what version of mongo do you have locally, maybe that's an issue, too.

**Comment by Christilut** [comment]
I have the mongo tools here `C:\Program Files\MongoDB\Server\4.0\bin`

`MongoDB shell version v4.0.10`

Compare & Sync sounds really cool but I was a bit hesitant to try it because it involves my production database... And it does sound like exactly what I need but I couldn't infer that from the name or context... This needs some more explanation

**Comment by Christilut** [comment]
Also if it is a requirement to have the mongo tools then there should be a check step before opening Compare & Sync that tells me that

**Comment by tothradoslav** [comment]
I added a check for PATH and mongo -version. Will upload a new version for you. Please let me know what logs you see, should be 2 logs:

process.env.PATH
checkMongo result

thanks!

**Comment by Christilut** [comment]
I don't see those in the logs. I just downloaded the latest version.

Also I'm beginning to miss auto updating :P

**Comment by tothradoslav** [comment]
Sorry about this, the version wasn't realeased. I usually just label the issue with `next release`. Once I close the task it's releases.

I'm working on the autoupdate, but this is quite complicated. 

However, once I start releasing real versions (still keeping the 0.9.13 version), Mingo will notify you and you can download the new version with one click.

The new release is published now.

**Comment by Christilut** [comment]
Yeah getting auto update working isn't easy... I managed it with my electron app for Windows and Mac so if you need help, just ask. This link helped me on the Mac side a lot: https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

And I used electron-builder which makes it much easier.

New build seems to be broken, I'll open a new issue.

**Comment by tothradoslav** [comment]
Compare & Sync has been updated with explanation (was hidden in compact mode) and with the logs.

**Comment by Christilut** [comment]
`Mongo command in shell failed. Maybe mongo not found??`

It's not in my PATH I guess. But should that really be a requirement? Mongo tools don't get added to your PATH by default do they?

I would check the path and the default installations locations. If neither has the mongo tools, then give the user a popup or something giving them instructions how to add something to their path. In most cases the tools will be at their default location.

**Comment by tothradoslav** [comment]
Thanks. Can hou also send console log output?

**Comment by Christilut** [comment]
I just says
```
Mongo not found??
```

And some db/sync messages, and my PATH var.
And my connectionstring with password again.. Maybe make a helper for that? Not really acceptable that passwords end up in the logs

**Comment by tothradoslav** [comment]
Hi, just uploaded a new version with changes in compare/sync:
1. removed the logs, sorry about that, hope nothing else left, but these are temporary now
2. added some other logs, trying to find a way to "find" mongo automatically
3. added a dialog to `find mongo executable`

Please let me know if it works and / or send me some logs. Thanks a lot, I really appreciate your help.

**Comment by Christilut** [comment]
![image](https://user-images.githubusercontent.com/3471363/72759914-6400c180-3bd7-11ea-9616-b1cf6c30c0bb.png)

Didn't find it at first, then I selected that path and gave the same message.

Also you can add a FIle FIlter in the dialog:
```
    const paths = dialog.showOpenDialogSync({
      properties: ['openFile'],
      filters: [
        {
          name: 'mongo.exe', // Just a label but a good hint
          extensions: ['exe']
        },
        {
          name: 'All files',
          extensions: ['*']
        }
      ]
    })
```

Or maybe better to allow folder selection that the user thinks contains mongo.exe? Right now I wasn't 100% sure that I had to choose mongo.exe

**Comment by Christilut** [comment]
Also the text "Find mongo" sounds like it's going to automatically find it. Maybe change to something like "Choose mongo.exe path" or so

**Comment by tothradoslav** [comment]
Thanks, I updated the details. So has it actually worked for you? :)

**Comment by Christilut** [comment]
Nope, not yet

**Comment by tothradoslav** [comment]
Ok, finally got the VM running and tested it on windows 10, so should be running now. Please check it out...

**Comment by Christilut** [comment]
It asked for my mongo path again, I selected `mongo.exe` and I could continue. But after I pressed `Compare collections` it said there was an error.

Console says `Mongo command in shell failed. Maybe mongo not found??`

**Comment by tothradoslav** [comment]
Trying to find a way to debug this without having to bother you with another new version... Now it's probably a mongo issue rather than exec(), but it worked for me. 

A few questions:
1. are you comparing local or remote dbs?
2. are you using SSH to connect? 
3. can you try simply comparing 2 localhost databases? (comparing makes no changes to documents)

**Comment by Christilut** [comment]
1. my first db is production, remote and my second db is localhost
2. nope
3. same error with 2 localhost databases

**Comment by tothradoslav** [comment]
Finally, had to create a new version with some logs. Added a helper to remove passwords. Please send me the logs. Thanks a lot.

**Comment by Christilut** [comment]
```
Mongo command in shell failed. Error: Command failed: "C:\Program Files\MongoDB\Server\4.0\bin\mongo.exe" mongodb://127.0.0.1:27017/rekordcloud-test-ElllOJAwngJ9DreOHLYP --quiet --eval 'TSH=s=>{for(var i=0,h=6;i<s.length;)h=Math.imul(h^s.charCodeAt(i++),387420489);return h^h>>>9};db.getCollection("playlists").find({}).limit(100000).map(d => {return {_id: d._id.str || d._id, hash: TSH(JSON.stringify(d))}});'
> was unexpected at this time.
```

**Comment by tothradoslav** [comment]
This seems to be an issue with escaping, but for some reason it worked fine on my VM with same mongo version as yours.

Before I upload a new version, could you please try 2 little things for me?

1. run the above command directly in CMD in windows (command line) to see if it works or what's the result error.
2. could you run the following command, same as above but escaped:

`"C:\Program Files\MongoDB\Server\4.0\bin\mongo.exe" mongodb://127.0.0.1:27017/rekordcloud-test-ElllOJAwngJ9DreOHLYP --quiet --eval 'TSH=function(s){for(var i=0,h=6;i<s.length;)h=Math.imul(h^s.charCodeAt(i++),387420489);return h^h\>\>\>9};db.getCollection(\"playlists\").find({}).limit(100000).map(function(d){return{_id:d._id.str\|\|d._id,hash:TSH(JSON.stringify(d))}});'`

**Comment by Christilut** [comment]
```
C:\Users\Alpha>"C:\Program Files\MongoDB\Server\4.0\bin\mongo.exe" mongodb://127.0.0.1:27017/rekordcloud-test-ElllOJAwngJ9DreOHLYP --quiet --eval 'TSH=s=>{for(var i=0,h=6;i<s.length;)h=Math.imul(h^s.charCodeAt(i++),387420489);return h^h>>>9};db.getCollection("playlists").find({}).limit(100000).map(d => {return {_id: d._id.str || d._id, hash: TSH(JSON.stringify(d))}});"
> was unexpected at this time.
```


```
C:\Users\Alpha>"C:\Program Files\MongoDB\Server\4.0\bin\mongo.exe" mongodb://127.0.0.1:27017/rekordcloud-test-ElllOJAwngJ9DreOHLYP --quiet --eval 'TSH=function(s){for(var i=0,h=6;i<s.length;)h=Math.imul(h^s.charCodeAt(i++),387420489);return h^h\>\>\>9};db.getCollection(\"playlists\").find({}).limit(100000).map(function(d){return{_id:d._id.str\|\|d._id,hash:TSH(JSON.stringify(d))}});
The system cannot find the file specified.
```

**Comment by tothradoslav** [comment]
Just uploaded a new version, please try it. I've done several tests on windows and worked fine. Please let me know.

**Comment by Christilut** [comment]
It works now, very cool! Really useful feature.

Small thing I noticed: after I compare and see the compare results, I only wanted to sync 1 collection but after changing any checkbox, all compare results are gone. They can stay until I press compare or sync?

Also if you press Compare and change a checkbox while it's still comparing, the operation continues and results keep appearing. Maybe disable checkboxes while it's running? And turn the Compare button into a Cancel button while it's running.

**Comment by tothradoslav** [comment]
[] stop button while running
[] ignore checkboxes while running
[] allow selecting collections to sync after comparison
