### ISSUE TITLE
Startup with deeplink

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#137]
I'm not sure if this one was fixed or not, but if so feel free to close it right away

When starting Mingo with a deeplink (mingo is closed), then I get the `Cannot read property replace of null` error. If Mingo is already open, it works as expected.

**Comment by tothradoslav** [comment]
Not sure if you have the latest version but this should be resolved. Can you please check?

**Comment by Christilut** [comment]
Just downloaded latest. 
It doesn't give the replace error anymore, but it just opens Mingo with the last tabs I had visible but not the tab from the deeplink.

Basically I have to click the link twice now to get the expected result. One click opens Mingo, second click opens the tab (in the current tab)

**Comment by tothradoslav** [comment]
Ok, I added some logs to see what's happening after startup. Will close task when uploaded.

**Comment by Christilut** [comment]
Not sure if you're aware but this problem still exists. And I can't open the devtools anymore to check the logs.

Also tiny other thing, maybe add a release date in the "Whats new" popup.

**Comment by tothradoslav** [comment]
thanks, the devtools will be available again with new version. 

What's new: sure, thanks.

**Comment by Christilut** [comment]
In the newest version it still ignores the startup deeplink. I don't see it in the devtools either. When I press a second time with Mingo already open, I do see the `deep link params` message in the devtools.

**Comment by tothradoslav** [comment]
Is this on windows? Mac works ok. Looking into it...

BTW, has this worked before and stopped working again or is this still the original issue and never worked?

**Comment by tothradoslav** [comment]
Nevermind, I figured it out and works now, tested on win 10. Will be in next release. Thanks for the feedback.

**Comment by Christilut** [comment]
This still doesn't work reliably. I use it quite a lot and often it doesn't open the requested tab.

**Comment by tothradoslav** [comment]
is this still an issue with the latest v1.2.6?

**Comment by Christilut** [comment]
It looks fixed. 
Just one small new issue is that when I use the deeplink the search popup "Type a collection, history or bookmark name..." overlays it.
