### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by tothradoslav** [mingo-app/mingo#139]
@christilut wrote:

> Yeah getting auto update working isn't easy... I managed it with my electron app for Windows and Mac so if you need help, just ask. This link helped me on the Mac side a lot: https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/
> 
> And I used electron-builder which makes it much easier.

**Comment by tothradoslav** [comment]
@christilut Do I need any kind of windows developer account to be able to use autoupdate? Some articles claim I do. 

We already have signing for macs but not for windows.

**Comment by Christilut** [comment]
No but you do need an Authenticode certificate to sign it. You can do it without signing it but users will get the `unidentified developer` message. The cheapest I found was here: https://codesigncert.com
You'll get a certificate that you have to download with an old version of Firefox (yup).

Then you add this to your envs:
```
# Windows code signing certificate and password
WIN_CSC_LINK=../../Documents/certificates/app-certificate.p12
WIN_CSC_KEY_PASSWORD=
```

And add this to `electronBuilder` options:
```
        win: {
          publisherName: 'Company name' // Same as on your certificate, probably your legal company name
        },
```

And electron builder should start signing your app automatically.

I'd get auto update working first without signing it on Windows though. I'm publishing to a github repo, that works with auto updates automatically (if you use electron builder).

**Comment by GriffinSauce** [comment]
Hey I see this is not an easy thing to solve, but since you asked for priorities recently: I getting a bit tired of the whole "go to the website, download new version, drag it forgetting to kill the app, kill the app, start the new one, yes I know I just downloaded it Apple" and _then_ being able to continue. 😅 

I can see this leading to a big drop off of real (less early adopter type) users over time.

**Comment by tothradoslav** [comment]
Yeah you are right. I kept pushing it away but will try to solve it now. :)

**Comment by tothradoslav** [comment]
This is done, please test it. I have tested on mac an windows (emulation). Please let me know if something goes wrong. 

You will actually only see the results when the next release is out.
