### ISSUE TITLE
Visual issues

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#142]
I'm seeing some styling issues:

![image](https://user-images.githubusercontent.com/5630996/73067875-0d7ed600-3eaa-11ea-8ee1-c3ccee7029a5.png)

![image](https://user-images.githubusercontent.com/5630996/73067886-1a9bc500-3eaa-11ea-9743-f0c361cdc170.png)

This is in compact mode.

**Comment by tothradoslav** [comment]
Thanks, the scrollbar will be hidden, but for the "traffic lights position", we'll have to wait for the next release of electron, they just merged this feature into master 2 days ago :)
