### ISSUE TITLE
Shell results empty

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#143]
When I run a command (no matter what) in the shell I get an empty results view with these headers:

![image](https://user-images.githubusercontent.com/5630996/73067951-4323bf00-3eaa-11ea-8534-c692f2f5c3e1.png)

**Comment by tothradoslav** [comment]
Are you usin nodeshell or the original shell?

**Comment by tothradoslav** [comment]
Could you send an example of command that doesn't work? Trying different commands but I always get the results.

Also, what version of mongo do you use on that db?

**Comment by Christilut** [comment]
I have the same problem.
`db.collection("logs").find().limit(10)` 

Error in console:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'NativeTopology'
    |     property 's' -> object with constructor 'Object'
    |     property 'sessionPool' -> object with constructor 'ServerSessionPool'
    --- property 'topology' closes the circle
    at JSON.stringify (<anonymous>)
    at i.u [as _s] (renderer.js:1)
    at i.<anonymous> (renderer.js:1)
    at i.e._render (renderer.js:1)
    at i.r (renderer.js:1)
    at Io.get (renderer.js:1)
    at Io.run (renderer.js:1)
    at He (renderer.js:1)
    at Array.<anonymous> (renderer.js:1)
    at Q (renderer.js:1)
```

**Comment by GriffinSauce** [comment]
Sorry for the delay, I get the same error ^

I noticed the shell button below collections starts with `db.collection("").find().toArray()`
But the shell under a specific collection like `user` starts with `db.collection("user").find();`

I do see results when `toArray` is added to the query.
