### ISSUE TITLE
Nodejs shell cancel running command

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#144]
I accidentally ran a very inefficient query in the Nodejs Shell and it froze Mingo. All I see the is infinite loader spinning but nothing responds to my input.

Should the UI not respond even though it's loading? And whatever I ran should be cancellable.

**Comment by tothradoslav** [comment]
I'd like to see your command executed, but: 

1. if you create a command such as `db.collection('users').find().toArray()` and your collection contains lots of documents, rendering so many results would freeze the webview. I added a safety-cut-off at 100 docs, so the rendering is acceptable.

2. if the command is inefficient on the server (takes too long to execute), I added a "stop" button to kill all operations from Mingo (esentially your long-running operation);

**Comment by Christilut** [comment]
I did this on me `logs` collection with 700k and it was prefilled with `db.collection('logs').find().toArray()` and I thought "lets see if this works". It did not haha

If it stops at 100 then it's fine.
