### ISSUE TITLE
Date helper not working in $gt

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#146]
```
{
    type: '4',
    createdAt: {
        $gt: #thisMonth
    }
}
```

Returns no results.

**Comment by tothradoslav** [comment]
Hm, this is probably a not-well-explained feature. 

`{type: '4', createdAt: #thisMonth}` would be the correct way to use it because it actually means "during this month" and will be interpreted as:

'{
type: '4', 
  "createdAt": {
    "$gte": new Date("Wed Jan 01 2020 00:00:00 GMT+0100 (Central European Standard Time)")
  }
}'

**Comment by Christilut** [comment]
Ah okay, I had a feeling it was like that.

I thought the `#thisMonth` would expand to `2020-01-01:00:00:00` and that's why I used `$gt`

Maybe the helpers can be used both ways? `$gt: #thisMonth` would be 2020-01-01 while just using `createdAt: #thisMonth` would automatically use `$gt` and `$lt` ?

Or maybe that just makes things more confusing... I'm not sure. The date helpers are super useful, I really hate writing dates in Mongo... Would be really awesome if they just worked magically, whatever the input is.

**Comment by tothradoslav** [comment]
There’s difference between durations and specific moments. ThisMonth is a duration and should work that way. We should come up with helpers for moments but I feel they are pointless. 

What would you use them for? “Start of today”? You rarely query for specific moment. Usually its more like today yesterday etc. what do you think?

**Comment by Christilut** [comment]
No but users might not know the mingo way or prefer to enter queries with `$gt` because that's what they know (or maybe copy paste it from their code). 

This way with mingo is really nice but if I know the MongoDB query syntax already and started using Mingo, it would be annoying to have to learn this new way.
But if I can combine the old MongoDB knowledge I already have with date helpers that remove the need for me to type out full ISO dates, then that's perfect.

**Comment by tothradoslav** [comment]
How about keeping the existing helpers and adding a new one: #2020-01-27 or even #2020-01-27-12:35 and these would simply be formatted to a mongodb date. Example:

{createdAt: {$gt: #2020-01-27}}

Only minor issue: we have such a helper already but it means “during that day”. So would have to be changed.

**Comment by tothradoslav** [comment]
I was also rhinking of changing the prefix to @ instead of # this helper meaning “at”

**Comment by Christilut** [comment]
I think @ is a good idea.
This all does needs some more documentation and some good examples though.

Would be cool if it could recognize `@12:35` to be `today at 12:35`

**Comment by tothradoslav** [comment]
Ok, I went with ISO standard format or any part of it will be recognized: https://en.wikipedia.org/wiki/ISO_8601

Also, as you requested, `@12:35:24` or `@12:35` will be recognized, too.

**Comment by Christilut** [comment]
Very cool! Works really well and intuitive
