### ISSUE TITLE
Replace function

### ISSUE THREAD

**Issue by nicothed** [mingo-app/mingo#149]
I'd LOVE to have a function like (pseudo code):
`db.myColl.replace((doc) => {name: doc.name.replace( /Studio 3T/gi, "Mingo"), sum: doc.n1 + doc.n2})`

**Comment by tothradoslav** [comment]
Just to clarify: you’d like to have a way to iterate over every document within a collection and update fields using a function?

If this is the case you could use Mingo’s NodeShell where you could write your code almost as above. 

If you meant something else, let me know. Thanks!

**Comment by nicothed** [comment]
Yes, I'd like an easy way to "iterate over every document within a collection and update fields using a function", but ideally in the GUI. A bit like in Excel: select one or more columns, type the "Find" (could be a regexp in v 2.0 ;) and "Replace by", and your software does the rest.

**Comment by nicothed** [comment]
Example: I'd like to replace "guiness" with "guinness" (correct!) in these 2 columns:
![image](https://user-images.githubusercontent.com/9327873/73499319-cef78880-438d-11ea-9956-2955ccd87285.png)

**Comment by tothradoslav** [comment]
We are working on a new section for Mingo, which will be called "Updater". It's going to be a better GUI for update operations which will include regular MongoDB operations ($set, ...), mapping functionality and also find/replace as you requested.

**Comment by tothradoslav** [comment]
As time went by, we updated our NodeShell so that it can execute actual JS code, so you could easily use it to do what you requested:

This would be the code:
```javascript
const docs = db.collection("myColl").find().toArray();
docs.forEach(doc => {
  db.collection("myColl").updateOne({_id: doc._id}, {$set: {name: doc.name.replace( /Studio 3T/gi, "Mingo")}})
})
```

BTW, download the latest version to have this functionality. Thanks!
