### ISSUE TITLE
Aggregation templates

### ISSUE THREAD

**Issue by nicothed** [mingo-app/mingo#150]
I trained on SQL (long ago), and have been using MongoDB for 4 years, but still hate their aggregation framework. SQL was *so* simple!

A great GUI feature would be to provide templates. One of them (pretty much the base for every aggregation I perform) is:
SELECT myField, count(*) AS c FROM myCollection 
GROUP BY myField 
SORT by c DESC

I'm sure you know what I mean.

**Comment by tothradoslav** [comment]
Yes, this could be added to our Aggregator, which already allows you to save pipelines and even individual stages for later use, but we could add reset examples for each command (such as $group). Will do so. 

The particular example you provided can already done in Mingo. When listing documents, right-click on a field / value you want to group by and count and select that option:

https://cl.ly/d967442103e8

You'll get the results in a modal.

**Comment by nicothed** [comment]
_> The particular example you provided can already done in Mingo_
I LOVE this feature, thank you!
Weirly, "44" comes first though - a small sorting issue:
![image](https://user-images.githubusercontent.com/9327873/73545820-20455d80-440a-11ea-8b05-691d1e709a3e.png)

It would also be great to be able to open that query in the aggregator to modify it.

**Comment by tothradoslav** [comment]
The sorting issue is a result of JS props not being sorted stably, so had to change the view of the results a bit.

Also added the "open in aggregator" option.
