### ISSUE TITLE
Add column

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#159]
![image](https://user-images.githubusercontent.com/3471363/74523705-ee5dec00-4f1d-11ea-949b-a22d1881db7b.png)

It seems to suggest all keys of an object as a column. The list goes on for quite a bit.

Also maybe filter `__v` as a common but unimportant field in this column? It comes from Mongoose, it's on every document and is never useful for the user to see.

**Comment by tothradoslav** [comment]
Field name length issue corrected.

Will create a separate issue for __v. You are right, but maybe it's good to know that there's something extra we would not know about if we hid it...

**Comment by Christilut** [comment]
Maybe just sort them to the bottom, they should be visible but at least not take up important space

**Comment by tothradoslav** [comment]
great idea, done :)
