### ISSUE TITLE
Deeplink doesn't focus the app if it's in another space/desktop

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#160]
When you have mingo on the same space/desktop on MacOS it will focus the window when you open a deeplink, when it's on another space it does not.

Deep links are super powerful already, little interaction details like this would make it even smoother as part of a workflow :)

**Comment by tothradoslav** [comment]
Been trying to google this for a while but no mention about this whatsoever. But the issue is real, tried it. 

Will keep this open, maybe I'll come across something...
