### ISSUE TITLE
Query history dropdown

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#164]
This is very personal but it's been bugging me for longer. I thought I'd get used to it but I'm really not.

Every time I click the query field the history dropdown pops open. To me this is very annoying behavior, I can't really explain why though. It just feels too fragile. The fact that I do one mouseclick and my entire screen (lots of history) is filled. 

I think (I can't be sure, this is too subjective) I would like it better if the history didn't popup out like that but there could be a button (maybe above the query go arrow button) with a clock icon that activates the history.

I really like the history and I use it all the time but I think the current display method is a bit too eager or something.

**Comment by Christilut** [comment]
Just realized it's also because when I'm crafting a query, I alt tab a lot and every time I click the query field the history pops back up, but I want to see the results of my (incomplete) query. So I keep pressing escape to keep closing it.

**Comment by tothradoslav** [comment]
I have completely reworked this functionality, because I agree with your "subjective" feelings :)

We'll see how it goes, whether we like it more than the current solution.
