### ISSUE TITLE
Compare & sync bug

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#168]
I tried to sync a single collection but got `An error occurred` when I pressed `Compare collections`.

Console said: `Mongo command in shell failed. SyntaxError: Unexpected number in JSON at position 4`

Other small bug: when in this state and you uncheck the collection, it disappears and you end up with this:
![image](https://user-images.githubusercontent.com/3471363/75030911-6f306100-54a5-11ea-80a1-0c690dd1117d.png)

Checking the header checkbox fixes it though.

**Comment by tothradoslav** [comment]
Trying to re-create your error, but can't... Might need more info or a new version with some logs. Does this always happen? Or just in special cases? 

The other small bug will be corrected.

**Comment by Christilut** [comment]
This happens on all collections. But this happens on the database that's hosted on MongoDB Atlas and compared with my localhost db. That might be causing it.

**Comment by tothradoslav** [comment]
Atlas could be the case. I will try to test it on atlas and we’ll see. 
-[ ] test atlas
-[] correct hiding rows

**Comment by tothradoslav** [comment]
Do you have any other remote connections besides Atlas where the compare/sync works?

**Comment by Christilut** [comment]
Yeah it works on my self hosted mongodb server in my local network

**Comment by tothradoslav** [comment]
Found the issue, which was actually caused by an open MongoDB issue, waiting to be resolved. Made a workaround...
