### ISSUE TITLE
Better way to edit subdocuments and arrays

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#169]
I would really love it if there is a better way to edit subdocuments and arrays.

Now I usually double click a subdocument or array and the small 1 line edit modal pops up. But for objects that works very unpleasantly: `{ foo: "bar" }`. Getting something like that but with more data (which usually doesn't fit in the tiny modal either) is not the way I ever want to edit my data. So then I always click `Edit entire doc` and I have to look for the subdoc and then I can edit it.

It would be really nice if the tiny modal would be multi-line and accommodate objects/arrays better. That way I wouldn't have to find the thing to edit in the entire doc but I could still enjoy a nice JSON editor that has exactly the data I want to edit.
There should absolutely be a limit to how many lines it should be. Maybe it can grow upwards and downwards (eg, overlay the document) so there's lots of space available.

Anyway, I was triggered by myself here because I noticed that when I'm editing an object or array, I never want to use the tiny modal and I even actively started avoiding it.

**Comment by tothradoslav** [comment]
So you only want to change one attribute of a subdocument or array item? In that case, have you tried dblclick on the actual subdoc field or array item? The small edit works in any depth.

**Comment by Christilut** [comment]
Sorry, I forgot to mention an important detail. I mean when I'm editing a subdocument and I want to add a new field, then I end up with something like this that I have to enter a new field into, which isn't very pleasant:
![image](https://user-images.githubusercontent.com/3471363/75613250-9e8d4080-5b2b-11ea-8286-a7d5f620c49b.png)

**Comment by tothradoslav** [comment]
Ok but this could be solved by a “add new field” option, which is actually on my todolist. Would that be sufficient?

**Comment by Christilut** [comment]
I think so, but wouldn't the the click menu become a bit too crowded? But since rename and delete are already there, it would make sense.
