### ISSUE TITLE
Deleting field from subdocument does not update UI

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#170]
Deleting a field from a subdocument does not update the UI. After I refresh the query, the field is gone so the delete did work. 

I think this used to work in the past?

**Comment by Christilut** [comment]
Just deleted some more field but now it does work properly. I'll keep an eye on it and check the console next time.

**Comment by tothradoslav** [comment]
Do you remember what type of field was it? A complete object (subdoc) from an array?

**Comment by Christilut** [comment]
It was a field (boolean or Date) inside a subdocument
