### ISSUE TITLE
Undo popup feedback

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#172]
The undo diff is really handy but in the tooltip the way it is now is not very user friendly. Long changes are very hard to read (even a Date is hard to read since it's so long).

Maybe the undo lines can slide down when click on? And a button next to `Undo` that says `Details` with a chevron-down to expand?

Also the summaries aren't super useful:
![image](https://user-images.githubusercontent.com/3471363/75677383-9e0bbb80-5c8b-11ea-9b0f-3bd336a09adf.png)

It says `update` for every line even though the tooltip says `add` or `update`. Which is technically an update but not really what the user experiences.

And I'm not sure about the usefulness of the document ID. I get that there needs to be a way to differentiate the undo's but I don't know any doc ID's usually. 

I'd really like to see a super mini summary version in the line itself, eg `Deleted 1 field` or `Added 1 field`. Maybe with the field name (or first 10 letters or something, could be too long). Color coded would be nice too.

And the popup shows the entire collection name, but I would assume that the undo popup is only for my current connection (I don't know if that's true). But it would be best if the undo's separated between connections. And in that case then you'd only need to show `users` instead of the connection name as well.

**Comment by tothradoslav** [comment]
Thanks for this, I have rethought this a bit based on your feedback and reoganized it. Let me know what you think once this is closed :)
