### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#177]
Just downloaded the app on my Windows box and was pretty surprised by the zip with a .exe and a bunch of resources.

So I'm used to the whackyness of app installing on MacOS but on Windows there is just one way: an installer. If you do decide to unzip and run it you're welcomed by this:

![image](https://user-images.githubusercontent.com/5630996/76685451-fd66b580-6613-11ea-8bd4-62673dc09d53.png)

Which you can skip, but if I was a potential customer I'd definitely nope out at this point. ;) Especially when dealing with any kind of serious db.

Edit: I didn't even get that far (which is a big tell!) but the app itself shows a white screen on start. I'm unable to launch the debugger, let me now if there's any logs I can grab for you.

**Comment by tothradoslav** [comment]
I just found the bug you mentioned at the end. Will male a release tonight. 

Regarding win installer, will investigate on how to get this working. Thanks!

**Comment by GriffinSauce** [comment]
Thanks! I realise now my language was a bit rough, apologies. Looking forward to testing out the installer! :)

**Comment by tothradoslav** [comment]
Not rough at all :). I have released a new version (keeping the number for now) with the bug removed, installer will come later...

**Comment by tothradoslav** [comment]
We have finally received our Windows certificate, could you please try if the new version is signed and doesn't show the above message? Thanks.

**Comment by GriffinSauce** [comment]
Long time no see! I just downloaded it, it was quite slow from us-east to the EU. You should probably chuck a CDN in front of that S3 bucket ;) 

So, bad news sorry:

![image](https://user-images.githubusercontent.com/5630996/93931566-41531980-fd1f-11ea-9cb8-cdb181cb1bab.png)

You could try running a Windows virtual machine to debug this. You can download official ones [here](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/)

**Comment by tothradoslav** [comment]
Thanks for the information. I updated the exe file, please download the v1.2.4 again. I tested it with a virtual machine and the file is signed, however, it still prompts the above message. The reason in explained here:

> The regular (and often cheaper) Code Signing Certificate shows a warning during installation that goes away once enough users installed your application and you’ve built up trust.

https://www.electron.build/code-signing

Seems like we got the cheaper certificate and I have no idea how long such a process takes for the warning to go away... It took us ages to get the certificate, now this... :)

**Comment by bwgjoseph** [comment]
Hi,

I just downloaded `v1.4.1` and it is still reporting the trust issue as reported

**Comment by tothradoslav** [comment]
Hi, sorry for the late reply. Yes, this is still an issue due to the above reasons. We are considering buying the expensive certificate, but in the meantime, please bypass the alert to let MS know that Mingo is OK. Thank you :)
