### ISSUE TITLE
CTRL+R reloads mingo

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#178]
I keep pressing CTRL+R because I'm used to that but it reloads Mingo but I just want to reload the current query. I think this was already fixed in #81 ?

**Comment by tothradoslav** [comment]
I thought we had solved it but it’s a built-in shortcut that could only be overridden by global OS shortcut which started interfering with other apps, too. It blocked reload in chrome for example :) So we removed it. 

There was an electron bug involved. Will take a look at it again. Thanks

**Comment by tothradoslav** [comment]
I've spent hours on this and can't figure it out. I could catch the key-strokes, but eventually, it bubbles up to Electron which reloads the app and I can't stop it.  Tried all options but I'm stuck here... If you have any experience with this, please let me know. Thanks

**Comment by Christilut** [comment]
This works for me:

```
export default class App extends Vue {
  mounted() {
    window.addEventListener('keydown', (e: KeyboardEvent) => {
      if (e.code === 'KeyR' && e.ctrlKey) {
        e.preventDefault()
      }
    })
  }
}
```

**Comment by tothradoslav** [comment]
Thanks. Does this work in Electron?  It works in the browser (app window) but it does not prevent Electron from catching it and doing its own thing. Even tried bundling a production without devTools, but  no change...

**Comment by Christilut** [comment]
Seems to work for me... I can't reload Electron with CTRL+R with that code added. Dev tools are always open for me.

Maybe you need to combine it a remapped Reload in the menubar. I don't show the Reload button in the menubar at all (but neither does Mingo).

I'm on Windows so maybe that's a difference..

**Comment by tothradoslav** [comment]
Still couldn't figure it out, didn't work for me. Eventually, I hacked it using window.onbeforeunload.

**Comment by tothradoslav** [comment]
CTRL+R reloads docs
CTRL+SHIFT+R reloads the entire app (left it there for dev / testing purposes for now)
