### ISSUE TITLE
Adding a connection to a project is blocked when one DB cannot be reached

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#180]
There seem to be some issues here:

1. When my local development db is shut down I cannot edit my project.

2. Even when everything is up I sometimes get an error for one db not being available (just now about our prod db which ... is not true ;) ) This doesn't happen consistently though, I don't see any obvious logs that could help debug it.

**Comment by tothradoslav** [comment]
I tried point 1 and after a few seconds (timeout) a got this:

<img width="946" alt="Screenshot 2020-04-07 at 00 05 36" src="https://user-images.githubusercontent.com/3465808/78609741-a1cec700-7863-11ea-9823-7f94e6968750.png">

What do you mean by "cannot edit my project"? Cannot save changes to it? 

I'll move on to point 2 after we figure this one out :)

**Comment by GriffinSauce** [comment]
Yeah I can't save it. So when my local db is down I cannot add/remove any other databases (ie. dev, staging, production)

I was migrating our production database, to add the new connection I had to turn on my local mongo even though it's completely irrelevant for the task.

**Comment by tothradoslav** [comment]
Well, this is a good point. Should this be allowed or not? 

Mingo checks the connections upon submit. This could be ignored, but then you might not notice an issue with connection settings of the DB you just added. What do you think should be the best way to go about this?

**Comment by GriffinSauce** [comment]
Fair point, I'd change the "error" to a "warning" state and allow the user to continue.

- normal state -> [Save]
- loading state -> button disabled with loading animation
- warning state -> mark bad connections + button enabled with [Continue anyway]

It might also be good to add some copy like "There was a problem connecting with one of your databases, please check the marked connections" for clarity.

Showing the warning can be super helpful, blocking when the warning can be ignored is not.

**Comment by tothradoslav** [comment]
This was a tougher one. There's a bug in mongodb driver with connection timeout, so had to hack it, but see how you like the solution and will work on improvements.
