### ISSUE TITLE
Remove docs popup

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#183]
![image](https://user-images.githubusercontent.com/3471363/78595649-af2b8780-784a-11ea-997b-9b79b611de60.png)

`null documents`

This happened after I was asked if I wanted to unlock this tab for 10 minutes.
I think the selected documents got de-selected causing it to say `null`. Not sure why but maybe the deselect came from the unlock popup.

**Comment by tothradoslav** [comment]
thanks, corrected
