### ISSUE TITLE
Loader or progress during remove

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#184]
I just removed 360k useless log docs from my db which took about 10 seconds. But during that time I was able to do everything in Mingo, including unselecting the documents I was in the process of removing.

There should be a loader here that prevents the user from doing potentially dangerous or weird things. Would be really nice if there can be a progress indicator, if that's possible at all.

**Comment by tothradoslav** [comment]
Have you used the "select all documents" and then "remove documents" option? Or did you clear collection completely?

**Comment by tothradoslav** [comment]
I created a configurable cover-all loader that we can use in such cases in Mingo.  Applied it now to the "remove documents" (multi-select action). If other places pop up where we could use it, will add. Please let me know. Thanks.

**Comment by Christilut** [comment]
I queried for documents first and then selected the header to delete all documents in my current query results.

**Comment by tothradoslav** [comment]
ok, then that's done :)
