### ISSUE TITLE
Dragging element

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#185]
![image](https://user-images.githubusercontent.com/3471363/78983212-0f107f80-7b24-11ea-97c5-b984dc3c6c6c.png)

Here's a fun bug. I dragged the plus icon into the query field accidentally and it dropped `file:///C:/Users/Alpha/Documents/programs/mingo/resources/app.asar/dist/electron/index.html#` into the query field.

**Comment by tothradoslav** [comment]
Yep, this is fun :)
