### ISSUE TITLE
ObjectId is not defined in shell

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#201]
![image](https://user-images.githubusercontent.com/3471363/83643530-68d77800-a5b0-11ea-9204-8ab93c0583c4.png)

![image](https://user-images.githubusercontent.com/3471363/83643538-6b39d200-a5b0-11ea-815d-6c787e0ea140.png)

Am I doing something wrong in the query? I think this is the correct way according to the MongoDB docs.

**Comment by tothradoslav** [comment]
In JS mongodb driver, it's actually ObjectID (capital D), but we had this the wrong way, too. It's corrected. I also added an alias under the name ObjectId, so you'll be able to use both.

**Comment by Christilut** [comment]
Actually now I can't use either `ObjectId` or `ObjectID`

![image](https://user-images.githubusercontent.com/3471363/90021032-ffab6980-dcb0-11ea-84eb-9de25676abe9.png)

**Comment by tothradoslav** [comment]
Yep, it was missing in the context, I added it. Just wasn't clear from my reply, sorry. It will be there from new version.

It will also be possible to run more complex JS code in NodeShell with the new version, using loops, conditions, etc...

**Comment by Christilut** [comment]
Very cool, I really miss that!
