### ISSUE TITLE
Limit results

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#202]
Is there a way to limit the results in a query? I'm sorted by `createdAt` and I only care about the last few results in a huge collection that takes long to query.
I don't see any way to add the `limit` parameter.

**Comment by tothradoslav** [comment]
I guess you mean in documents viewer. There's no limit option, because you can sort it by {createdAt: -1} and there's pagination. So you see the last results. 

But maybe you need it for a different use-case, in that case let me know. Thanks.

**Comment by Christilut** [comment]
Well my server keeps giving a timeout in Mingo (not sure why, haven't had time to investigate) but my usual workaround is to limit results. Without limit it does a full document scan on all documents in certain cases. Usually happens when I'm searching my logs for old data for one specific user.

**Comment by tothradoslav** [comment]
I'll check out our internal timeout settings, however, there's always a limit in the background as we only show the first 50 documents on first page. So limit is automatically added always: {limit: 50}.

Not sure about the size of you collection, but maybe an index is missing? I usually get timeouts on aggregations with "left join" that are really complicated. Otherwise, never in documents.

**Comment by Christilut** [comment]
Yeah these are regex searches in the logs so I'm expecting them to take long, but the timeout is preventing the search from completing

**Comment by Christilut** [comment]
I think it was 2 index related inssues for me. Did some digging and added a compound index that solved the performance problem.

I did notice that when creating an index in Mingo, that the connection would still timeout. Creating the index takes about 30s here and the connection times out after about 5s but it still continues in the background.

**Comment by tothradoslav** [comment]
Thanks. Will increase / remove the timeout.

**Comment by tothradoslav** [comment]
we had a 5sec timeout, turned it off, uses default value now
