### ISSUE TITLE
Full text CTRL-A

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#203]
When pressing `CTRL+A` to select all in a text field, it also selects the entire UI.

![image](https://user-images.githubusercontent.com/3471363/83738939-3a5fa880-a655-11ea-9b12-1abee60368f6.png)

**Comment by tothradoslav** [comment]
This should be the "desired behaviour" unless the "select all" is caught in documents to select all docs. 

I added a "copy entire text" button in this modal, too. Let me know if this is OK.

**Comment by Christilut** [comment]
Isn't it easy to override the keyboard listener when the modal is open?

What happens in the screenshot is never supposed to happen right? It's not very useful

**Comment by tothradoslav** [comment]
It's easy, but it didn't work on windows :) Mac is fine. Will find the reason / solution.

**Comment by tothradoslav** [comment]
resolved for next version
