### ISSUE TITLE
Deeplink error

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#213]
Getting this error:
```
Deep link incorrect: TypeError: r.replace is not a function
```

With this deeplink:
```
mingo://rekordcloud/production/documents/tracks/%7B%20library:%20new%20ObjectID(%225f74afe23ff5ed31ef3da7ee%22)%20%7D?useCurrentTab=false
```

I haven't changed the deeplink for a long time.

**Comment by Christilut** [comment]
Seems to only happen if Mingo is already open

**Comment by tothradoslav** [comment]
There should a log right before the "Deep link incorrect" error. Could you paste it here?

**Comment by Christilut** [comment]
![image](https://user-images.githubusercontent.com/3471363/94779044-8aae0380-03c6-11eb-9e5d-4de17d44dd8a.png)

**Comment by Christilut** [comment]
![image](https://user-images.githubusercontent.com/3471363/94779093-a0232d80-03c6-11eb-91e8-831706b85bf6.png)
