### ISSUE TITLE
Empty pages after the second page

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#214]
I have a collection of 335 docs:
![image](https://user-images.githubusercontent.com/3471363/95060784-037cca80-06fb-11eb-86f6-3e968ca54d2f.png)

And it shows 7 pages total, which is correct:

![image](https://user-images.githubusercontent.com/3471363/95060826-1394aa00-06fb-11eb-93ff-d5ca44adfea3.png)

But the docs only go to 72:

![image](https://user-images.githubusercontent.com/3471363/95060850-1e4f3f00-06fb-11eb-8df1-0e52a834783a.png)

Any page after this is empty.

**Comment by tothradoslav** [comment]
I just went through several collections to try to reproduce but without success 👍 
Could you take a look at the console? Maybe there's some more info. This is really weird.

Thanks!

**Comment by Christilut** [comment]
There is nothing in the console. Even after restarting Mingo, it still does this.

Maybe what caused it is that the collection was about 70k items before. I deleted almost all of them (335 were left after the delete) with the edit button (`deleteMany`). Then it started doing that.

**Comment by tothradoslav** [comment]
Did you delete those doc uaing mingo? 

Wondering if this is a mongodb issue that it would still tell you a wrong number docs or is there a cache a mongodb. Because the count ia never cached and updated with each query. 

Have you seen this behaviour with othe collections?

**Comment by Christilut** [comment]
First time this happened. I did delete them with Mingo yes.

**Comment by tothradoslav** [comment]
Could you try the following the NodeShell?

`db.collection("YourCollectionName").count();`

**Comment by Christilut** [comment]
I only have this problem locally now. Mingo says 279 docs but there are only 16.

This is the count output:
![image](https://user-images.githubusercontent.com/3471363/95302336-1cfc4e80-0882-11eb-836f-da90bca1800c.png)

Still 7 pages though, last 6 are empty.

**Comment by tothradoslav** [comment]
That really seems like a MongoDB issue, since that's the response from mongo directly... 

Tried to google it and found this:

https://stackoverflow.com/questions/30715466/incorrect-count-returned-by-mongodb-wiredtiger

**Comment by Christilut** [comment]
Maybe use countDocuments instead? Might be slightly heavier in performance but that call isn't used so often that it becomes a problem?
