### ISSUE TITLE
Database collapse

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#217]
![image](https://user-images.githubusercontent.com/3471363/95654025-6906f780-0afd-11eb-96e1-917a3b724289.png)

Right now all other databases collapse when you expand one but I find this behavior a bit annoying. I prefer to leave open what I had opened because that makes switching between local/production much easier.

**Comment by tothradoslav** [comment]
You are right, this was a dilemma for me, too. But I can easily change this behaviour. 

However, did you know you can "pin" collections (right click on a collection in sidebar)? Pinned collections will be shown even if you collapse the database. I use this to keep the most often used collections always visible (some of my dbs have 50+ collections).

**Comment by Christilut** [comment]
I didn't know that, I like that a lot. I'll use that for a while now
