### ISSUE TITLE
Pressing Node.js shell clears current input

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#219]
1. Click `Node.js Shell`
2. Type a fun long query
3. Click `Node.js Shell` again
4. Everything is gone

I expected it to open in a second tab

**Comment by tothradoslav** [comment]
Thinking about the solution... Basically, a click on the sidebar will set the state of the current tab. CTRL (cmd) click would open a new tab and would not touch the current one.

Options:

1. if the link you clicked on is the one that's opened in current tab, do nothing (or maybe ask for confirmation). However, if you clicked away without saving your work, it would be still lost when you return. 
2. always remember the last state of the input and open the new tab with the last state which means you won't notice anything in this case.
3. always open sidebar links into new tabs

What do you think?

**Comment by Christilut** [comment]
I would always open a new tab if it means work would otherwise be lost. Work should never ever be lost.

Possibly show a popup: Do you want to open this in a new tab? "New tab", "Existing tab" with checkbox "do not show this again"

**Comment by tothradoslav** [comment]
ok, set to open in new tab always, we'll see how it goes, but I like it so far (testing locally)
