### ISSUE TITLE
User select

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#221]
![image](https://user-images.githubusercontent.com/3471363/98097467-55954500-1e8d-11eb-92e1-63d0cbcdefe0.png)

This is kind of ugly in an application. I would put `user-select: none` on all non-input elements.

**Comment by tothradoslav** [comment]
Great observation! I have set the user-select in some parts of the app, but kept it in documents viewer, for example, where you might want to select a piece of text or value to copy it.
