### ISSUE TITLE
Aggregator error

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#223]
![image](https://user-images.githubusercontent.com/3471363/100329154-9a645580-2fcd-11eb-8d4f-a5abf41fa69d.png)
![image](https://user-images.githubusercontent.com/3471363/100329182-a4865400-2fcd-11eb-924a-51c246b8702d.png)

Very simple query, can't seem to get it to work

**Comment by Christilut** [comment]
Seems to be because debtor is an ObjectID but I used it as a string. Although a better error there would be nice. Or auto cast to ObjectID

**Comment by Christilut** [comment]
Same error again after changing it to this query:
```
{
  "active": true,
  "debtor": new ObjectID("5c01401c9ca615005c17205e"),
  "createdAt": {
    "$lt": "2020-11-26T08:31:50.681Z"
  }
}
```

Seems it doesn't like the date string.

**Comment by Christilut** [comment]
Changing it to this works:
```
{
  "active": true,
  "debtor": new ObjectID("5c01401c9ca615005c17205e"),
  "createdAt": {
    "$lt": new Date("Thu Nov 26 2020 09:31:50 GMT+0100 (Central European Standard Time)")
  }
}
```

But that's super annoying to write. It's weird that `new Date("2020-11-26T08:31:50.681Z")` doesn't work but I had to go into a JS console and do `new Date("2020-11-26T08:31:50.681Z").toString()` first and copy the result into Mingo

**Comment by tothradoslav** [comment]
ObjectID:
- autocasting is not really possible in this case, as I can't distinquish between a arbitrary string or a possible objectID
- however, I corrected the "total of undefined" error and it shows regular "No results found". There isn't much more we can do here as I could type anything in there, such as `{"asdf": "aksdfjasdfkjaksdfjasldf"}` and the system has no idea it's a mistake
- let me know if you have a better idea to improve this

Dates:
- you could use `new Date("2020-11-26T08:31:50.681Z")`
- or you can even use Mingo readable dates like this:

`{
  "system.createdAt": #last30days
}`

- it may be a good idea to let people know about this option

**Comment by Christilut** [comment]
Well the objectId is always 24 characters, lowercase and hexadecimal. The first 4 bytes are the timestamp, you can make conclusions from that too. If the timestamp is too far into the future (24 hours? timezones are hard) then maybe assume it's not an ObjectId.


I used `new Date("2020-11-26T08:31:50.681Z")` but didn't work. That's what I found strange.

**Comment by tothradoslav** [comment]
The "new Date" issue is strange, the following works for me fine and returns proper results:
`{
 createdAt: {$lt: new Date("2020-03-01T08:31:50.681Z")}
}`

Maybe there's a different problem? I tried several dates and the results were fine.

Regarding the ObjectID issue, your solution is great. However, I have had an issue / feedback from a friend telling me they are using ObjectID-like strings as ids, but in string format. In his case, auto casting would make it unusable, unless we implement a workaround or an exception. Or, internally the query could be updated as following:

` {"debtor":  "5c01401c9ca615005c17205e"}`

would be casted / updated to (in the background only):

`{$or: [{"debtor": new ObjectID("5c01401c9ca615005c17205e")}, {"debtor": "5c01401c9ca615005c17205e"}]}`

What do you think? I'm trying to avoid too much "magic" happening in the background.

**Comment by Christilut** [comment]
Maybe a setting that it doesn't auto cast these for these users?

**Comment by tothradoslav** [comment]
Should this be a local or global setting? Would it be in global settings or just for the aggregator? Also, each DB could have a different ID type...

**Comment by Christilut** [comment]
I'd say global, leave it on by default. Users that are bothered by it will turn it off.

You could go further and let users create their own regex for their ID type.

**Comment by tothradoslav** [comment]
Actually, Mingo knows what type of ID your DB uses, so we could use that info and do it automatically.
