### ISSUE TITLE
Appending the ability to put off automatic starting of aggregation in aggregator tab

### ISSUE THREAD

**Issue by DestroyerOfCode** [mingo-app/mingo#228]
Whenever I write an aggregation in a +10MB size collection, it takes a few seconds to finish the statement. As the software starts the query statement after chaning but a character, it becomes so slow that mere typing is delayed by a few seconds.
Thus I need to have total control on when to start each query. 
Has this been implement and I have only not found it? If not, please implement it.

**Comment by tothradoslav** [comment]
Maybe an "Autoload samples" with on/off (checkbox) would suffice?

Also, please, what is your operating system and Mingo version?

**Comment by DestroyerOfCode** [comment]
18.0.4 linux ubuntu
I only downloaded this morning, so the latest one

**Comment by DestroyerOfCode** [comment]
@tothradoslav  and inded, such a functionality would totally awesome.
IMHO autoloading samples saves time when working with smaller collections but working with huge datasets is made practically impossible.
