### ISSUE TITLE
Can't install dmg on mac

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#233]
![image](https://user-images.githubusercontent.com/3471363/103099538-29857d00-460f-11eb-9bdc-2c76d7ae6aeb.png)

This is what I'm seeing when I launch it. Might be because I'm on an M1 macbook.
I need to upgrade my own app for M1 too so if I learn anything, I'll be sure to let you know.

**Comment by tothradoslav** [comment]
I see you got a nice christmas present :) 
Will investigate, too, thanks.

**Comment by tothradoslav** [comment]
Latest Electron supports M1

https://www.electronjs.org/releases/stable#release-notes-for-v1111
