### ISSUE TITLE
Error querying localhost

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#235]
![image](https://user-images.githubusercontent.com/3471363/106300463-d4b0d400-6256-11eb-8bd2-58822e5aa0bc.png)

This is on my localhost that has no auth. Used to work in the older mingo version.

Empty query.

**Comment by tothradoslav** [comment]
Is this in the Documents Section?

**Comment by Christilut** [comment]
`{}` as query, in Documents yes

**Comment by tothradoslav** [comment]
Doesn't happen to me, can't reproduce. But I have a feeling that I had that issue, too and solved it.

Does it happen to all collections? Or just specific cases?

**Comment by Christilut** [comment]
All collections.
Maybe related: when I go to my Localhost connection and try to refresh, it gets stuck on "syncing db meta info". It seems to timeout per database.

**Comment by tothradoslav** [comment]
Ok, I think this will be resolved in the next version, already.

**Comment by Christilut** [comment]
Is there a quick workaround? I can't use my localhost at all now :/ And downgrading to mingo 1.3.5 gives a white screen and error on startup

**Comment by tothradoslav** [comment]
try downloading the new release: https://github.com/mingo-app/mingo/releases/tag/v1.4.1-rc.1

**Comment by Christilut** [comment]
Same problem

**Comment by tothradoslav** [comment]
ok, I will work this out. Are you on mac or win?

**Comment by Christilut** [comment]
Windows

**Comment by tothradoslav** [comment]
I found this, seems like it's not even mingo related...

https://stackoverflow.com/a/63670669/3307962

> Check if no other instance of your mongodb is in use.

I checked the entire code and we are not even using the aggregate() command in the documents viewer, at all. It is only used in the following cases:

- Schema Analyzer
- Aggregator
- "Group by and count" option in document field - which is not your case probably.

**Comment by Christilut** [comment]
I'm not doing anything with Mingo and this error is happening. Just one empty tab.

Mongodb otherwise seems to work fine locally, my development server is using it and I'm not seeing anything strange there.

**Comment by Christilut** [comment]
I logged into the server with the CLI and it complains about authentication there too... Something must've changed on my server even though I didn't do anything... Somewhat concerning 🤔 I'll dig into it

**Comment by tothradoslav** [comment]
are you not using your new mac yet? btw, as I was googling for "MongoError: command aggregate requires authentication", I found sme pages describing this as an issue, try this: https://stackoverflow.com/questions/57848302/how-to-solve-command-find-requires-authentication-using-node-js-and-mongoose

**Comment by Christilut** [comment]
Okay found the problem, user error :D
I have Mongdb as a Windows service running, but I was experimenting with running it in WSL2 in Docker a few weeks ago. That didn't really work (port forwarding with WSL2 is still a big problem) and for some reason Docker restarted Mongodb apparently a few days ago. So I had Mongodb running twice and it was giving preference to the WSL2 instance, which had authentication set up. :/

Sorry to waste your time on this!

**Comment by tothradoslav** [comment]
No problem, I'm glad you worked this out :)
