### ISSUE TITLE
Dot feels like there are unsaved changes

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#236]
![image](https://user-images.githubusercontent.com/3471363/106716578-e69bc980-65fe-11eb-85f0-380786ae5a8c.png)

Seeing that dot makes me immediately think there are unsaved changes but it seems to mean that the tab is open. Personally I don't need another visual indicator for that (the tab itself does it already) and it makes me feel nervous because I don't like unsaved changes, even though it means something else here.

**Comment by tothradoslav** [comment]
Hm, never thought of it like this, BUT I just realized that I completely ignored that dot, anyway, so might as well remove it. It's confusing to you and useless for me :)
