### ISSUE TITLE
Mingo freezes with large object subdocument

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#237]
This is definitely bad database design on my part, but this happened:
![image](https://user-images.githubusercontent.com/3471363/106938475-55704400-671f-11eb-9fa3-0bd69965ca71.png)

When I went to this document and tried to open the subdocument, Mingo froze. Didn't seem to recover anytime soon so I had to force quit it.

**Comment by tothradoslav** [comment]
If that one document is not too private, could you send it over via email? Tried very large docs, but never happened to me. Maybe there is something specific?

**Comment by Christilut** [comment]
Mailed you
