### ISSUE TITLE
updating databases in project

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#24]
- mam jednu database ktora mi funguje OK
- chcel som pridat dalsiu... nastavil som URL a dal ze 'save'
- modal sa nezatvoril, pricom dole v rohu sa mi vipisalo "Connection updatet"
- tak som si modal zavrel sam, ale ta druha DB sa mi nepridala... :/

**Comment by tothradoslav** [comment]
vies mi poslat to mongo uri druhe? ze ci tam bola chyba alebo co lebo by to malo cakat
