### ISSUE TITLE
Mingo updates results without permission

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#240]
1. Run any query
2. Open a result
3. Change query (but don't execute it)
4. Try to open another result
5. Mingo automatically runs new query and shows new results

I don't think it should do that because I was still browsing the old results and forming a new query

**Comment by tothradoslav** [comment]
In which section is this? Documents? Export?

**Comment by Christilut** [comment]
In Documents

**Comment by tothradoslav** [comment]
Ok, thanks, corrected in Documents. However, in Export, the functionality is a bit different and the "export samples" are updated whenever you change / blur the query input, so that you see the results immediately. That seemed the best solution for now.
