### ISSUE TITLE
Two tabs of the same collection

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#241]
When I have a tab open of a certain collection (and a query that I'm looking at), sometimes I want to open a second tab of the same collection. But when I try to do that, it switches to the already open tab. So my 2nd tab (blank) will stay blank, it won't go to the collection view.

**Comment by tothradoslav** [comment]
I literally just created a video about navigation, but not satisfied with it, but still you can watch it and it explains this. :)

basically, to open the same collection twice, cmd or ctrl click it. 

If you have better ideas on to handle this let me please know. We wanted to prevent many duplicate tabs.

**Comment by Christilut** [comment]
Maybe an option to automatically switch to the existing collection tab?

Personally I don't mind many tabs, that's how I'm used to tabs anyway (eg Chrome). When there are too many, I just mash CTRL+W until they are gone. That tactic works in Chrome, VSCode and Mingo.

But others users might prefer less tabs so maybe an option for them (and maybe use that as default).

**Comment by tothradoslav** [comment]
So what should be the default behaviour? Once I have a tab open with a specific collection, should a click on sidebar open a new tab or just focus the current one. 

CTRL+click opens a new tab. This is current functionality.

**Comment by Christilut** [comment]
Well that is the difficult part haha. But personally I prefer to always open a new tab. It was like that in Mingo before and it made sense for me.

**Comment by tothradoslav** [comment]
I think we'll go with your suggestion. Was testing it myself and "many tabs" is truly not an issue...
