### ISSUE TITLE
extend Rename field feature

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#242]
add support for: 
- Rename field in selected documents ($count)
- Rename field in filtered documents ($count)
- Custom rename - use https://docs.mongodb.com/manual/reference/operator/update/rename/

- no undo available
- rename field in one document - dont show modal
- don't use modal in rename at all
- after rename - don't scroll up
also provide "Undo" option after "Rename field: all documents"

**Comment by tothradoslav** [comment]
All done, except for "Rename field in selected documents"
