### ISSUE TITLE
Editing a sub-document

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#245]
I often find myself wanting to edit a sub-document but the UI for that doesn't let me easily do that.

![image](https://user-images.githubusercontent.com/3471363/111900749-98b71580-8a34-11eb-94d4-13f84d79a829.png)

This is a small object and is already hard because it's all on one line but bigger ones become near impossible:

![image](https://user-images.githubusercontent.com/3471363/111900805-d9169380-8a34-11eb-9d98-119c203e165a.png)

I would really love a better popup for editing objects. Now I always go into "Edit entire document" but it's counter-intuitive because I already found what I wanted to edit and now I have to find it again in the popup.

ps: As I'm typing this I just found the `Add field` option which somewhat nullifies the need for this, but it's still quite hard to edit a subdocument as text in the mini popup which I do feel can be improved.

**Comment by tothradoslav** [comment]
When you say edit a subdocument, do you mean editing a particular field? Or adding a new field? Or delete a field in subdocument?

For the first case, you can expand the subdocument and then edit the field inside it. 

The inline edit is mainly for editing a field. 
A possible solution: dbl-click on subdoc would open a larger textarea in a modal window. Is that ok?

**Comment by tothradoslav** [comment]
Yeah, that’s what i meant. Dbl cllick or edit would do the same thing. If the value is an object or array, we would open a textarea instead of online input.

**Comment by Christilut** [comment]
Sounds good

**Comment by tothradoslav** [comment]
For now, I have just made a "stupid-simple" solution with textarea on objects / arrays. Works OK. A separate modal would be probably better, but involves a lot of changes I didn't want to risk in first step. Let me know if this solution is OK for you.
