### ISSUE TITLE
Strings getting escaped multiple times

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#246]
I added a string property to a document with a multiline content using backticks:
```
`this
is
the
content`
```

After saving and opening it, it is now all on one line as `this\nis\nthe\n\content` which is correct but when saving that again (without making changes), it becomes: `this\\nis\\nthe\\ncontent`. Another slash is added every time it is saved.

**Comment by Christilut** [comment]
It only seems to happen in the mini editor, not the full JSON editor

**Comment by tothradoslav** [comment]
Are you editing a string? Trying to reproduce, but does not happen to me.

**Comment by Christilut** [comment]
Yes this is a string:
![image](https://user-images.githubusercontent.com/3471363/112895261-2c47b080-90dd-11eb-959c-89348c405db8.png)

![image](https://user-images.githubusercontent.com/3471363/112895293-3669af00-90dd-11eb-8c21-56d66f2ba7f9.png)

![image](https://user-images.githubusercontent.com/3471363/112895302-3b2e6300-90dd-11eb-82d3-abffcb5d71a4.png)

**Comment by Christilut** [comment]
Look like it happens when I open the mini editor
