### ISSUE TITLE
Update does not download

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#249]
Just saw the new release and immediately used `Check for updates`

It tells me there is a release but when I press `Download`, nothing happens.

On Windows 10. Nothing in console either.

Related bug: when pressing `Check for updates`, it opens two dialogs

**Comment by tothradoslav** [comment]
Do you get the notification from Github? Because I accidentally published the release on mingo.io a few minutes before it completed uploading to Github. Can you try now? On mac I tried running the old version of Mingo and downloaded and installed OK.

**Comment by Christilut** [comment]
Still doesn't seem to do anything

**Comment by tothradoslav** [comment]
Ok, will look into this. Meanwhile, can you download and install the new version manually?

**Comment by Christilut** [comment]
Yep, no problem.

Just noticed that I saw the "Are you sure you want to open Mingo.exe from the internet" popup way below all my windows, so maybe that was why it didn't do anything. It was probably there all that time blocking the other attempts.

**Comment by tothradoslav** [comment]
Could we test this with the next minor version whether it will update automatically? I just tested it locally on windows and worked fine.

**Comment by Christilut** [comment]
Sure thing, I'll use the updater every time from now on
