### ISSUE TITLE
Idea: show relative date

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#250]
Just a wild idea that I had, feel free to not do this if you don't like it :)

![image](https://user-images.githubusercontent.com/3471363/113032922-b8ff7680-9190-11eb-86c9-a73c51e01fa5.png)

Dates are shown like this, but I often make mistakes in dates (especially in the new year). 
What would make me more confident in editing dates is that it could show the relative date next to it with color coding.

Maybe something like this:
![image](https://user-images.githubusercontent.com/3471363/113033226-17c4f000-9191-11eb-810e-b1c570168405.png)
And
![image](https://user-images.githubusercontent.com/3471363/113033380-3e832680-9191-11eb-9d9a-f6248cb73055.png)

What do you think?

**Comment by tothradoslav** [comment]
Yeah, that's a good idea. How to implement, though?

1. In preferences, we have the option to select a date format. We could add this as a new date format. But not many people would notice this. Also, this format could be the default.
2. Right-click on a date would give the option to select the date format, with the proposed format included.
3. Add this relative date to any date format.
3. Or we could combine both. 

Questions to consider: 
1. Would the relative date be shown in pinned columns? Seems quite long for that...
2. Relative dates are changing, we need an interval to update these regularly, which may be an overhead, but can be dealt with.

**Comment by Christilut** [comment]
I would go for the third option because I like seeing both the absolute and relative version. 
But there could be an option to hide the relative date, although I don't think anyone is bothered by it. But you can always add an option later based on feedback.

I wouldn't show it in pinned columns.
Relative dates change but maybe you can update them every minute, and maybe only if the document is opened / in view? 
You only need add an update interval if the relative date is low. Anything above 24 hours (or something like that) doesn't need to be refreshed in my opinion. That would be a very much edge case.
