### ISSUE TITLE
Allow resizing sidebar / navigation

### ISSUE THREAD

**Issue by GlennKintscher** [mingo-app/mingo#255]
I am working on a project that has many long collection names that wrap around in the side navigation (in both, compact and comfortable view). As my screen has a lot of space (3072 x 1920 px at 226 ppi), I would love to drag the sidebar a little wider.

![image](https://user-images.githubusercontent.com/23224757/116678242-5f65b400-a9a9-11eb-9a77-f649fd7e3868.png)

**Comment by tothradoslav** [comment]
This ha been requested before so we will implement it in next release. Thanks

**Comment by tothradoslav** [comment]
added in v1.4.3
