### ISSUE TITLE
Problems with connection over SSL

### ISSUE THREAD

**Issue by daveage** [mingo-app/mingo#257]
I have no idea how to connect through ssl. The URI field turns red after a while, and message "Unable to connect to following connections: xy" appears, but I have no clue, what part of that URI is wrong. Whether fails connection or authorization.

Maybe some more elaborative check message could be shown. Like in robo3T when I press "Test" button.

Thanks

**Comment by tothradoslav** [comment]
Thanks. Will improve this.

Do you have a specific hosting you are using?

**Comment by daveage** [comment]
Thank you. We are using our own MongoDB in Docker stack. I can't share any details.

**Comment by tothradoslav** [comment]
We have improved the error reporting and also added the TEST button. Once released, please let me know if it worked for you or we can work on it further.

**Comment by tothradoslav** [comment]
please check out the new release and let me know if this works for you, thanks

**Comment by daveage** [comment]
The test button is missing at the Project Connection form. 

Also the test is not entirely helpfull since it only sais 'Unable to connect to this connection'. 

However I tryed to make SSH tunnel with Termius app, and that led me to realize, that I used wrong domain address in the Mongo URI string. When I changed it to 'localhost', I got connected. 

I consider this issue solved. Thank you.
