### ISSUE TITLE
Add support for SSH agent when connecting using SSH

### ISSUE THREAD

**Issue by GlennKintscher** [mingo-app/mingo#258]
I am using my Yubikey with the GPG SSH agent to connect to SSH servers. Therefore, I neither have a private key file nor a password as the private key is stored on the Yubikey. My current workaround is local port forwarding via SSH but it would be a lot better if Mingo could just use the SSH agent like other programs.

**Comment by tothradoslav** [comment]
Hi, thanks for this. I've never used GPG for SSH so I did my research on it, but still can't wrap my head around it properly :)

I'm guessing that if you have your computer set up with GPG agent, then simply removing the requirement for either password or privateKey would work since there's no need for them?

In the background, Mingo uses tunnel-ssh https://www.npmjs.com/package/tunnel-ssh

**Comment by GlennKintscher** [comment]
Hey, I tested it locally and it works when I do not specify a password or a key file in the tunnel-ssh config. Unfortunately, tunnel-ssh is very outdated and using ssh2@0.5.4, so it does not support ssh-ed25519 keys (support for those were added in ssh2@0.8.3) – so even if you add support for this, it still won't work for me :( I mean you could fork / create your own version of tunnel-ssh if you have the time for it as the original package does not event contain 200 lines of code :)

**Comment by tothradoslav** [comment]
I forked tunnel-ssh, updated the ssh2 version to latest but made no changes in the tunnel-ssh code. Then used it. However, now my existing ssh connections stopped working, it says: 

Uncaught Error: connect EADDRINUSE

Could there be any breaking changes in ssh2? Do you have any idea?

**Comment by tothradoslav** [comment]
Please check out Mingo's new version 1.4.3 if this actually helps. If not, will work on it. Thanks for the patience. :)

**Comment by GlennKintscher** [comment]
Sorry for the delay. Even the latest Version does not work for me (I am running the latest macOS).

**Comment by tothradoslav** [comment]
Ok, working on it. There's an option in tunnel ssh called "agent" which should be the socket path. Is that what you'd need to set for the ssh agent to work?

**Comment by GlennKintscher** [comment]
Yes, that would be great!

**Comment by tothradoslav** [comment]
Hi, we have a new release candidate available. Please take a look and let us know if it works for you.

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.3

Thanks you!

**Comment by GlennKintscher** [comment]
It seems to work so far, thank you very much!
