### ISSUE TITLE
"backend" missing in the options of "create index"

### ISSUE THREAD

**Issue by ymy88** [mingo-app/mingo#259]
When creating new index, the option "backend" is missing in the checkboxes.
I have to input it manually.

Could you add a checkbox for it please?

Mingo version: 1.4.2
OS: macOS 11.3

<img width="827" alt="截屏2021-05-20 13 47 12" src="https://user-images.githubusercontent.com/5236890/118925824-f0f58f80-b971-11eb-821d-cd2a1a0c539a.png">

**Comment by tothradoslav** [comment]
Thanks. Did you mean "background"? I could not find "backend" in documentation.

If you meant "background", we will add it, however according to docs, the background option is "Deprecated in MongoDB 4.2."

**Comment by ymy88** [comment]
Oh, yes, "background". Glad to hear that you will add it. Thanks

**Comment by tothradoslav** [comment]
Also added "hidden" option and improved some options for special index types, such as 2sphere, geoHaystack or text.

Will be available in next release.

**Comment by tothradoslav** [comment]
added  in v1.4.3
