### ISSUE TITLE
Feature Request: Better control of tabs

### ISSUE THREAD

**Issue by dotvhs** [mingo-app/mingo#261]
I really enjoy Mingo but I keep finding myself with too many tabs open. I'd like to suggest a feature that will stop opening new tabs when I single click anything. 

More natural solution would be similar to how browsers accomplish the same thing: either with ctrl+click or shift+click to open in new tab, otherwise open in current tab.

In perfect world this would be a toggle in preferences. Thanks in advance

**Comment by tothradoslav** [comment]
I assume you mean "when clicking on a collection in sidebar".

Changed the behaviour as requested, with toggle in preferences. Default behaviour is "always open in new tab" (current). 

Ready for next release.

**Comment by dotvhs** [comment]
> I assume you mean "when clicking on a collection in sidebar".
Yes, that's exactly what I meant.
> Changed the behaviour as requested, with toggle in preferences. Default behaviour is "always open in new tab" (current).
Wow, thank you, I was not expecting that so fast.
> Ready for next release.
❤️

**Comment by tothradoslav** [comment]
Maybe an improvement: if a tab with the clicked collection already exists, just focus it. If not, open in current tab. CTRL click would always force-open a new tab.

What do you think?

**Comment by dotvhs** [comment]
Sure, then I guess toggle is not even needed, because this feels like should be a standard behaviour.

In my perfect world I wouldn't need every tab for every collection because I sometimes just check something for a short moment and I'm going back where it was. But what you described is a more universal approach and wouldn't add new options to the whole thing, I'm fine with it :)

**Comment by tothradoslav** [comment]
It used to be standard as you mentioned, without "toggle", however, we had some complaints about it. 

For now, left it as discussed above: click opens the collection in current tab, ctrl+click always opens in new tab. Deciding whether to open new tab based on whether that collection is already open would feel like "background magic", so we decided to keep it simple.

**Comment by tothradoslav** [comment]
This has been implemented in the current release candidate. Download and try it at: 

https://github.com/mingo-app/mingo/releases/tag/1.4.4-rc.1

Please let us know if this works fine. Thanks.
