### ISSUE TITLE
Connection timeout is too short

### ISSUE THREAD

**Issue by ymy88** [mingo-app/mingo#264]
The connection timeout is only about 5 seconds in 1.4.3
I cannot even run "explain()"

But it used to be quite long in 1.4.2

How could I config it?

**Comment by tothradoslav** [comment]
You can't config this currently, but we will add this into settings in the next release.

**Comment by tothradoslav** [comment]
This has been implemented in the current release candidate. Download and try it at: 

https://github.com/mingo-app/mingo/releases/tag/1.4.4-rc.1

Please let us know if this works fine. Thanks.

**Comment by ymy88** [comment]
works great, thanks
