### ISSUE TITLE
Multiple Windows

### ISSUE THREAD

**Issue by colbygreen32** [mingo-app/mingo#265]
How can I open another instance of Mingo in a different window? This might already be a feature, but if it is its hard to find.

**Comment by tothradoslav** [comment]
This is actually not available currently in Mingo. We experimented with it already, but it came with some pitfalls. I will rethink this again and will let you know when implemented.

Thanks for the issue, though.

**Comment by colbygreen32** [comment]
Thank you for the quick response. It means a lot. Please let me know if your moving forward with this feature. I payed for the premium version of the product thinking that being able to have multiple connections would allow me to have multiple windows. Thats how it is in Mongo Compass, when you create a new connection a new instance of the mongo compass opens up in a new window. Its a little disappointing that I payed a good chunk of change for a feature I didn't even get :(. Even with that said, the product is very useful, I just could have made due with just the free tier.

**Comment by tothradoslav** [comment]
We will be definitely moving forward with this, probably in the next release.

**Comment by colbygreen32** [comment]
This is awesome!!!! thank you!!!!
