### ISSUE TITLE
Issue Copying Collection to New Collection

### ISSUE THREAD

**Issue by colbygreen32** [mingo-app/mingo#266]
I am not able to copy a collection to a new collection. It says mongorestore is completed but when I look at the other db where the target collection should be there is nothing. Output shows that 0 documents were restored successfully. Output also says "The --db and --collection flags are deprecated for this use-case; please use --nsInclude instead, i.e. with --nsInclude=${DATABASE}.${COLLECTION}". I don't understand what is going on.
<img width="810" alt="Screen Shot 2021-06-12 at 8 53 21 PM" src="https://user-images.githubusercontent.com/46765063/121792239-6d217280-cbc0-11eb-9d99-80906dc8614b.png">

**Comment by tothradoslav** [comment]
Thanks for this info. The deprecation message should not be the issue in this case. But please provide further information:
1. what version of mongodb are you using?
2. what is the version of mongodump and mongorestore?
3. did this work previously and just stopped now? Or is this the first time you tried to use this feature and it failed?

Thank you!

**Comment by tothradoslav** [comment]
@colbygreen32 can you please send the info? thanks!

**Comment by argordmel** [comment]
hello!

I've the same problem.

Mingo: v1.4.5
MongoDB: 4.4.1
MongoRestore: 100.2.1

**Comment by tothradoslav** [comment]
Thanks, what is your operating system?

**Comment by argordmel** [comment]
My operating system is MacOS Big Sur

**Comment by tothradoslav** [comment]
Does Mingo have access to the Downloads directory?

**Comment by solusoftek** [comment]
Hi, same issue here,
Operating system Windows 10, 
Mingo v1.6.2
MongoDB: 5.0.2
MongoTools: 100.5.1

**Comment by paulincai** [comment]
Same here:
macOS Monterey | on M1 machine
MongoDB: dump from 4.4.10 | restore into 4.4.4
Mongorestore/Mongodump: 100.5.1

Copied 3 (small) collections of under 200 records from Mongo Atlas to my local station successfully. Then tried to copy another 3 collection with 30k+ records and got this issue

**Comment by tothradoslav** [comment]
Hi, we have a new release candidate available. Please take a look and let us know if it works for you.

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.3

Thanks you!
