### ISSUE TITLE
Dark tabs

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#267]
![image](https://user-images.githubusercontent.com/3471363/121906231-3451dc80-cd2b-11eb-9cd2-a3b67b4a14ea.png)

I can't really see the tabs in dark mode

**Comment by tothradoslav** [comment]
Do you mean you can't see the "tabby" shape of the tabs in dark mode?

**Comment by Christilut** [comment]
Yep that's right

**Comment by tothradoslav** [comment]
It's actually a new design element for the tabs as it's quite difficult to play with the shades in dark mode. So we changed the tabs. I have to admit they look a bit messier than in light mode. We'll play around with it.

Meanwhile, if you have any ideas, please forward :)
