### ISSUE TITLE
CMD-H on Mac

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#268]
I think the Apple guideline is that CMD-H should hide the current window but it doesn't work in Mingo. I'm not an Apple expert though, so probably good idea to check that :)

**Comment by tothradoslav** [comment]
Found this: `cmd+H hides all windows of an app, cmd+M minimizes the current window to the right side of the dock.`

CMD+M works now, but also added CMD+H in the next release. Thanks!

**Comment by tothradoslav** [comment]
This has been implemented in the current release candidate. Download and try it at: 

https://github.com/mingo-app/mingo/releases/tag/1.4.4-rc.1

Please let us know if this works fine. Thanks.
