### ISSUE TITLE
customize aggregate stage input box height

### ISSUE THREAD

**Issue by wxs77577** [mingo-app/mingo#279]
It can display only 3 stages in full-screen mode, I want to decrease the input box height to 1~3 lines so that I can see more stages at the same time.

**Comment by tothradoslav** [comment]
Thanks for this. I optimized the box height to 4 lines of code, so now I can see 5 stages. 

It would be best to make the box auto-grow, but with the current text editor, this is not possible. Working on our own text editor though....
