### ISSUE TITLE
Show database size

### ISSUE THREAD

**Issue by ismaelheinen** [mingo-app/mingo#282]
On collections hover, and database collections list, is showed total sizes of collectiosn and avg doc sizes.

I don't know if it would be interesting for more people, but for me, it would be nice to also show the total size used in the database.

Thanks, app is great

**Comment by tothradoslav** [comment]
Thanks for letting us know. We added the total size and collections count as a tooltip in sidebar and in database collections list, too. Included in next release.

If you have any other ideas or issue, don't hesitate to let us know.

**Comment by tothradoslav** [comment]
Hi, v1.5.0-rc.1 is available at github, please check it out and let us know if your issue has been properly resolved. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.5.0

Once it's tested, the new version will be officially released.

**Comment by ismaelheinen** [comment]
I saw on the top right, database information, exactly what I was talking about.

Thanks!
