### ISSUE TITLE
The auto-completion doesn't work without quotation mark for non-first field

### ISSUE THREAD

**Issue by ymy88** [mingo-app/mingo#284]
When doing query, the first field always get auto-completion with or without quotation mark.
But for other fields, I have to type the quotation mark to trigger auto-completion:

No quotation mark:
<img width="657" alt="截屏2021-08-27 15 34 02" src="https://user-images.githubusercontent.com/5236890/131090440-62c76bf3-d002-4f11-8b3e-838f3fc4765b.png">

With quotation mark:
<img width="686" alt="截屏2021-08-27 15 34 11" src="https://user-images.githubusercontent.com/5236890/131090475-b48f1813-78df-470b-aaf9-b1c97ad85a0a.png">

**Comment by tothradoslav** [comment]
Thanks for this, corrected in next release.

**Comment by tothradoslav** [comment]
Hi, v1.5.0-rc.1 is available at github, please check it out and let us know if your issue has been properly resolved. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.5.0

Once it's tested, the new version will be officially released.
