### ISSUE TITLE
Deleting connection deletes ALL connections

### ISSUE THREAD

**Issue by Mai-Lapyst** [mingo-app/mingo#287]
When deleting a connection in Mingo (dosnt metter if currently selected or not) it deletes all connections that are present.

### Steps to reproduce:
- Create Connection 1
- Create Connection 2
- Delete one of the Connections
- Find all connections gone

Mingo Version: 1.4.5 (PRO)

**Comment by tothradoslav** [comment]
As hard as I try, I cannot reproduce the error. Are you deleting a standalone connection or a connection from a project?

**Comment by Mai-Lapyst** [comment]
I am deleting a standalone connection. No projects present at all. But I only tested it so far with two connections that use the same connection URL and connections that fails connection. Will test with a second mongo instance today.

**Comment by Mai-Lapyst** [comment]
Update: now tested it with a second mongodb instance, but the error persists. More strangely, when I now add a connection it randomly creates 2 connections.

**Comment by tothradoslav** [comment]
That IS strange, thanks for letting us know. I will try to reproduce the error and let you know.

**Comment by tothradoslav** [comment]
This is related to #288 so should be OK in next release.

**Comment by tothradoslav** [comment]
Hi, v1.5.0-rc.1 is available at github, please check it out and let us know if your issue has been properly resolved. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.5.0

Once it's tested, the new version will be officially released.
