### ISSUE TITLE
Cannot create 2 connection on free tier

### ISSUE THREAD

**Issue by daniel-huesca** [mingo-app/mingo#290]
Downloaded this tool to take advantage of the one click compare and sync solution. I want to test it out but when I try to create a second connection, the create workspace modal appears and then it asks for the license key.

I want to try the product first, and it says 2 connections are supported, but I only have 1 connection configured

**Comment by tothradoslav** [comment]
Hi, sorry for the late response. We are changing the licensing model in the upcoming version but until then I could send you a temporary license for a couple of months to try the tool. Send me an email to info[@]mingo.io and will send you a license key. Thanks.
