### ISSUE TITLE
CMD+W behavior

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#293]
`CMD+W` closes Mingo tabs which is nice but I think that it should also close the window if there are no tabs left to close.

Same for Windows although I haven't tried it there.

**Comment by tothradoslav** [comment]
Ok. What if that is the last window?

**Comment by Christilut** [comment]
On mac it should close the window but keep Mingo running. When you click Mingo in the dock, it should open a Mingo window again.
CMD+Q should completely shut down Mingo

**Comment by tothradoslav** [comment]
After a bit of discussion, we came up with the following:
- CMD+W should close tabs (as now)
- if there's no tab left (except the new dashboard home tab), CMD+W should show a small box saying "Press CMD+W again to close the window"
- we also need to change Mingo's behaviour, as it closes the entire app upon closing the last window

What do you think?

**Comment by Christilut** [comment]
Sounds good. I don't think you need to close the entire app though, just hide the window.

**Comment by tothradoslav** [comment]
Yeah, that's what I meant, just hide the current window.
