### ISSUE TITLE
Download update issues

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#297]
My Windows PC is still on 1.5.0-rc1

When I press `About Mingo`, I can press the `Download 1.5.0` button. The popup closes but nothing happens.

When I click `Check for updates`, I get a message `Current version is up to date`

No errors in the console.

**Comment by tothradoslav** [comment]
It only happens on Windows?

I wonder if this could be caused by the fact that I have deleted the rc1 version from github repository completely... Maybe you updated on mac before windows?

**Comment by Christilut** [comment]
Not sure, but I'll report it again if it happens from the current 1.5.0 version and onwards

**Comment by tothradoslav** [comment]
ok thanks
