### ISSUE TITLE
Is Mingo open source?

### ISSUE THREAD

**Issue by almogtavor** [mingo-app/mingo#298]
Is there any place where the users can view or contribute to the source code of Mingo? Unlike competitors like T3 where there is a Github repo, I couldn't find any for Mingo that contains the source. Any reason for this?

**Comment by tothradoslav** [comment]
Hi, Mingo is not open source. We use Github to distribute beta & prereleases and manage issues. 

Do you have a particular idea or improvement in mind? Would you like to contribute to Mingo?

Thanks.

**Comment by almogtavor** [comment]
Probably if it would be open source so yes because I can't take a look at the code rn. Any reason why it's not open source/ will it be in the future?

**Comment by tothradoslav** [comment]
We decided to make Mingo a paid app and support its development that way.
