### ISSUE TITLE
Cannot Connect To Serverless Atlas Instance

### ISSUE THREAD

**Issue by Zozman** [mingo-app/mingo#299]
When attempting to connect to a Serverless MongoDB Atlas instance, the error `ERROR: Load balancer mode requires driver version 4+` is seen:

<img width="287" alt="error" src="https://user-images.githubusercontent.com/1192364/142742421-4c3823c0-c5c3-47f2-88b3-e57040ba8b70.png">

I don't see a way to update Mingo's driver so not sure what to do to continue using Mingo.

Issue observed using Mingo `1.6.0`.

**Comment by tothradoslav** [comment]
hi, thanks for letting us know, will update the driver version in next patch. We will notify you here.

**Comment by tothradoslav** [comment]
Please check out this release and let us know if it worked for you. We tested it with our serverless database.

https://github.com/mingo-app/mingo/releases/tag/v1.6.1

**Comment by Zozman** [comment]
Can confirm that I can connect; awesome!

1 note though; when selecting 1 or 2 rows apparently I can't export in `1.6.1`.  If I select all then Export works but 1-2 rows does nothing when clicking on `Export`.

![2Docs](https://user-images.githubusercontent.com/1192364/143071077-49f98f9d-13a1-4469-ba82-b16453392c86.png)

**Comment by Zozman** [comment]
In fact I can't get export to work at all.  Don't even see an export option and the Sample never runs.

![export](https://user-images.githubusercontent.com/1192364/143073427-83a6616a-78ab-41f2-aa6f-7ca459c1f080.png)

**Comment by tothradoslav** [comment]
Great, thanks, I corrected this. It was caused by the new driver. We will create a new build and let you know. If you find anything else, please let us know.

**Comment by tothradoslav** [comment]
Please try the new version:
https://github.com/mingo-app/mingo/releases/tag/v1.6.2

**Comment by Zozman** [comment]
Can confirm; export seems to be working.  Thanks!

**Comment by tothradoslav** [comment]
Could you please try this patch if it connects properly to your Serverless Atlas? There were other connection issues so we had to update it. 

https://github.com/mingo-app/mingo/releases/tag/v1.6.3

Thank you.

**Comment by Zozman** [comment]
Yeup, was able to connect on `1.6.3`.

**Comment by tothradoslav** [comment]
great, thanks!
