### ISSUE TITLE
Revoke registered machines

### ISSUE THREAD

**Issue by daviddesmet** [mingo-app/mingo#300]
Is there a way to manage the license so I can drop some machine activations?

I had some troubles with my work computer and it has been replaced 2 times and reinstalled with all the software I use like Mingo. The computer once again stopped working and ended replacing it with a different model, the issue is that I can no longer activate it since I'm getting a "machines count exceeded" message and would like to be able to just drop all the registrations I made for the previous computers.

I've sent an email to `info` but haven't got a reply yet so I'm asking here.

**Comment by tothradoslav** [comment]
Hi, thanks for letting us know. I have not received your email, but we can definitely resolve your problem.

I found you in our db using your github username and cleared the machines you used so far. You should be able to use your license key now again.

Please let me know if this worked.

**Comment by daviddesmet** [comment]
Thanks, I was able to register Mingo.

Btw, any plans to have the option to manage the registered machines on our end? Maybe something simpler like a page where we input our key and get a list of registered machines so we can pick which one to revoke? I know this is not something common but would be nice to have so we don't have to look for ways to reach you guys. I'm just saying since you didn't receive the email and I don't think many customers would know that you can be reached over here.

**Comment by tothradoslav** [comment]
Great.

We have been considering this option for a while now, but Mingo's feature-set has been the priority so far :). We will do this. I will create a new issue with your request. Thanks a lot!
