### ISSUE TITLE
Unable to connect with any database

### ISSUE THREAD

**Issue by argordmel** [mingo-app/mingo#301]
the app was recently upgraded to 1.6.2 but when I try to connect to a MongoDB Atlas it says:

Mingo: 1.6.2
MongoDB: Mongo Atlas
SO: MacOS Monterrey (Intel)

<img width="548" alt="Screen Shot 2021-11-25 at 10 44 56 AM" src="https://user-images.githubusercontent.com/1320168/143470509-56e43852-2e2d-487d-b064-6936902c696b.png">

**Comment by tothradoslav** [comment]
Thanks, this will probably be a problem with the new version of the mongodb driver. Looking into it.

**Comment by tothradoslav** [comment]
Please check out our new release (not public yet) and see if you can connect. Worked on our Atlas connections.

https://github.com/mingo-app/mingo/releases/tag/v1.6.3

Please let me know if worked.

**Comment by josedaniel** [comment]
The error is different now:
![image](https://user-images.githubusercontent.com/120134/143572005-88c23f11-ea45-4a50-8e8e-c9faff7e6a8e.png)

**Comment by tothradoslav** [comment]
So the Compare & Sync worked even though this modal was shown? The feature shown is only necessary for the compare & sync functionality.

**Comment by josedaniel** [comment]
Yes, it worked. It was a weird behavior because at first, it showed the error, then I completely closed the app, reinstalled version 1.5, and to my surprise, it keep crashing with the same message. Then, I retried again with 1.6.3 and it worked again. I have been using the compare and sync tool all day on 1.6.3 and it's working just fine.

**Comment by tothradoslav** [comment]
Please, if it happens again or you find any pattern, let us know. So far, I could not reproduce your error. Also, if you have ideas on how to improve it, we'll be happy to hear them :)
