### ISSUE TITLE
Unable to copy ObjectID fields in 1.6.x

### ISSUE THREAD

**Issue by rashikkathuria** [mingo-app/mingo#302]
Copying ObjectID fields using the context menu not working in version 1.6.x. This is working in 1.5.

MacBook Pro (mid 2015), Intel
macOS Big Sur

<img width="1261" alt="Screenshot 2021-11-26 at 13 05 19" src="https://user-images.githubusercontent.com/10266611/143546350-48fc05b1-fdab-4863-9ecc-78b71484e2ee.png">

**Comment by tothradoslav** [comment]
Thank you, I can confirm the issue, will resolve it. Meanwhile, you can just select the ObjectID string and copy it manually? (CMD+C on field does not work either).  This only happens when copying a ObjectID.

**Comment by tothradoslav** [comment]
Resolved, same issue as in #303

**Comment by tothradoslav** [comment]
Hi, please try the latest release and let us know if it worked. Thank you.

https://github.com/mingo-app/mingo/releases/tag/v1.6.4

**Comment by rashikkathuria** [comment]
Hi, 

Updated to the latest version and confirm the issue is resolved.

Thanks for your prompt response.
