### ISSUE TITLE
Aggregator functionality in ver 1.6.x not working

### ISSUE THREAD

**Issue by rashikkathuria** [mingo-app/mingo#303]
Aggregator not working in version 1.6.x. gets stuck on loading sample documents and CPU usage increases. 

Also adding a new stage does not do anything - maybe because no sample documents are loaded yet.

These are working fine in 1.5.

MacBook Pro (mid 2015), Intel
macOS Big Sur

<img width="940" alt="Screenshot 2021-11-26 at 13 04 55" src="https://user-images.githubusercontent.com/10266611/143546638-536d5487-538e-4550-8fc6-9a3aa8e7971e.png">

**Comment by tothradoslav** [comment]
Thanks for letting us know. What exact version do you have? We have just build a new version 1.6.3 (not public yet) with connectivity fixes. Could you try it?

https://github.com/mingo-app/mingo/releases/tag/v1.6.3

**Comment by rashikkathuria** [comment]
Hi @tothradoslav, 

For me the issue occurs in 1.6.1, 1.6.2 & 1.6.3.

I have downgraded to 1.5 due to this issue and get a prompt to update to 1.6.3 in the app.

**Comment by tothradoslav** [comment]
Thanks, resolved. MongoDB driver changed naming of ObjectID to ObjectId and this was causing the issue. Will let you know when a patch is released.

**Comment by rashikkathuria** [comment]
Thanks @tothradoslav. Look forward to the update being released.

**Comment by tothradoslav** [comment]
Hi, please try the latest release and let us know if it worked. Thank you.

https://github.com/mingo-app/mingo/releases/tag/v1.6.4

**Comment by rashikkathuria** [comment]
Hi, 

Updated to the latest version and confirm the issue is resolved.

Thanks for your prompt response.
