### ISSUE TITLE
Closing mingo is not really closing it

### ISSUE THREAD

**Issue by RokkuCode** [mingo-app/mingo#304]
Closing mingo seems to be quite tricky. Closing it via the "x" in the title bar, does not close it. It is still running but the window is no longer shown and not focusable (you can't get it back).

If mingo is closed via the filemenu or ctrl+q - then it is relly closed.

Is this expected behaviour?

**Comment by tothradoslav** [comment]
Thanks, will look into it. This is only the expected behaviour on macs. Are you using windows?

**Comment by tothradoslav** [comment]
Ok, I found the bug, ready in next release. Thank you!

**Comment by tothradoslav** [comment]
Hi, please try the latest release and let us know if it worked. Thank you.

https://github.com/mingo-app/mingo/releases/tag/v1.6.4

**Comment by RokkuCode** [comment]
Hi. The update fixes the problem. I am on linux (arch). I appreciate your fast replys and solution of the problem. many thanks.

**Comment by tothradoslav** [comment]
I am glad it worked. If you have any othe issues or ideas please let us know.
