### ISSUE TITLE
Updater has no progress feedback

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#306]
I'm pressing the "Check for updates" button and tell Mingo to "Download Now". 
Nothing happens, maybe it is downloading but I can't tell. Even after a few minutes, nothing has happened. No errors in the console.

Windows, Mingo 1.6.2

**Comment by tothradoslav** [comment]
Thanks. Did Mingo install the new version eventually? Or nothing happened at all? 

After restart, do you still have the same version?

**Comment by Christilut** [comment]
Nothing happened, I installed the update manually
