### ISSUE TITLE
Splash has selectable text

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#311]
Tiny thing I noticed, when launching Mingo, you can select the "mingo" text in the blue splash screen

**Comment by tothradoslav** [comment]
Hi, we have a new release candidate available. Please take a look and let us know if it works for you.

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.3

Thanks you!

**Comment by tothradoslav** [comment]
We have just released a new pre-release of Mingo, please check it out and let us know if your issue has been corrected. Thanks!

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.4
