### ISSUE TITLE
Cannot Drop DB

### ISSUE THREAD

**Issue by msenol86** [mingo-app/mingo#314]
![Screen Shot 2021-12-10 at 16 28 06](https://user-images.githubusercontent.com/2547551/145581517-98cb37f9-a1bc-4d3e-a19f-a9763b9fda0a.png)

**Comment by tothradoslav** [comment]
nevermind, I was able to reproduce it and now it's been corrected. Ready for the next releae

**Comment by tothradoslav** [comment]
Hi, we have a new release candidate available. Please take a look and let us know if it works for you.

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.3

Thanks you!

**Comment by tothradoslav** [comment]
We have just released a new pre-release of Mingo, please check it out and let us know if your issue has been corrected. Thanks!

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.4
