### ISSUE TITLE
How can create a backup from all my connections?

### ISSUE THREAD

**Issue by argordmel** [mingo-app/mingo#315]
hello! 

Is it possible to create a backup from all my connections? copying some folder or something?

OS: MacOS Monterey
Mingo: 1.5.0

Thanks!

**Comment by tothradoslav** [comment]
Hi, what do you mean by connections? Do you mean data (collections and documents) or do you mean connections and projects setup? Maybe you would like to use mingo with current setup on a different computer?

**Comment by argordmel** [comment]
I want to create a backup for all connections and projects setup to a different computer

**Comment by tothradoslav** [comment]
In the main menu, use File -> Export Mingo state. Then on the other computer, use import.

**Comment by argordmel** [comment]
Thank you so much! it works!
