### ISSUE TITLE
Shortcut for comfortable view not working

### ISSUE THREAD

**Issue by heyitstay11** [mingo-app/mingo#316]
Ctrl+ + shortcut is not working

Window _zooms_ in from the top bar View dropdown, but when i use Ctrl++ it does not works.
Ctrl+- is working properly

**Comment by tothradoslav** [comment]
Thanks, is this on Windows? Just looked at it on a mac and worked fine.

Also, there are only 2 states (compact, comfortable) so if you are already in comfortable, it won't work (just a reminder).

Could you take a look in the devtools to see if there are any logs / errors in the console? That would help. Thank you

**Comment by heyitstay11** [comment]
i made a blunder  😅, I was doing Ctrl + = the whole time instead of Ctrl + Shift + =.
The dropdown only shows two keys to press (Ctrl key and + key) it is little confusing.
Maybe change Ctrl++ to Ctrl+Shift+= in the dropdown

**Comment by tothradoslav** [comment]
That's weird, because it should work with CTRL++, without Shift. Maybe that's different on windows?

**Comment by heyitstay11** [comment]
It registers + key only when shift key is also pressed,

![output logs, showing + key is register only when shiftKey is true ](https://user-images.githubusercontent.com/74863317/146174261-63e2bb29-fe41-4501-aafc-777f71dc6e2d.png)

**Comment by tothradoslav** [comment]
Ok, I think I understand your point now. When you want to type a + sign on your keyboard, you have to use shift+key, otherwise it's a minus (-), right?

Well, maybe we could change this behaviour, because there are only two states (compact, comfortable) so any of these keys could just toggle it. What do you think?

**Comment by heyitstay11** [comment]
Yes :thumbsup: , Vs code also zooms in and out of view using Ctrl + key and Ctrl + Shift + key

**Comment by tothradoslav** [comment]
We have just released a new pre-release of Mingo, please check it out and let us know if your issue has been corrected. Thanks!

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.4
