### ISSUE TITLE
Issue while Creating Graph in the Dashboard

### ISSUE THREAD

**Issue by wohlig** [mingo-app/mingo#317]
While we are creating graph in the dashboard, the preview of the graph is coming fine but when we save and add to dashboard that time its giving us error. Refer the screenshot for the reference: https://ibb.co/Sd4jhcV

**Comment by tothradoslav** [comment]
Hi, in the first step of creating the chart, what chart type did you choose? Could you send me a screenshor or other reference of the error? Thank you!

**Comment by tothradoslav** [comment]
Hi, is this still an issue?

**Comment by tothradoslav** [comment]
Hi,

we have just released an RC with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please, let us know if it's OK or send us feedback. Thank you!

**Comment by tothradoslav** [comment]
We have just released a new version with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2

Please, let us know if it's OK or send us feedback. Thank you!
