### ISSUE TITLE
Price mismatch

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#319]
The price shown at the first start of Mingo is lower, than the price on the website, where you actually can buy it. I assume that you meant 49€/year, not 19.

![image](https://user-images.githubusercontent.com/1028647/147264927-51a59ac3-f0b4-46bc-b803-01b25a2254d3.png)

**Comment by tothradoslav** [comment]
Hi, yes, sorry for the late reply, this has been corrected in the latest release.

We have just released a new pre-release of Mingo, please check it out and let us know if your issue has been corrected. Thanks!

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.4
