### ISSUE TITLE
Unable to delete a database from a Project

### ISSUE THREAD

**Issue by ptrin** [mingo-app/mingo#321]
I'm attempting to test out Mingo for the first time but I haven't been able to connect to my MongoDB Atlas databases (separate issue) and also I hit an error while removing an empty (unsaved) database from a Project:

<img width="1312" alt="Screen Shot 2021-12-27 at 2 06 30 PM" src="https://user-images.githubusercontent.com/383887/147500290-654bc8c7-6568-40d8-b8b0-6495945655f1.png">

A "delete database" confirmation modal quickly shows, then is replaced by the "Save anyway?" confirmation modal.

<img width="1312" alt="Screen Shot 2021-12-27 at 1 56 43 PM" src="https://user-images.githubusercontent.com/383887/147499852-5eeba6ea-7fea-4b3c-8187-55855306e468.png">

It looks like no combination of clicking "No, return" or "Save anyway" etc. will work around the bug.

**Comment by ptrin** [comment]
It looks like I can't delete the Project itself either.

**Comment by tothradoslav** [comment]
Hi thanks for this. This issue has been solved in the upcoming version which should be out january first week. Will send you a message here when it is out. Thanks again!

**Comment by tothradoslav** [comment]
We have just released a new pre-release of Mingo, please check it out and let us know if your issue has been corrected. Thanks!

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.4
