### ISSUE TITLE
Linux client stuck at welcome screen

### ISSUE THREAD

**Issue by Vallefor** [mingo-app/mingo#322]
I was looking some mongodb client and found Mingo. My OS is Manjaro, so I downloaded Appimage file and run it.
After start I see welcome screen.
![image](https://user-images.githubusercontent.com/1270687/147555977-55ed776e-dd1f-4aad-b508-ddf127c04416.png)

I added one project and two connections 
![image](https://user-images.githubusercontent.com/1270687/147556127-73c0100b-d099-49de-b6ab-bbc803a26e52.png)

I closed connection manager and... I can't moving on. App is stuck at welcome screen.
I still see "Add your first connection" button. I can click on it and see my connections and project.

I tried to install it from deb, tried to do factory reset. Nothing work.
If I open dev tools and try to open tab or close tab I see this errors:
![image](https://user-images.githubusercontent.com/1270687/147556723-3fbbec51-d518-487b-b806-abca498694fe.png)

**Comment by tothradoslav** [comment]
Hi @Vallefor , thank you for letting us know even though your app didn’t evet start properly, really appreciate it. 

Based on the logs you sent, we should be able to correct it. 

Also, in the meantime, we have a new release candidate which you could try:

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.3

**Comment by Vallefor** [comment]
Thanks for answer.
Seems that RC3 works fine. At least sidebar and data from DB are visible and I can play with it while trial is active.

**Comment by tothradoslav** [comment]
Ok, great, let me know your thoughts, thanks!
