### ISSUE TITLE
Cannot close home tabs

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#323]
Once new home tabs are opened, they cannot be closed (there is an X on all but the first home tab, but it is not functional).

**Comment by tothradoslav** [comment]
We have just released a new pre-release of Mingo, please check it out and let us know if your issue has been corrected. Thanks!

https://github.com/mingo-app/mingo/releases/tag/v1.6.5-rc.4

**Comment by brianlukoff** [comment]
Works in this new release - thanks!
