### ISSUE TITLE
Edit JSON Editor TINY OMG

### ISSUE THREAD

**Issue by patriotphoenix** [mingo-app/mingo#325]
When editing a document the modal popup that displays the textarea to modify a document's JSON string has a GUI that is so small. 

1. Can the modal be larger.
2. Can the font size be increased?

Also, while an edit modal is opened if you click on Preferences it loses your edit modal and thats a bad user experience that may actually force me to stop using this product. I literally just purchased a license and am shocked. Am I the only one?

**Comment by tothradoslav** [comment]
Hi @patriotphoenix , 

thanks for the great feedback. All three issues are corrected. We increased the modal size and font size. We also made sure we check for changes in the edited document and if it has been changed, Mingo will not close the modal without your confirmation. Checking for unsaved changes was already implemented, however, opening another modal directly (such as Preferences) could override this. I'm sorry for the bad experience.

If you find any other issues, or have ideas, please let us know. We try to solve all issues within a few days and release the changes with next release. Thank you.

**Comment by tothradoslav** [comment]
Available in the latest release: https://github.com/mingo-app/mingo/releases/tag/v1.7.1
