### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#327]
I'm seeing idle CPU usage in the 15-25% range with 7 tabs open, using the latest RC. Maybe a regression of #244?

**Comment by tothradoslav** [comment]
You could not believe what caused this... A spinning icon that had visibility: hidden, instead of display: none :)

Thanks for letting us know, ready for next release...

**Comment by brianlukoff** [comment]
Thanks for the quick fix!

**Comment by brianlukoff** [comment]
Is this out in 1.6.5? I'm still seeing the behavior in that release.

**Comment by tothradoslav** [comment]
Nope. It was corrected after the release. Will let you know when we release a patch.

**Comment by tothradoslav** [comment]
Available in the latest release: https://github.com/mingo-app/mingo/releases/tag/v1.7.1
