### ISSUE TITLE
About box locks up the app

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#328]
When opening the About box on the Mac app, the background of the app dims but no dialog appears, and there is no way to go back -- you must restart the app.

**Comment by tothradoslav** [comment]
Yep, we found this issue right after we released the version so we just updated the bundle for the same version. If you re-download the bundle from here and reinstall it, it's gone. Sorry for the inconvenience.

https://github.com/mingo-app/mingo/releases/tag/v1.6.5

**Comment by brianlukoff** [comment]
Thanks -- works now!
