### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#329]
What do you think about the ability to flag a connection as a "production" connection. In this mode, the big dangerous features (e.g., drop database, drop collection, truncate collection) would be completely disabled. (This would be like "termination protection" with Amazon EC2 instances.)

**Comment by tothradoslav** [comment]
We have a feature to lock a database which is on by default. Then you can temporarily unlock a db or completely. But I guess you would prefer a complete blocking mode so that those features you mentioned would be completely disabled?

**Comment by brianlukoff** [comment]
Right -- the locking feature is great. I'm thinking an extra layer of protection -- for a production database I don't want it to ever be possible to take an action that destructive. (If I ever need to for some sort of maintenance reason -- which would be rare -- it wouldn't be a big deal to have to change a setting on the connection explicitly.)

**Comment by tothradoslav** [comment]
Yeah. I like the idea. We’ll introduce it somehow

**Comment by brianlukoff** [comment]
Thanks!

**Comment by tothradoslav** [comment]
Hi, we have implemented this in a bit different way, but it solves your issue. In next release...

**Comment by tothradoslav** [comment]
Available in the latest release: https://github.com/mingo-app/mingo/releases/tag/v1.7.1
