### ISSUE TITLE
Minor export bug and feature enhancement request

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#331]
A small bug: If I am on the Documents tab and click the Export tab, Mingo switches over briefly and then jumps back to Documents. Clicking Export a second time then works.

And a related feature request: it would be great for the Export filter to default to the same filter as is currently active on the Documents tab, as that seems like a common workflow for me (search in the Documents tab, and then decide to export in the Export tab).

**Comment by tothradoslav** [comment]
I'm unable to reproduce the bug you mentioned. Will test it with colleagues, too. Could you maybe send a short screen video or is that too much to ask? :)

Regarding the feature request, we'll implement this. Just thinking whether it should happen in background automatically (like magic) or should users confirm this? Also, you can do this by clicking at the dropdown button by the "Submit" button and choose "Export Documents"

<img width="281" alt="Screen Shot 2022-01-19 at 08 41 15" src="https://user-images.githubusercontent.com/3465808/150085902-999bf655-0d8e-485c-8b26-644deb03655c.png">

**Comment by brianlukoff** [comment]
That's great -- I didn't realize exporting the results of the query was an option in the dropdown. That makes the feature request less important to me since there is another easy way to do it!

I'll email you a screen recording.

**Comment by tothradoslav** [comment]
Thanks for he recording, I found the bug and corrected it :)

We also discussed the other feature request for the "Export" and for now we decided not to change that behaviour to avoid confusion of something automatically happening in the background like magic.

Thank!

**Comment by brianlukoff** [comment]
Sounds good -- I agree that having that option in the dropdown is enough.

**Comment by tothradoslav** [comment]
Available in the latest release: https://github.com/mingo-app/mingo/releases/tag/v1.7.1
