### ISSUE TITLE
[Request] Generating Graphql Schema

### ISSUE THREAD

**Issue by emehmet** [mingo-app/mingo#332]
Hi,

Thank you for great project.

It would be great if we could convert a collection from the data or schema structure in it to a Graphql schema.

Maybe it is in the program but I couldn't find it. I do not know.

Thank you!

**Comment by tothradoslav** [comment]
Thanks for the request. We will definitely look into this and implement. Meanwhile, if you have specific ideas on implementation, please let us know.

**Comment by emehmet** [comment]
I'm using the following package to convert to gql, but it's not that good. But it would be great if it was in your software.

https://www.npmjs.com/package/json-to-graphql-typesystem

Thank you!

**Comment by tothradoslav** [comment]
Done, you will find it in the Schema section under "Export as GraphQL schema". Available in next release.

**Comment by emehmet** [comment]
Really thanks. This is very good news :)

**Comment by tothradoslav** [comment]
Hi,

we have just released an RC with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please, let us know if it's OK or send us feedback. Thank you!
