### ISSUE TITLE
Persist previous query history between launches

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#333]
I love the next/previous buttons for navigating query history; would be great if that could be preserved across quitting and relaunching the application.

**Comment by tothradoslav** [comment]
That's actually a good idea, will check how complicated it would be... :)

**Comment by tothradoslav** [comment]
I just checked the implementation of this feature and there's a little catch... This history is currently attached to the tab itself, so it is preserved across quitting and relaunching the app, however, it's lost when the tab is closed and / or not shared with a newly opened tab.

Essentially, it works just like in a real browser: each tab has it's own history and the browser has its global history, too.

Possible solution: When a new tab is opened (with blank history), append the collection filter history to it. This would, however, work a bit differently. When you open such a new tab, you don't know what will happen when you click the back button.

We will think about this futher...

**Comment by tothradoslav** [comment]
After giving this a bit more thought, we have to drop this idea because of the above explanation. The query history and back / forward buttons are stored between launches and even after closing and reopening the tab (SHIFT + CMD + T). The history cannot be taken from another tab (we wouldn't even know from which one).

**Comment by tothradoslav** [comment]
You can still use the query history (click on Query dropdown) https://www.loom.com/i/dd100586ede24f11aea42324c5f6d0d9
