### ISSUE TITLE
Compare and Sync errors

### ISSUE THREAD

**Issue by ycelik1** [mingo-app/mingo#334]
I am using version v1.6.5 in 14 day trial mode to compare two databases. When I select collections and press the "Compare selected collections" button "An error occurred" text appears next to each collection. 

Is it because Compare and Sync not supported in trial mode?

**Comment by tothradoslav** [comment]
All features are supported in trial so there will be a different problem. I will need more info about when the problem happens. Your OS, mongo version you are connecting if possible.

**Comment by ycelik1** [comment]
OS is Windows 10 v21H2. I compare two databases one on my localhost and the other running on a Linux server both MongoDb v5.0.5.

![Untitled](https://user-images.githubusercontent.com/5623846/151609042-c91e3af7-9b98-4407-826e-5c66a01c3e6c.jpg)
.

**Comment by tothradoslav** [comment]
Thank you. We will investigate. I might send you further questions.

**Comment by tothradoslav** [comment]
OK, we found the bug and corrected. Thank you for letting us know. The fix will be available in next release, probably in a few days.

**Comment by ycelik1** [comment]
Thank you. I will download and try new release then. 

As as far as I can see, in the current version which doesn't work for me, the Compare and Sync feature doesn't include views and indexes, right? I mean you can see collections available on both sides, copy/merge them from one side to the other but you can't see if the indexes and views defined over those collections are different or missing on one side.

For SQL databases Visual Sudio's Schema Compare feature helps a lot when deploying index, view and stored procedure changes from development to a production database. Something similar for MongoDb would be great.

**Comment by tothradoslav** [comment]
Mingo's next release candidate is out, please check it out: 

https://github.com/mingo-app/mingo/releases/tag/v1.7.0-rc1

Regarding Compare / Sync, indexes are included. But views are not, and I'll put this in our roadmap, good tip!

Please let me know if the RC worked for you.

**Comment by tothradoslav** [comment]
Available in the latest release: https://github.com/mingo-app/mingo/releases/tag/v1.7.1
