### ISSUE TITLE
Downloading update does not do anything

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#336]
I was notified of the new 1.7.0 update and I clicked Download but nothing happened. Even after waiting a few minutes

Windows 10, Mingo 1.6.5

**Comment by tothradoslav** [comment]
Thank you. I will test it. Did you manage to install it manually?

**Comment by Christilut** [comment]
Still the case in 1.7.2

**Comment by Christilut** [comment]
I still have this problem. Every update so far it's the same. Download does nothing and I always download updates from the Github releases page
