### ISSUE TITLE
long (64bit) number show as unsigned or something

### ISSUE THREAD

**Issue by pp0236** [mingo-app/mingo#337]
![image](https://user-images.githubusercontent.com/54238880/153806287-67e0ab28-87eb-4ddb-bcd3-ad6d5acf97f0.png)
it should be 708198820995006475 not {"low": 1405222923, "high": 164890387, "unsigned": false}

timestamp is also long number but lower

on mongo shell it work fine
```
MongoDB Enterprise atlas-xxxxxx-shard-0:PRIMARY> db.userData.find()
{....., "user_id" : NumberLong("708198820995006475"), "timestamp" : NumberLong("1644816143740")}
```

**Comment by tothradoslav** [comment]
thanks, will correct it!

**Comment by tothradoslav** [comment]
Hi,

we have just released an RC with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please, let us know if it's OK or send us feedback. Thank you!

**Comment by pp0236** [comment]
fixed thanks.
![N6tWE56jXY](https://user-images.githubusercontent.com/54238880/159167572-83ed0f06-0880-45d0-8727-6ca1b0718471.png)
‎

‎
no issue metion :cry‎: ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎jk idc much :)
![image](https://user-images.githubusercontent.com/54238880/159167582-0899be94-6e24-4479-8a6b-7416a9b0cd22.png)
