### ISSUE TITLE
Restore option is not available in Dump & Restore tool

### ISSUE THREAD

**Issue by 21sonisingh** [mingo-app/mingo#338]
I have taken the dump, now when trying to restore that option is not available
![image](https://user-images.githubusercontent.com/100336023/155465435-c249356f-643c-4ddc-9715-d8e020dcc155.png)

**Comment by tothradoslav** [comment]
Yes, we are implementing this in the upcoming version, thanks!

**Comment by tothradoslav** [comment]
Hi,

we have just released an RC with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please, let us know if it's OK or send us feedback. Thank you!

**Comment by tothradoslav** [comment]
We have just released a new version with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2

Please, let us know if it's OK or send us feedback. Thank you!
