### ISSUE TITLE
I think recent update may have broken "find document by _id" feature

### ISSUE THREAD

**Issue by colbygreen32** [mingo-app/mingo#340]
I used to be able to easily click on the foreign object _id in a document and it would almost immediately bring me over to the outside collection that the _id belongs to. This was one of my favorite features about Mingo, but for some reason I can no longer get it to work. Everytime I click on the foreign object _id I just see the "searching" notification load for roughly 20 seconds and then nothing happens. Was planning on doing a Mingo demo with my team this Tuesday to try to convince them to switch from Mongo Compass over to Mingo and was really hoping to show them this feature :(
<img width="1225" alt="Screen Shot 2022-02-27 at 4 57 18 PM" src="https://user-images.githubusercontent.com/46765063/155901796-646d1dee-2b8e-44c2-bec7-b5fe1d1b0ac0.png">

**Comment by tothradoslav** [comment]
Sorry for this, you are right, it's broken in case the objectId is an actual objectID (not string). Ready for next release which will be out next week.

**Comment by tothradoslav** [comment]
Hi,

we have just released an RC with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please, let us know if it's OK or send us feedback. Thank you!

**Comment by tothradoslav** [comment]
We have just released a new version with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2

Please, let us know if it's OK or send us feedback. Thank you!
