### ISSUE TITLE
Do Mingo give missing index information like in sql server we get?

### ISSUE THREAD

**Issue by 21sonisingh** [mingo-app/mingo#341]
It will be grt if that option avilable...

**Comment by tothradoslav** [comment]
This would be a great feature, how exactly do you imagine this implemented?

For now, you can use the "Explain" link in the bottom status bar which shows after the query has been executed. 

But this could be implemented in a better way. We don't want to run "Explain" on every query for performance reasons, but we could add a link like "Were any indexes used?" which would execute the Explain command and show whether and / or which indexes have been used.

**Comment by tothradoslav** [comment]
Hi,

we have just released an RC with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please, let us know if it's OK or send us feedback. Thank you!

**Comment by 21sonisingh** [comment]
Thanks will check

**Comment by tothradoslav** [comment]
We have just released a new version with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2

Please, let us know if it's OK or send us feedback. Thank you!
