### ISSUE TITLE
Open admin database

### ISSUE THREAD

**Issue by dorandeluz** [mingo-app/mingo#343]
Hi,

I need to access collections in the admin database of my mongo server (no auth). I can't seem to find a way to access/open the admin DB in Mingo and found nothing in the docs either. Is that impossible?

Thanks

**Comment by tothradoslav** [comment]
Yes, we have hidden these, but will show them in the upcoming version. Thanks for letting us know!

**Comment by dorandeluz** [comment]
Great, thanks! Any idea, even approximate, when that next version will be published?

**Comment by tothradoslav** [comment]
Sorry, a bit late... We have just released a new version with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2

Please, let us know if it's OK or send us feedback. Thank you!
