### ISSUE TITLE
Is there a way to get distinct values without using aggregator?

### ISSUE THREAD

**Issue by jaredatdannyronsrescue** [mingo-app/mingo#344]
I'm really loving Mingo so far, but one reason I didn't use Compass over Robo is the lack of flexibility.  For example: I want to do something like: db.collection.distinct("status",{}).  But I don't see a way to do this.  Am I missing something? 

I expected to click on the word "Query" where there's a dropdown and see options for distinct, updateOne, insertOne, insertMany, updateMany, etc.  I know there are other ways to insert/update, but what about distinct?

I just noticed that limit() is also not available.

**Comment by tothradoslav** [comment]
Yes, there are several ways to do this:

1. Using NodeShell (last option at the top when viewing a collection), you can type any command, such as the one you mentioned.
2. Once you "pin" the field you want to get the distinct data from (add it as a column), in your case "status", you can just click the column name, select "Data -> Copy distinct values". I created a video for you to see exactly: 

https://www.loom.com/share/488c701802ec466893e832e954126b98

Hope this helps. If you have further questions, let me know.
