### ISSUE TITLE
Stuck on "Press again to close entire window"

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#345]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/3471363/157336456-7b6da459-523e-435f-a4ac-a38a64cf3e9a.png">

After starting Mingo (fully shut down), I see the above.

I think this is what I did:
1. Press CMD+W
2. Don't press it a second time
3. Instead press CMD+Q to quit Mingo
4. Start up Mingo 5 minutes later
5. Popup as in screenshot is stuck

**Comment by tothradoslav** [comment]
Thanks for the detailed info I could easily reproduce and correct the bug. Thank you :)

**Comment by tothradoslav** [comment]
We have just released a new version with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2

Please, let us know if it's OK or send us feedback. Thank you!
