### ISSUE TITLE
Widgets : Bar graph shows "Select X axis data type.."

### ISSUE THREAD

**Issue by Lord-V15** [mingo-app/mingo#348]
### Widget creation issue
_Your version: `1.7.1`_
Every time I try to create a bar/line chart, I face the same issue. 
**Could anyone explain what the message means ?**
<br>
<img width="666" alt="Screenshot 2022-03-14 at 3 36 01 AM" src="https://user-images.githubusercontent.com/46837998/158081217-85f37ebf-d12e-43a3-98d5-66708cb2a31c.png">

**Comment by tothradoslav** [comment]
Hi,

we have just released an RC with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please, let us know if it's OK or send us feedback. Thank you!

**Comment by Lord-V15** [comment]
Thanks I'll test it out 🍻

**Comment by Lord-V15** [comment]
It's fixed in the 1.7.2-rc1 thanks @tothradoslav !
