### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by javigines** [mingo-app/mingo#350]
I am trying to export from one database some documents and import them on another. I have tried in JSON format by file and clipboard and every time on import on the new database this error appears. 
![image](https://user-images.githubusercontent.com/15628852/158421451-bd3db467-2b5c-481b-9cb3-539ede22ee2b.png)
I have tried with only one document and it happens no matter what.

**Comment by tothradoslav** [comment]
Thank you. What version of Mingo are you using?

**Comment by javigines** [comment]
I have tried in the 1.7.1 and in the 1.7.2-rc

**Comment by tothradoslav** [comment]
Great, I found the bug, thanks a lot! It will be available in next release candidate.

**Comment by tothradoslav** [comment]
We have just released a new version with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2

Please, let us know if it's OK or send us feedback. Thank you!
