### ISSUE TITLE
Add new database failed on save

### ISSUE THREAD

**Issue by javigines** [mingo-app/mingo#351]
Sorry for bothering again, but I had found another bug.

On saving an additional database, the save process executes correctly, but nothing happens. When I test the connection everything seems okay. If I exit the connection manager screen when I reenter, the new connection is created but no field seems to be saved. Here you can see it on a video. I don't open the connection for privacy reasons, but as you can see on the video the test connection process returns everything is okay.

It's the third connection I don't know if it must be because of any of that.

https://user-images.githubusercontent.com/15628852/158427926-c68bf8e6-12e3-46ee-8068-856a7732d916.mp4

This is on Windows with the 1.7.1 and 1.7.2-rc

**Comment by javigines** [comment]
It seems that if I move up the connection to the first position on the project it is saved correctly

**Comment by tothradoslav** [comment]
Thank you for the detailed report. I'm trying to reproduce the error and I found a specific situation: 

- if you leave the "Environment name" empty, there will be an error shown in the bottom right of the screen (which could be overlooked)
- if you then "Save changes", it will not continue
- when you leave the form (using the Back button) and return, I can see something similar as in your video

Could you please confirm this? I'm working on a solution for this issue. I'd like to know if this was the problem or there's something else, too.

**Comment by javigines** [comment]
No, this is not the case. I have set the name testing on the connection environment name.
Here you can see the settings/fields I am using.
![image](https://user-images.githubusercontent.com/15628852/158466389-157a2cbc-0608-4ac4-975a-f01e4ab6485c.png)

**Comment by tothradoslav** [comment]
Great, thanks, will look into it!

**Comment by tothradoslav** [comment]
Can you please let me know if this still happens in the latest v1.8.1?

**Comment by javigines** [comment]
Yes, in Windows and Mac with the latest version.

**Comment by tothradoslav** [comment]
I'm cleaning up Mingo issues and just noticed this issue has not been resolved. We have, however, made many changes in projects / connections management since. Could you please check if this is still a problem?

**Comment by tothradoslav** [comment]
I was actually able to reproduce the error now and solved the issue. Will be out in next release.

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
