### ISSUE TITLE
Invalid type alias when navigating from Schema tab

### ISSUE THREAD

**Issue by IonBazan** [mingo-app/mingo#352]
When exploring the collection schema in Schema tab, if field is `ObjectId`, clicking "view these docs":
![image](https://user-images.githubusercontent.com/1985514/158943423-a76aae2b-5e0c-4abf-9032-035b779e1172.png)

produces an invalid query:
```
{"mapPoint._id":{"$type":"objectid"}}
```

instead of:
```
{"mapPoint._id":{"$type":"objectId"}}
```

which trows error:
> MongoServerError: Unknown type name alias: objectid 

See: https://docs.mongodb.com/manual/reference/operator/query/type/#available-types

**Comment by tothradoslav** [comment]
Thank you! We went through all the types and corrected them. Available in next release.

**Comment by IonBazan** [comment]
Thank you @tothradoslav! One more thing - when that happens - the "documents" tabs becomes completely unusable (loading overlay) and if I navigate back to "schema", it shows it below the result set after I scroll down 🤔 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/1985514/159421896-10063862-c77a-4cd0-8594-84f605568ce1.png">

I believe this will be fixed by fixing the type aliases, but I am afraid it could happen in different situation too, when a server error occurs.

**Comment by tothradoslav** [comment]
Hi, please check out the new RC, this should be OK now:

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please let me know if it worked.
