### ISSUE TITLE
Cmd + Click to open in new window

### ISSUE THREAD

**Issue by IonBazan** [mingo-app/mingo#354]
Hello, Mingo team! Thank you very much for Mingo.io - it makes dealing with MongoDB so much easier! ❤️ 

I think it would be nice if <kbd>Cmd</kbd>+ click (or <kbd>Shift</kbd> + click) should open a connection in a new window (same as clicking the icon on the right from the connection name, similarly as web browsers do.

![image](https://user-images.githubusercontent.com/1985514/159422874-c6868914-8201-47d9-8331-6f6cf274c0d0.png)

**Comment by tothradoslav** [comment]
Thank you!
This can already be achieved by clicking at the button to right of each option (seen in your screenshot). However, we added the SHIFT+click option as you requested, too. We used shift of macs, too, because that's the default browser behaviour (CMD opens in new tab, not window).

**Comment by tothradoslav** [comment]
Hi, please check out the new RC, this should be OK now:

https://github.com/mingo-app/mingo/releases/tag/v1.7.2-rc1

Please let me know if it worked.

**Comment by IonBazan** [comment]
Unfortunately, this doesn't seem to work for me on Mac. The connection still opens in same window if I hold Shift.

**Comment by tothradoslav** [comment]
Oops, it worked on projects, but not on connections, sorry. Corrected.

**Comment by tothradoslav** [comment]
We have just released a new version with this issue solved.

https://github.com/mingo-app/mingo/releases/tag/v1.7.2

Please, let us know if it's OK or send us feedback. Thank you!
