### ISSUE TITLE
Capability to disable Retryable writes

### ISSUE THREAD

**Issue by javigines** [mingo-app/mingo#357]
Hello again,

Would be nice to have the capability to disable retryable writes. Some databases like DocumentaDB based on MongoDB from AWS don`t support them and make it impossible to edit an entire document with Mingo.

**Comment by tothradoslav** [comment]
Hi :) I checked the documentation and it says you can disable it with a query parameter in the mongodb URI itself like this:

mongodb://localhost/?retryWrites=false

https://www.mongodb.com/docs/v4.0/core/retryable-writes/

Can you please try this and let me know if it worked for you?

**Comment by javigines** [comment]
Solved with the retryWrites=false, I thought it was something done behind the scenes by Mingo. Sorry for the inconvenience.

**Comment by tothradoslav** [comment]
No problem @javigines , I'm actually glad you asked. This could have been an issue on our side. BTW, since you are using DocumentDB on Mingo, I'd like to ask you whether it works OK, because we haven't actually tested it yet. We would like to add full support of DocumentDB, too.

**Comment by javigines** [comment]
Ok, no problem, we are not using Mingo exclusively as the DB management tool but as I use it and found any more problem or doubt, I can reported here as an issue.
