### ISSUE TITLE
Icon for macOS

### ISSUE THREAD

**Issue by zamu87** [mingo-app/mingo#358]
Hi, the UI of your application is really fantastic, I want only to suggest you to update the icon according to Apple Guidelines https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

<img width="304" alt="Screenshot 2022-03-24 at 12 05 18" src="https://user-images.githubusercontent.com/22892878/159969362-bc3e9ef5-5060-4ba4-87ad-85d86f2fe6c1.png">

**Comment by tothradoslav** [comment]
Thank you, we will do so! :) Will reply here when done.

**Comment by zamu87** [comment]
[mingo_icns.zip](https://github.com/mingo-app/mingo/files/8670302/mingo_icns.zip)

Hi @tothradoslav, I've created a macOS icon using your default color schema.

**Comment by tothradoslav** [comment]
Wow, thank you, our desinger was so busy, I even forgot about this. Will use it!

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
