### ISSUE TITLE
only 100 collections displayed in a database

### ISSUE THREAD

**Issue by yuercl** [mingo-app/mingo#366]
Mingo cannot display more than 100 collections in a database.

**Comment by tothradoslav** [comment]
Thank you! I have just tested it and tried to add 200 collections to a database and it showed them correctly. Could you send me more info on where this happens? In the sidebar? Or elsewhere?

**Comment by yuercl** [comment]
It's a misunderstanding. My local database has 100 collections exactly, and server database has more 200+ collections.
It's not  bug. Awfully sorry.

**Comment by tothradoslav** [comment]
I'm actually glad you wrote, issues keep Mingo improving :)
