### ISSUE TITLE
Copy and Paste MongoDB Documents

### ISSUE THREAD

**Issue by laakal** [mingo-app/mingo#368]
How to copy MongoDB multiple documents and paste them across databases and collections? Like  [Studio 3T](https://studio3t.com/knowledge-base/articles/copy-paste-mongodb-documents/)

**Comment by tothradoslav** [comment]
Thank you! 

To copy entire collections, right-click on the collection and choose the "Copy collection to..." which will open and pre-fill the Dump&Restore tool.

We have also added a similar functionality to copy / paste individual documents as in Studio 3T. This will be available in next release. Thanks for the tip!

**Comment by tothradoslav** [comment]
Hi,

we have just released a new version 1.8.0 with this issue solved. 

https://github.com/mingo-app/mingo/releases/tag/v1.8.0

Please, let us know if it's OK or send us feedback. Thank you!

**Comment by laakal** [comment]
Thank you. Can you add the capabilities mentioned below?
- Multiple select the source collection you want to copy and right click in the collections list
- Select your target MongoDB database where you want to copy your source collections to.
- Right click on your target and select paste collections.
