### ISSUE TITLE
Suggestion: Delete field options

### ISSUE THREAD

**Issue by VladimirMikulic** [mingo-app/mingo#369]
Hi!

During testing/migrations, I frequently deal with deleting keys from more documents.
It would be nice if I didn't have to open NodeShell, copy field and specify `$unset`.

![Frame 1](https://user-images.githubusercontent.com/35997844/162550740-a829e1fc-25ae-4e3d-bfc0-f5bc3b04ba43.png)

For example, if we could replicate `Rename field` submenu, but for delete action as well.
So it would be (Delete field submenu):
- This document only
- All documents in collection
 
It's not a deal breaker though, just a quality of life improvement that I would find helpful and is consistent with rest of the actions.

Thank you again for amazing product!

**Comment by tothradoslav** [comment]
Thank you for the tip, it's been implemented and will be available in next release.

**Comment by VladimirMikulic** [comment]
Just downloaded v1.8.0! Works flawlessly. Thank you so much @tothradoslav!
