### ISSUE TITLE
add feature quick search collection name

### ISSUE THREAD

**Issue by yuercl** [mingo-app/mingo#371]
want to add feature: quick search collection name. just like mongodb compass:

![image](https://user-images.githubusercontent.com/2859382/163945646-4e07a08f-4f04-4717-b5ae-723b17959c12.png)

**Comment by yuercl** [comment]
use 「 Command + F 」

**Comment by tothradoslav** [comment]
Or you could use Command + T (open new tab) and then you are focused into a search field by default, just start typing and select the collection / view with arrow keys.
