### ISSUE TITLE
Suggestion: Autocomplete _id syntax

### ISSUE THREAD

**Issue by VladimirMikulic** [mingo-app/mingo#372]
When searching for document with _id selector, it would be nice if autocomplete could also write `ObjectId("<place my cursor here>")` in here as well. This would be similar to how `$exists` offers to autocomplete `$exists: false/true`. Minor features like these really **make a big difference** in workflow (surprisingly, none of the other tools I used for years have this!) and are hopefully not hard for you to implement :)

Thanks again for all the amazing work!

**Comment by tothradoslav** [comment]
Sure, thanks, implemented. Ready for next release.

**Comment by Jeannot-Muller** [comment]
I second that small changes like this are making a BIG difference, and I second that the "others" don't seem to see this a relevant, but it actually is. Thank you!

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
