### ISSUE TITLE
X axis field value missing in Chart Widget Editor

### ISSUE THREAD

**Issue by cricku** [mingo-app/mingo#373]
When trying to edit an existing doughnut chart the value for `X axis field` is missing. I experience this after updating the client to version `1.8.0` (macOS).

**Comment by tothradoslav** [comment]
Thanks! Corrected, will be in next release.

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
