### ISSUE TITLE
No horizontal scroll bar

### ISSUE THREAD

**Issue by SinBirb** [mingo-app/mingo#374]
Hey, unfortunately I don't have a horizontal scroll bar in the Documents view so that I don't see all columns.

I'm using Gnome 42 with Wayland.

Is there any more info you need?

**Comment by tothradoslav** [comment]
Thanks, could you send a screenshot or more details? Can you scroll horizontally? Or you can't even scroll at all? Mingo does not show all fields as columns, but picks a few of them at first and you can add / remove them.

**Comment by SinBirb** [comment]
Hey, here is a screenshot of the section. I can scroll vertically. There are more columns to the right. I can "cheat" to see them by selecting some text and dragging the mouse over the window's border to the right. The view then scrolls to the right. Just the scroll bar is missing.

![image](https://user-images.githubusercontent.com/5778042/165047398-29b95275-0dcc-420c-af86-2e4a7e965ae3.png)

**Comment by tothradoslav** [comment]
Great, thanks for this. It's done and ready for the next release.

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!

**Comment by SinBirb** [comment]
Thank you for fixing it so quickly.

Just a suggestion: The two scrollbars aren't moving the same container, therefore it's not possible to scroll horizontally and vertically at the same time. Instead, you have to scroll vertically, wait 2 seconds and then scroll horizontally. It's really not a big deal, just a small thing to improve your already great product.

**Comment by tothradoslav** [comment]
V1.9.0-rc1 is available. Please try it out and please let us know whether your issue has been resolved. Thank you! https://github.com/mingo-app/mingo/releases/tag/v1.9.0-rc1

**Comment by SinBirb** [comment]
There is still this delay when using the touchpad and the scroll bars are still in the same position, I don't think anything changed.

**Comment by lynchem** [comment]
Yeah, we see this as well. If your results have 50 docs and your current view can only display 25 then you have to first scroll vertically before you can see the horizontal scroll bar and use it. I think this is what the OP is also talking about. It's not a big deal but I'm always missing it.

**Comment by tothradoslav** [comment]
We can't currently fix this due the layout, unfortunately...
