### ISSUE TITLE
Proper wayland support

### ISSUE THREAD

**Issue by SinBirb** [mingo-app/mingo#375]
I use Gnome 42 with Wayland especially because I have fractional scaling active on my external monitor, which enlarges applications, similar to the Windows functionality. Apps that use XWayland look blurry, and so does Mingo.

I have managed to launch Mingo using Wayland instead with the following command: `mingo --enable-features=UseOzonePlatform --ozone-platform=wayland`.

Now the scaling works, it's not blurry, but the window decoration is missing, ie. the title bar to close, resize and move the window. There are also a few errors on the console. VSCode also has [problems on Wayland](https://github.com/microsoft/vscode/issues/109176) and they solved it by updating to [electron 17.3.1](https://github.com/electron/electron/releases/tag/v17.3.1).

mingo's logs say it's currently using electron 15.3.6. Do you think it's feasible to upgrade to at least 17.3.1 soon?

**Comment by tothradoslav** [comment]
Sure, updating to new electron should not be an issue and will be available in the next release. Thanks!

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!

**Comment by SinBirb** [comment]
Thank you, it works without parameters and there are window decorators now :)
