### ISSUE TITLE
Date in the past in green

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#376]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/3471363/164948534-6889e70d-83e5-4ced-b7fd-7e06f5e3168b.png">

Is that intended? It used to be red right?

**Comment by tothradoslav** [comment]
I think it used to be different based on whether it's positive or negative, but we simplified it to minimize the use of colors. I'm thinking of changing this to the same color as the date itself.

<img width="253" alt="Screen Shot 2022-04-24 at 21 25 28" src="https://user-images.githubusercontent.com/3465808/164993148-d95ef733-ffee-4c12-bd8e-986d1dec5c86.png">

What do you think?

**Comment by Christilut** [comment]
I personally really like the green/red thing to indicate future or past. That's good use of colors in my opinion.

When I read "4 weeks ago" in green, it seems off to me.

**Comment by tothradoslav** [comment]
OK, I guess you are right :)

**Comment by Christilut** [comment]
I think if you feel that it is important to reduce the colors, then I would make the text without any specific color.
But personally, I really enjoy the positive and negative color.

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!

**Comment by Christilut** [comment]
I upgraded to the latest version today but immediately noticed this (was using 1.9.0 before this because of that other bug). Now all dates are in orange? Is that intentional? I think the green/red color coding is really useful opposed to having to comprehend an ISO date.

**Comment by tothradoslav** [comment]
I have changed the relative date ("2 years ago") to grey and not dependent on future / past.

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
