### ISSUE TITLE
Problem restoring a backup from file

### ISSUE THREAD

**Issue by tothradoslav** [mingo-app/mingo#377]
`struggling with restoring a backup

don't know what to do with file "/Users/jmu/Downloads/backup/nuage/domains.bson

otherwise all is fine.
I dumped the files successfully into a directory. But restoring doesn't seem to work though. But probably related to my knowledge of mongodb. So please see it as input for pot. new users: make it as easy as restoring a db on postgres 🙂
`

@jeannot discord

**Comment by Jeannot-Muller** [comment]
when restoring manually it works:

`/opt/homebrew/bin/mongorestore --host=127.0.0.1 --port=27017 --username=<MYUSER> --authenticationDatabase=admin --gzip --archive=/Users/jmu/Downloads/dump/nuage-archive.gz`

Seems to be related to the --authenticationDatabase if that helps.

**Comment by Jeannot-Muller** [comment]
My bad, my mistake. It turned out that the remote server was still running on mongodb 4 but locally I had mongodb 5, now all is working. I have no idea if you can build in such a check in future?

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
