### ISSUE TITLE
Mingo Installation Directory

### ISSUE THREAD

**Issue by amitkumarhq** [mingo-app/mingo#378]
Please add an option to install to custom installation directory rather than one click install, as the C:\ drive can fill up drastically with a lot of programs

**Comment by tothradoslav** [comment]
Thank you! I have not used Windows for a while now, but isn't there an option for you to move the app to any directory you prefer?

**Comment by AmitKumarHQ** [comment]
I tried creating a junction for the files but it didn't seem to work
