### ISSUE TITLE
Changing fontsize in the query and nodeJS editor or some zooming would be great.

### ISSUE THREAD

**Issue by Jeannot-Muller** [mingo-app/mingo#379]

**Comment by tothradoslav** [comment]
Are you interested in zooming in (larger font) or zooming out? I'm implementing this now.

As a side note: did you know you can zoom mingo "in / out"  in preferences or using CMD+0 key shortcut?

**Comment by tothradoslav** [comment]
There are actually two ways to implement your requirement:

1. by only changing the font size in the actual editor (query, nodeJS) and leaving the rest of the UI as is...
2. Improving upon the current zooming functionality (compact mode) and allowing for more options (very small, small, normal, larger). Which would zoom in the entire UI font size, globally.

Which one do you think would be better?

**Comment by Jeannot-Muller** [comment]
hmm,1 would be sufficient for me. But I personally think that 2 might be a requirement for some users too. I learned via my customers how many people actually are facing (unfortunately) sight issues.

**Comment by Jeannot-Muller** [comment]
I am aware of the currently implemented zoom options. And though they are already very helpful they have have their limitations, mainly for zooming in. Thinking of the kind of like "zooming into a webpage", for instance to quickly verify if a letter i an l (lowcase l) or an I (uppercase i ). This kind of stuff. a magnifying glass function might be an option too? I know that all that stuff is a bit difficult to implement: but I think for the "extremes" very small and larger the layout doesn't necessarily have to be pixel accurate (the extremes more being for a quick help).

**Comment by tothradoslav** [comment]
We implemented the option to zoom in / out at much larger scale than it was available. CMD+ and CMD- work now for this.

**Comment by Jeannot-Muller** [comment]
Great, thank you.

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
