### ISSUE TITLE
Suggestion: Provide keyboard shortcut for common functionality

### ISSUE THREAD

**Issue by kalaivanan-muthusamy** [mingo-app/mingo#382]
First, thanks for the wonderful modern MongoDB GUI. Using since couple of month and it is really excellent and user friendly

Suggestion:
Currently when pressing `Ctrl+A`, all the documents gets selected which is awesome. It will be great if you can also provide the keyboard shortcut for the important to the actions displayed (most importantly `Delete`, `Copy as JSON`, `Export` and so on.) when one or more document is selected. 

You can also take this opportunity to review all the common features/functionalities throughout the application and implement the keyboard shortcuts as necessary. This will improve the user productivity efficiently

**Comment by tothradoslav** [comment]
Thanks for this, we'll definitely work on this. We even considered making it possible for a user to use Mingo in a "mouse-less" fashion, just using the keyboard, but this is obviously very difficult.

Currently, we have different types of keyboard shortcuts: 
1. CTRL (CMD) + something
2. just regular keyboard (hover over a document  and press space selects it, for example)

We'd need to come up with a logical system for all keyboard shortcuts. We tried to make them very intuitive, to  mimic the behaviour of other apps, mainly browsers.

In your case, maybe a solution could be:
1. press CTRL (CMD) + A (or select any documents)
2. then press a letter as a shortcut (D to delete, E to export, F to find, A to analyze, etc). Some of them actually already have a shortcut, just not mentioned properly in docs. For example press CMD+C will copy the selected docs into a "virtual clipboard" and you can paste (CMD+V) them into other or even the same collection (more options will pop up).

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!

**Comment by kalaivanan-muthusamy** [comment]
Wonderful!!!. It is working as expected now. Thanks for the quick resolution.
