### ISSUE TITLE
Incorrect table headings

### ISSUE THREAD

**Issue by emehmet** [mingo-app/mingo#384]
Hi,
Table headers are not replaced when a collection is cleared or a field is completely deleted. Old titles are shown. If the tree is expanded, the correct titles appear.

Windwows 11
Mingo 1.8.0

**Comment by emehmet** [comment]
Hi,
I can guess that you said yes. But it felt like a bug or a problem to me as an end user. 
You can manage this with warnings or automatic control for collectioins whose total data count is below a certain counts.

**Comment by Jeannot-Muller** [comment]
Or it could be a preference. Either let the user do it manually, or offer to reload automatically after a deletion.

**Comment by tothradoslav** [comment]
We decided not to solve this so that Mingo would recognize the column is not existing any more. We bumped into several other related issues with this. Users can manually add / remove or reorganize columns. We even have a way to add default columns and resize widths based on current values.
