### ISSUE TITLE
Allow custom connection timeouts

### ISSUE THREAD

**Issue by mrjoesm** [mingo-app/mingo#385]
It would be useful to be able to set a custom timeout longer than 60 seconds

![image](https://user-images.githubusercontent.com/19344769/166900758-d8bc7a1b-5c20-4c98-ab55-827f12f6bf0f.png)

![image](https://user-images.githubusercontent.com/19344769/166900156-e14de08d-5e0b-42fb-9174-43fd0469d977.png)

**Comment by tothradoslav** [comment]
We added 2 more options: 5 minutes and 1 hour. We believe this should be sufficient in overwhelming majority of usecase. If you feel this is not sufficient, please let us know. Thanks!

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
