### ISSUE TITLE
BUG: Aggragator: when stage is deleted the documentation tooltip is not updated

### ISSUE THREAD

**Issue by jomel** [mingo-app/mingo#387]
When an aggregate stage is deleted the tooltip for the documentation link is not updated (the link target IS).
![mingo1](https://user-images.githubusercontent.com/3426561/167130634-d4f71eb8-aefe-4e14-b145-ab33f227bdd6.png)
![mingo2](https://user-images.githubusercontent.com/3426561/167130630-6ab18931-561e-41af-8b15-3606788c4b6d.png)

**Comment by tothradoslav** [comment]
thanks, corrected, in next release. Keep the issue open please.

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
