### ISSUE TITLE
Feature Request: rename tabs

### ISSUE THREAD

**Issue by jomel** [mingo-app/mingo#388]
I have a few different tabs of the same collection (eg with different aggregate queries), but all tabs just have the collection name on them.
It would be cool to be able to right-click and give each tab a descriptive name.

![image](https://user-images.githubusercontent.com/3426561/167133280-637bf3a9-f77b-4c49-b221-267ea7156aae.png)

**Comment by tothradoslav** [comment]
Thanks for the idea. Before implementing this, I'd like to play with the idea of naming the tabs automatically in some way. For example, show the query (at least part of it). This solution, however, is not perfect, I know...

Do you keep these tabs open for a long time? I'd like to know more about your use-case. Thanks!

**Comment by Jeannot-Muller** [comment]
Automatic sounds good, but I second the idea of being able to rename them too. I can think of the need to name a tab differently of what a query is reflecting. Something like "Almost Working", "test1", "different approach", etc.

**Comment by tothradoslav** [comment]
Ok, done :) You will be able to rename a tab as you wish.

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
