### ISSUE TITLE
Mingo is showing "Free Licence" even though I'm not on a free licence 

### ISSUE THREAD

**Issue by mrjoesm** [mingo-app/mingo#389]
![image](https://user-images.githubusercontent.com/19344769/167148348-3df1e2da-08d4-4297-8b0f-15c8f4ab2346.png)

![image](https://user-images.githubusercontent.com/19344769/167148383-8eb8dbb4-a684-46a2-95d9-c3d7718ebacd.png)

**Comment by Jeannot-Muller** [comment]
same here, but at least the functionality is there ;-)

**Comment by tothradoslav** [comment]
thanks, corrected for next release.

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
