### ISSUE TITLE
2 seats license policy

### ISSUE THREAD

**Issue by Jeannot-Muller** [mingo-app/mingo#390]
I think I am not the only one using 2 macs. In my case a macbook pro (basically used as a desktop / third screen) with 2 monitors. That's my main dev machine. For more relaxed time, customers visits I am using a macbook Air. Now though you can switch licenses as such that only one device is activated it is a bit "unusual" in 2022. 

I would appreciate if the license could work on 2 macs. As a dev I know that there is nothing like free cake. I would even be fine it his would come at a small fee.

**Comment by Jeannot-Muller** [comment]
Wow, that's very kind of you! Thank you!

**Comment by mrjoesm** [comment]
@tothradoslav it seems completely reasonable to me to sync settings/hostnames/etc without syncing passwords - just my 2 cents
