### ISSUE TITLE
Compact / Comfort View is a toggle function

### ISSUE THREAD

**Issue by Jeannot-Muller** [mingo-app/mingo#391]
Not a bug, but a detail:

If you click _command / plus_ or _command / minus_ you can switch currently between the 2 available views (compact or comfort). 

But it is not a oneway road, but actually a "toggle" functionality. Means: if you are already in comfort view and you click that button in the menu again (or the keyboard shortcut) the look will actually change to the compact view, although the buttons tells you differently. This is comfortable, but the reading on the button then doesn't fit ;-).

**Comment by tothradoslav** [comment]
Yep, we changed this now: #379

**Comment by Jeannot-Muller** [comment]
you guys amaze me every day. Thank you. Keep it up!

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
