### ISSUE TITLE
Compare & Synchronise - Peep sound when check is finished

### ISSUE THREAD

**Issue by Jeannot-Muller** [mingo-app/mingo#393]
It would be great if this sounds (or any sound) cloud be made a pref.

**Comment by tothradoslav** [comment]
Would you like to have more options to choose from or the ability to choose any sound from a file on the computer? I think, the second option would be an overkill :)

**Comment by Jeannot-Muller** [comment]
Just switching off is fine with me ;-). I mean one of things I like most with Mingo is that it is lean ;-) and it should keep being lean ;-)

**Comment by Jeannot-Muller** [comment]
Early morning writing, sorry. Didn't made sense to me either when reading it again. I only meant to be able to switch sounds off. Like the animations.

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
