### ISSUE TITLE
After run of a Sync is not updating all information on a view

### ISSUE THREAD

**Issue by Jeannot-Muller** [mingo-app/mingo#394]
After running a sync there is a "back" button. If you click that link the collections are not automatically analysed again and only some information are updated. This might lead to the following:

![ScreenShot 2022-05-11 at 07 32 34@2x](https://user-images.githubusercontent.com/7870873/167776301-baa77062-d0b4-410e-b927-ec2c30a28e3d.png)

which, unfortunately doesn't make sense.

**Comment by Jeannot-Muller** [comment]
in sync is correct (in this case, as situation AFTER the sync), but the 93 docs and 93 docs are coming from the analysis BEFORE the sync.

**Comment by tothradoslav** [comment]
Thank you, corrected!

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
