### ISSUE TITLE
Filter by field value

### ISSUE THREAD

**Issue by dlucazeau** [mingo-app/mingo#399]
Hello
I suggest that by right-clicking on the value of a column, you filter the list on this value. The filter would be updated accordingly.

Regards

**Comment by tothradoslav** [comment]
You can do this by right-click on a field in a document (opened). Like this

<img width="586" alt="Screen Shot 2022-05-11 at 21 16 52" src="https://user-images.githubusercontent.com/3465808/167928403-7813a625-7103-49d6-b48f-aa6546ad6eca.png">

Or did you mean here? (Click on closed document, you can copy any of the pinned column values)

<img width="552" alt="Screen Shot 2022-05-11 at 21 17 36" src="https://user-images.githubusercontent.com/3465808/167928523-d1d38d18-c652-4b45-9a4e-cbc10a8c844e.png">

**Comment by dlucazeau** [comment]
I had not found this, I had tried on a column but on the closed document.
👍

**Comment by tothradoslav** [comment]
This could, however, still be implemented, so that you can click on the doc itself (closed). will keep this open.

**Comment by dlucazeau** [comment]
Perfect 👍

**Comment by tothradoslav** [comment]
Hi, this issue has been resolved in the current release of Mingo v1.8.1. Please, have a look and let us know if it worked fine :)

https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Thank you for your contribution!
