### ISSUE TITLE
v1.8.1 installation issue on windows

### ISSUE THREAD

**Issue by mrjoesm** [mingo-app/mingo#416]
When trying to install v1.8.1 on Windows 11, I get a:
![v1 8 1 install issue](https://user-images.githubusercontent.com/19344769/170462202-2bd8c317-b13b-4f08-8e27-4f79ee89f886.png)

**Comment by tothradoslav** [comment]
Thanks! Is this a new installation or an update?

**Comment by mrjoesm** [comment]
Both

**Comment by tothradoslav** [comment]
Hi, I think the problem was with the architecture, it was built for AMR (Apple M1 CPU), please check out the new exe file here:
https://github.com/mingo-app/mingo/releases/tag/v1.8.1

Please let me know! Thanks again.

**Comment by mrjoesm** [comment]
Thanks, I can't check right now but will do soon

**Comment by mrjoesm** [comment]
Yep that works perfectly now, thanks
