### ISSUE TITLE
Providing deb Package

### ISSUE THREAD

**Issue by RokkuCode** [mingo-app/mingo#418]
Since 1.8.1 there is no debian package. Is it possible to get the debian package back?

**Comment by tothradoslav** [comment]
sure, will create it and upload tomorrow. thanks!

**Comment by tothradoslav** [comment]
debian package available: https://github.com/mingo-app/mingo/releases/tag/v1.8.1

**Comment by RokkuCode** [comment]
Thanks for providing the debian package but it is for arm. Or is the naming wrong? I need amd64 please.
