### ISSUE TITLE
Bad type for queries referencing a document with a numerical _id field

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#419]
I added a new relation for my DB.

When clicking this, to search for referencing documents:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/1028647/171402372-061b98c7-c8dc-49d3-a458-fb837623fba4.png">
the new tab has a bad query in it:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/1028647/171402580-5dd76c89-2e37-4e58-95bd-68c2aea90cb2.png">
because the _id is of NumberInt type, not String.

**Comment by tothradoslav** [comment]
Thank you, corrected and will be available in next release.

**Comment by tothradoslav** [comment]
V1.9.0-rc1 is available. Please try it out and please let us know whether your issue has been resolved. Thank you! https://github.com/mingo-app/mingo/releases/tag/v1.9.0-rc1

**Comment by pepkin88** [comment]
Thanks, now it's ok.
