### ISSUE TITLE
Previews of referenced documents are only shown, if the type is ObjectId

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#420]
For a few collections I have integers for _ids.
It's understandable, that they weren't detected as references, the same way ObjectIds were, so I added manually those relations. One of them is this:
<img width="798" alt="image" src="https://user-images.githubusercontent.com/1028647/171406197-86caa400-c747-4167-b249-eb13168557b5.png">

But unfortunately, they are not treated the same, as those ObjectId.
For example, for ObjectIds I got this:
<img width="679" alt="Zrzut ekranu 2022-06-1 o 14 30 46" src="https://user-images.githubusercontent.com/1028647/171405202-76aa9a3c-5c59-4e07-b386-ec3c8fc79604.png">
But for numbers I got only this:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/1028647/171405385-336dd804-c0fa-44ca-bfdd-182dadbd3f22.png">

And for ObjectId with no relation set, I got this (which is great):
<img width="740" alt="image" src="https://user-images.githubusercontent.com/1028647/171405818-f4d2ce01-0ca8-48ae-b334-f9d7a7bdda43.png">

I understand, that ObjectId is a type, which almost always is used as a document reference, but when I add a relation manually, I would expect it to be treated as any other reference :)

**Comment by tothradoslav** [comment]
V1.9.0-rc1 is available. Please try it out and please let us know whether your issue has been resolved. Thank you! https://github.com/mingo-app/mingo/releases/tag/v1.9.0-rc1

**Comment by pepkin88** [comment]
Thanks, works great!

**Comment by pepkin88** [comment]
Now, because the Previews are shown for integer _ids, some bugs have surfaced: https://github.com/mingo-app/mingo/issues/435
