### ISSUE TITLE
Text color of conditional formatted columns should be adjusted for better contrast 

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#421]
How it looks now:
<img width="78" alt="image" src="https://user-images.githubusercontent.com/1028647/171417689-6f02a731-fee9-46ec-beb4-ea6af2626b4b.png">
For the "canceled" and "rejected" labels I would expect a light (white?) text color.

**Comment by pepkin88** [comment]
You could check the colors ad hoc here: https://coolors.co/contrast-checker/
WCAG 2.0 recommends contrast of 4.5 to 1 or more: https://www.w3.org/TR/WCAG20/#visual-audio-contrast

**Comment by tothradoslav** [comment]
V1.9.0-rc1 is available. Please try it out and please let us know whether your issue has been resolved. Thank you! https://github.com/mingo-app/mingo/releases/tag/v1.9.0-rc1

**Comment by pepkin88** [comment]
Thanks. After resaving the customization settings, it works good.
