### ISSUE TITLE
Option to change the editor font

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#422]
The default monospace font in Electron apps seems to always be some variant of Courier (I'm on Mac btw), but I have better fonts on my machine. I'd be nice to be able to change it.

That's how it looks now:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/1028647/171424987-20441cf9-1003-43a1-9cf5-988528e696ff.png">

The same font is used in other places too, e.g. query field:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/1028647/171426020-e5aaf978-3b0e-4c6c-a47e-2999452e077e.png">

I don't know, I just don't like that font :) it has serifs, it's wide and short, and I don't find it to be that readable at that size

**Comment by tothradoslav** [comment]
Do you have any specific font in mind? I have tried sans-serif. It looks better but  it's not monospace.

**Comment by pepkin88** [comment]
I think it could be the same css rule as it is on StackOverflow, and they use this:
`ui-monospace,"Cascadia Mono","Segoe UI Mono","Liberation Mono",Menlo,Monaco,Consolas,monospace;`

So for macOS it evaluates to Menlo, and I think it looks good. Definitely good enough :)
<img width="359" alt="image" src="https://user-images.githubusercontent.com/1028647/172861361-8e7ee60e-7ecf-4c49-a617-71493e19f279.png">

**Comment by Jeannot-Muller** [comment]
+1 for Menlo

**Comment by tothradoslav** [comment]
V1.9.0-rc1 is available. Please try it out and please let us know whether your issue has been resolved. Thank you! https://github.com/mingo-app/mingo/releases/tag/v1.9.0-rc1

**Comment by pepkin88** [comment]
Thanks, looks good!
In the meantime, I think that also solved another issue I stumbled upon. Namely, text from other scripts (like Cyrillic) used a fallback font, which messed up the position of the cursor. But now it also looks good. 👍
