### ISSUE TITLE
Insert document add _id automatically - _id auto detection type bug

### ISSUE THREAD

**Issue by consciouscoder** [mingo-app/mingo#424]
With the new version 1.8.1 when I insert a new document and it asks "Let Mingo add _id automatically?" and I choose yes. It is adding an _id that is a string while the entire collection has an ObjectId for _id. The dialogue box says it'll detect the _id type (string or ObjectId), but it is detecting the wrong type. The previous version worked for insert with correct _id type.

**Comment by tothradoslav** [comment]
Mingo analyzes the type of _ids the first time it connects to a database and reads its content. Once it has an _id type, this process is skipped. 

Do have the same type of _id in all collections? There's nothing special that I can think of that we would have changed regarding this in the new version. I'd like to find the cause of the problem, though.

**Comment by consciouscoder** [comment]
Shouldn't it only analyze the _id in the specific collection I'm inserting into? The collection is an ObjectId and 95% of the collections in the database are ObjectId as well ... yet, it's still defaulting to string.

**Comment by tothradoslav** [comment]
So far, Mingo expected the type of _ids to be the same throughout each collection in a database. I changed this now and the idType is analyzed for each colleciton separately. It should work find in the next release. Also, if the id type is a number, the newly generated one will be an autoincrement number.

**Comment by tothradoslav** [comment]
V1.9.0-rc1 is available. Please try it out and please let us know whether your issue has been resolved. Thank you! https://github.com/mingo-app/mingo/releases/tag/v1.9.0-rc1
