### ISSUE TITLE
The name of the connection is not immediately taken into account

### ISSUE THREAD

**Issue by dlucazeau** [mingo-app/mingo#426]
When a connection is created, its name is not taken into account during the first connection test.

![image](https://user-images.githubusercontent.com/4538922/172803355-848d337f-de39-43ce-bcd3-327c14b2ecfc.png)

**Comment by tothradoslav** [comment]
Thank you for the feedback! Correct, available in the next release.

**Comment by tothradoslav** [comment]
V1.9.0-rc1 is available. Please try it out and please let us know whether your issue has been resolved. Thank you! https://github.com/mingo-app/mingo/releases/tag/v1.9.0-rc1
