### ISSUE TITLE
Resizable columns in Aggregator and NodeShell views

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#427]
Right now, when you aggregate or use the shell, the column width in the results section is fixed.
It can be problematic to use the table, when the data is not fully visible.
Other use case would be making screenshots of processed aggregation.

**Comment by pepkin88** [comment]
A bonus feature would be a possibility to add columns, just like on the Documents view.
A use case for that would be reaching for specific path, without the need for the $addFields or $project stage.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2

**Comment by pepkin88** [comment]
@tothradoslav I don't know, how for others, but for me those columns are still unresizable, with a fixed order.
The tooltip shows that they can be rearranged, but they can't.
<img width="189" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/07e3df8c-92b5-43d1-b461-4dcaf0622b30">
And the menu shows this:
<img width="251" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/a5a3c9d9-6083-493b-a372-b40f53f6cfa5">

The menu for the columns on the NodeShell tabs is slightly better, because of the Unpin action.
<img width="257" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/c5aee162-b8c8-4385-81b4-a7158aa4b527">
And although there is no "+ Column" button, I found a way to add one, from the context menu of the document fields (but not on the Aggregator tab).

Maybe there was a regression or something. I'm currently on the latest version, 1.13.1.
