### ISSUE TITLE
Trying to delete __v field in Schema Analysor doesn't work (or runs for eternity)

### ISSUE THREAD

**Issue by Jeannot-Muller** [mingo-app/mingo#428]
<img width="730" alt="ScreenShot 2022-06-11 at 18 24 11@2x" src="https://user-images.githubusercontent.com/7870873/173196475-b375348f-8483-4518-ba9d-8aac2e07a9ac.png">

I stopped after 5 minutes, as it is a quick task in other IDEs.

**Comment by tothradoslav** [comment]
Did this only happen on this particular field? Have you tried other fields ?

**Comment by Jeannot-Muller** [comment]
I did, it runs for eternity and is not showing more information. Eternity as in Studio3T it is a questions of a few ms.

https://user-images.githubusercontent.com/7870873/173230693-8243e1ba-08b1-45b0-89c4-c0a4e58b9f39.mp4

**Comment by tothradoslav** [comment]
Thanks for the video, I found the bug and corrected it. Will be available in the next release.

**Comment by tothradoslav** [comment]
V1.9.0-rc1 is available. Please try it out and please let us know whether your issue has been resolved. Thank you! https://github.com/mingo-app/mingo/releases/tag/v1.9.0-rc1

**Comment by tothradoslav** [comment]
Please check out the new version of Mingo: https://github.com/mingo-app/mingo/releases/tag/v1.9.0
