### ISSUE TITLE
Feature Request: Allow Data Relations to access non-root properties

### ISSUE THREAD

**Issue by lynchem** [mingo-app/mingo#429]
The data relations feature is really useful!! Nice work 👍🏻 

But it seems to be limited to root level properties so I can associate userId with 'profile' (which will show me the whole profile object) but I can't write 'profile.email' which would keep things tidy and only show that property. 

This would make it even more useful where a human  readable string might not be available in the root level of the related doc.

**Comment by tothradoslav** [comment]
V1.9.0-rc1 is available. Please try it out and please let us know whether your issue has been resolved. Thank you! https://github.com/mingo-app/mingo/releases/tag/v1.9.0-rc1

**Comment by lynchem** [comment]
I can confirm that works for me! 👍🏻 Thanks
