### ISSUE TITLE
Database and Collection in deletion popup

### ISSUE THREAD

**Issue by thiagotsn** [mingo-app/mingo#430]
Hi, 

When deleting documents, I think it's better to state which database and collection you're working with, to avoid mistakes.
<img width="513" alt="CleanShot 2022-06-13 at 21 38 45@2x" src="https://user-images.githubusercontent.com/11219154/173441346-09a8d700-c4e9-4f8b-ac1c-d6210c7e117f.png">

Thanks

**Comment by tothradoslav** [comment]
Good point, implemented! Thank you :)

**Comment by thiagotsn** [comment]
That looks great. It was exactly what I had in mind.
Thank you!
