### ISSUE TITLE
Infinite loading after inserting first documents in a collection

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#432]
I created a new collection and inserted a document. After that, I got the info, that the document has been inserted, but there is endless loading (the Refresh arrow are also spinning). It persists even after I restarted the Mingo app.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1028647/174673719-ed521137-7a2b-45c7-b0ab-d719f88d0501.png">

**Comment by tothradoslav** [comment]
Thank you, found the bug and corrected.

**Comment by tothradoslav** [comment]
Please check out the new version of Mingo: https://github.com/mingo-app/mingo/releases/tag/v1.9.0
