### ISSUE TITLE
Existence of a field named `length` prevents the object from being expanded in the view

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#433]
Here I tried to expand all the documents and subdocuments:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/1028647/174675073-bf12bb22-a341-4833-a391-34853b72e4a1.png">

There is probably some exception thrown. I tried removing a column and the unexpandable row hasn't updated (`length` should be 32 here):
<img width="503" alt="image" src="https://user-images.githubusercontent.com/1028647/174675229-c7bb0975-d0d8-49db-94d3-47d03c5535e9.png">

**Comment by tothradoslav** [comment]
Thanks, found the bug, it thought it was an array of length 12... Corrected.

**Comment by tothradoslav** [comment]
Please check out the new version of Mingo: https://github.com/mingo-app/mingo/releases/tag/v1.9.0

**Comment by pepkin88** [comment]
It is that version that updated automatically, right?
I see that it is fixed for objects inside documents, but not the documents themselves:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/1028647/175395793-f88da5c5-c48b-41be-af79-d78c0a8928d3.png">
So documents that have a field `length` at the root level cannot expand.

**Comment by pepkin88** [comment]
@tothradoslav How can I reopen an issue?

**Comment by tothradoslav** [comment]
Hi, we have uploaded a new release candidate with this issue corrected in it. Please check it out and let me know if it works fine. Thank you for your input!

https://github.com/mingo-app/mingo/releases/tag/v1.9.1-rc1

**Comment by pepkin88** [comment]
This issue has a tag "ready for next release" left from the previous attempt to fix it, but I don't see any change regarding [this comment](https://github.com/mingo-app/mingo/issues/433#issuecomment-1164855418). I mean, it still behaves like that.

**Comment by tothradoslav** [comment]
Hi, yes, sorry, I found one more issue and corrected it. I really hope, it's going to work now :)
