### ISSUE TITLE
Sometimes references are overlayed on top of each other

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#435]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/1028647/174807654-266da8c8-4038-4d7e-9d75-d962c467fb88.png">

In my case it was only for a few documents, whose _ids were the same as in other collection (integer ids), but actually were not related to each other. E.g. a place with _id 1 (on the screenshot) has nothing to do with a city with _id 1, which rendered below other pointers.
In my case, it only did it to documents with _id from 1 to 5, probably because in that collection there is a field `city` (with an explicitly defined relation `cities._id <=> places.city`), and in this batch of 50 documents there were only 5 distinct values for the `city` field: numbers from 1 to 5.

BTW, it also tried to guess a relation for other fields (not just _id), like tags here (which are in fact ids, but from a different collection named `tags`, but I didn't set the explicit relation yet). And here too, it stops at 5, despite there are more cities in the `cities` collection:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/1028647/174810135-9052ec33-42aa-48a9-a7d6-050416f25a75.png">

What I see here is probably the guessing mechanism for ObjectIds, but retrofitted to integer ids. And while it's cute, the success rate will probably be much lower, because an integer can mean a lot of different things, and ObjectId usually refer to a unique thing across the whole database.

**Comment by tothradoslav** [comment]
Thanks for the detailed report. 

Having numbers as _ids is a quite specific usecase and difficult to handle / quess as relations, as number can mean anything. This is why MongoDB decided to go with special ObjectIds. But I understand that once you go with numbers, there's no way back. 

I will try to reproduce your issue and correct it. Meanwhile, have you tried manually editing your relations in the Data Relations section (right click on the database in side bar)?

**Comment by tothradoslav** [comment]
fair enough :)

We will make sure this works, as MongoDB supports any kind of _id, anyway...

**Comment by pepkin88** [comment]
As for this issue, I think that for non-ObjectIds those reverse references (outward arrows) should be provided only for explicitly defined relations, like in my case, the field `places.city`.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
