### ISSUE TITLE
[feature] Search inside document

### ISSUE THREAD

**Issue by brunoosilva** [mingo-app/mingo#437]
- Add feature of search (open input text) inside document (View document/Edit document), for fetch anything in longer JSON for example.
- Add text mode view with input search too (same Robo 3T)
![image](https://user-images.githubusercontent.com/3465257/175191229-01677db9-afbc-40ef-bbe5-95e66edb862d.png)

**Comment by tothradoslav** [comment]
Thanks for this. I improved the search functionality, this should be out in next release.

**Comment by tothradoslav** [comment]
Hi, we have uploaded a new release candidate with this issue corrected in it. Please check it out and let me know if it works fine. Thank you for your input!

https://github.com/mingo-app/mingo/releases/tag/v1.9.1-rc1
