### ISSUE TITLE
[bug] Lost my custom actions after last upgrade

### ISSUE THREAD

**Issue by brunoosilva** [mingo-app/mingo#438]

**Comment by tothradoslav** [comment]
Hi @brunoosilva , do you remember what was your previous version of Mingo? I'm trying to find the issue so it won't happen again... Thanks!

**Comment by tothradoslav** [comment]
We have changed the way we store this data and this should not happen any more. If you upgrage from an older version to 1.12.0 or newer, you might loose some parts of the data, but from then on, it should be fine.
