### ISSUE TITLE
On the NodeShell results screen, pinned columns have capital first letter when they definitely do not

### ISSUE THREAD

**Issue by pomelo-rich** [mingo-app/mingo#441]
![image](https://user-images.githubusercontent.com/92314031/176107832-209a7e2e-f4b1-4903-bc7f-33b80459ac2f.png)

This is in the NodeShell view. CompanyId and CreatedAt do not have capital letters.

![image](https://user-images.githubusercontent.com/92314031/176107962-1dbeea86-4e00-43af-a620-e36f3f0ed169.png)
This Documents view is how the keys really are.

**Comment by tothradoslav** [comment]
Thank you, corrected in next release.

**Comment by tothradoslav** [comment]
Hi, we have uploaded a new release candidate with this issue corrected in it. Please check it out and let me know if it works fine. Thank you for your input!

https://github.com/mingo-app/mingo/releases/tag/v1.9.1-rc1
