### ISSUE TITLE
Incorrect update query generated

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#442]
When I have found a record via Cmd+G (i.e., a value from an indexed field is on the clipboard) and then click that document to select it and then hit Update, the generated query is invalid -- `XXX` is the value that was on the clipboard, but it should be `{ field: 'XXX' }` instead of just `XXX`.

```
async function run() {
	return await db.collection("[collectionName]").updateMany(XXX,
	{$set: {
		
	}})
}
```

**Comment by tothradoslav** [comment]
Thank you! Found the issue, corrected.

**Comment by tothradoslav** [comment]
Hi, we have uploaded a new release candidate with this issue corrected in it. Please check it out and let me know if it works fine. Thank you for your input!

https://github.com/mingo-app/mingo/releases/tag/v1.9.1-rc1
