### ISSUE TITLE
What are projects for?

### ISSUE THREAD

**Issue by dlucazeau** [mingo-app/mingo#443]
Hello,
I work more and more with Mingo :smile:
In each of our environments, we have several mongodb bases each with a different port. We access them through port forwarding.
When I deploy a project associated with an environment, I only have one channel open. Opening a project should not open all its connections.
Allowing us to choose which database/connection to choose by a choice tree for example would fit my way of working.

For me, a project is more an organization of possible connections, if a connection is associated to a project, it should not be displayed alone.

Maybe I didn't understand your vision of projects. I probably have a different approach.

**Comment by tothradoslav** [comment]
Thank you! It would probably be best if we could have a quick online call so you can show me your use case exactly. We might have miscomunicated what projects are or maybe you just have an idea for improvement :)

Would you be willing to have such a call?

**Comment by dlucazeau** [comment]
I don't speak english well enough to explain my vision. I will prepare a video.

**Comment by tothradoslav** [comment]
Maybe we speak something similar :D 
OK send us a video and we'll work from there.

**Comment by dlucazeau** [comment]
Hello
I found my words.
I thought I understood that a project is more a folder than a set of connections to be opened all together.
