### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by cluelesscamel** [mingo-app/mingo#447]
Hello,

I get asked some very specific database exports very often that aren't offered by the app that runs on top of the database. In order to return this export in a more usable format, I export to JSON and use some free JSON to CSV website to make this usable for whoever requested it.

It would be a real time saver if exporting aggregations to CSV was possible.

Thanks

**Comment by tothradoslav** [comment]
Hi, do you mean an option to export results from a aggregation that you entered in Aggregator?

We could definitely do this. Also, we could improve the export tool to enter the agregation pipelilne directly.

**Comment by cluelesscamel** [comment]
Hi,
In short, what I'm asking for is, the ability to export aggregation results directly to CSV format. Right now only JSON and Javascript (both clipboard, file and zip file) are possible.
I always take the JSON to clipboard option and paste the output into a JSON to CSV online tool. It would be nice to not have to do the last step.
Thanks!

**Comment by tothradoslav** [comment]
Could you send me the online JSON to CSV tool you use? This should be no problem, but I'm thinking of the nested values and how to represent them in CSV.

**Comment by cluelesscamel** [comment]
I use two different tools for this very reason:
- https://www.convertcsv.com/json-to-csv.htm will generate columns depending on the amount of embedded array elements and name them something like `users/1`, `users/2`, ... I usually choose this tool when I know the CSV file will be used in spreadsheet software to calculate something.
- https://data.page/json/csv will generate new lines with only values in the column of the embedded array in order to show the data hierarchy better. I go for this tool when I know the file will just end up being read by whomever I'm making it for.

I think for a tool like Mingo. The first option is probably the best?

**Comment by kuhwar** [comment]
+1,  You guys already have export to csv on collection, adding similar functionality to aggregation results will be perfect

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
