### ISSUE TITLE
Change source of aggregation

### ISSUE THREAD

**Issue by cluelesscamel** [mingo-app/mingo#448]
Hello,

When building an aggregation, changing the source database in the top left corner doesn't seem to do anything.
Refreshing any of the stages also just keeps using the initial source of the aggregation.

Thanks!

**Comment by tothradoslav** [comment]
Thank you for reporting this, it's corrected, ready for next release!

**Comment by cluelesscamel** [comment]
Awesome! Thanks!

**Comment by tothradoslav** [comment]
Hi, we have uploaded a new release candidate with this issue corrected in it. Please check it out and let me know if it works fine. Thank you for your input!

https://github.com/mingo-app/mingo/releases/tag/v1.9.1-rc1
