### ISSUE TITLE
t.map is not a function

### ISSUE THREAD

**Issue by thiagotsn** [mingo-app/mingo#449]
Hi,

I got an issue that the collection was not opening up.
The error description was: _t.map is not a function_.

I realized was specific to the schema I was using, and this schema was changed before.
So after deleting all data relations to the collection it worked.
Not sure if this is enough to go forward.

Thanks

**Comment by tothradoslav** [comment]
Hi, sorry for the late reply... well, not much information there :)

A few questions to get closer:
1. the error was shown in the Documents section ?
2. so the actual data in collection have changed, especially their structure (schema) has changed?
3. could you regenerate the relations afterwords ?

Thank you!

**Comment by thiagotsn** [comment]
No worries.

1. Yes, the error was shown in the Document section, when trying to make any query.
2. Yes, the schema changed. Therefore, the data also changed.
3. After deleting the relation, I could regenerate and the error went away.

Thanks

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
