### ISSUE TITLE
Invalid Selector: ReferenceError: NumberLong is not defined

### ISSUE THREAD

**Issue by daviddesmet** [mingo-app/mingo#450]
When I try to query using Mingo, I get the error **Invalid Selector: ReferenceError: NumberLong is not defined**

This is the query I used:

```js
"LongValue": NumberLong("6917529027646853181")
```

It works with Compass.

**Comment by tothradoslav** [comment]
Thank you! Well, NodeJS MongoDB driver does not directly support NumberLong(), but we were able to "fake" it and you will be able to use NumberLong as you wrote above.

Also, from now on, you can use the following, too:

`{email: Long.fromString('1234112341234')}`

Details here: https://mongodb.github.io/node-mongodb-native/2.2/api/Long.html

**Comment by tothradoslav** [comment]
Hi, we have uploaded a new release candidate with this issue corrected in it. Please check it out and let me know if it works fine. Thank you for your input!

https://github.com/mingo-app/mingo/releases/tag/v1.9.1-rc1
