### ISSUE TITLE
Query and results color match

### ISSUE THREAD

**Issue by lluistar** [mingo-app/mingo#451]
Currently, the query colour for a string is green and the result colour for a string is orange.
For an Integer the query colour is orange and the result is blue.

Would not be better if they match. A string is the same colour everywhere and the integer as well.

**Comment by tothradoslav** [comment]
Do you mean here?

<img width="416" alt="Screen Shot 2022-07-27 at 08 48 08" src="https://user-images.githubusercontent.com/3465808/181180372-a8915187-fcce-4038-a8e6-2e207b82198a.png">

and the results in documents?

<img width="510" alt="Screen Shot 2022-07-27 at 08 51 35" src="https://user-images.githubusercontent.com/3465808/181181002-f49a9e25-10e5-4dea-816d-657e2eb7e993.png">

I see different colors here. Please send screenshots :) thank you!

**Comment by lluistar** [comment]
I’m on the mac using dark view. That’s why the colours differ.

See my screenshot:
Query string: Green
Query Integer: Orange
Query Boolean: Orange
Result string: Orange
Result Integer: Cyan
Result Boolean: Green





All the best,

Lluis Tarrida

**Comment by lluistar** [comment]
Screenshot didn't show.
<img width="818" alt="Mingo Colors" src="https://user-images.githubusercontent.com/4211139/181281378-aeea3504-1f54-450e-a5f6-42917536b920.png">

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
