### ISSUE TITLE
Improve index display

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#453]
A few ideas for improving the index display:
1. Be able to resize the columns in the index display (or at least make them wide enough to accommodate long index names)
2. Be able to export the index list to a CSV file
3. Include as an additional column whether an index is hidden
4. Be able to hide or unhide an index in the right-click context menu

**Comment by tothradoslav** [comment]
1. this is now done automatically onload, based on column contents
2. done
3. done, added hidden, background, sparse (all true / false options)
4. not done, you can edit the index regularly, this is edge-case and if hidden is added, might as well add many other options, so skipped this one

**Comment by brianlukoff** [comment]
Awesome - thanks!

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by brianlukoff** [comment]
Fantastic -- works great for me!

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
