### ISSUE TITLE
Quick reference > themes still mentions compact mode

### ISSUE THREAD

**Issue by cluelesscamel** [mingo-app/mingo#455]
...But I think it was removed from preferences, right?

**Comment by tothradoslav** [comment]
thank you! removed :) (in next release)

**Comment by tothradoslav** [comment]
Hi, we have uploaded a new release candidate with this issue corrected in it. Please check it out and let me know if it works fine. Thank you for your input!

https://github.com/mingo-app/mingo/releases/tag/v1.9.1-rc1
