### ISSUE TITLE
Aggregation summary update issue

### ISSUE THREAD

**Issue by cluelesscamel** [mingo-app/mingo#456]
The summary above an aggregation is not updated correctly when running the aggregation again renders no results.

Replicate:
- Set up and run an aggregation
- Change the db so the aggregation will not return any results
- Run the aggregation again

The "Result: 2 documents" will remain, even though there are now 0 documents.
An error will show up saying: "TypeError: Cannot read properties of undefined (reading 'count')"

**Comment by tothradoslav** [comment]
thank you! Corrected in next release

**Comment by tothradoslav** [comment]
Hi, we have uploaded a new release candidate with this issue corrected in it. Please check it out and let me know if it works fine. Thank you for your input!

https://github.com/mingo-app/mingo/releases/tag/v1.9.1-rc1
