### ISSUE TITLE
MongoNetworkTimeout UX improvement

### ISSUE THREAD

**Issue by VladimirMikulic** [mingo-app/mingo#458]
Hi! When querying non-indexed fields on big collections, I usually get MongoNetworkTimeout error.

![Screenshot_20220719_125043](https://user-images.githubusercontent.com/35997844/179734268-abe201de-b7af-403d-be83-fec6452d9b15.png)

I found out later in preferences that connection timeout can be increased which is great!
However, this wasn't immediately obvious so I feel like there should be a pointer (and maybe helpful explanation) below error message like:
"This error is usually a result of querying non-indexed field on a big collection.
Please go to Preferences if you'd like to increase connection timeout or set an index to the desired field."

Also, when I modified default connection timeout, changes were not picked up in the same session/window.
I had to restart the app in order for changes to take effect - maybe this should be automatic on save or show restart notification like VS Code to avoid confusion?

Thanks!

**Comment by tothradoslav** [comment]
Thank you, both done. I created a system for "tips" based on error message. Also, connections will be restarted everytime you change the settings.

**Comment by VladimirMikulic** [comment]
Thank you so much @tothradoslav.
You guys rock!

**Comment by tothradoslav** [comment]
Hi, we have uploaded a new release candidate with this issue corrected in it. Please check it out and let me know if it works fine. Thank you for your input!

https://github.com/mingo-app/mingo/releases/tag/v1.9.1-rc1
