### ISSUE TITLE
Ability to disable an aggregation pipeline stage

### ISSUE THREAD

**Issue by Icaruk** [mingo-app/mingo#459]
Sometimes I have:

- Stage 1
- Stage 2
- Stage 3

But I want to temporally disable `Stage 1` then re-enable it later, I haven't found a way to do that without deleting the content.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
