### ISSUE TITLE
Paste & Go incorrect query for ObjectId values

### ISSUE THREAD

**Issue by Icaruk** [mingo-app/mingo#460]
1. Paste ObjectId like "62d6b78d911ea02e13156044"
![](https://i.gyazo.com/0c51de2f1b4f8da3606f8b43e7a34034.png)

2. Click "Paste & Go" or `ctrl + enter`.
![](https://i.gyazo.com/f99ff2bc2216979a35df381931855a03.png)

3. Press `ctrl + enter`, `F5` or click "Refresh" button.

> No documents found...

---

The correct query should be:

```js
{
  "_id": ObjectId("62ab4e9b42c7f8f523f9906e")
}
```

so consequent refreshes don't fail.

**Comment by VladimirMikulic** [comment]
I was just about to report the same issue.
@achtan @tothradoslav is there a chance you guys could squeeze in the fix for this in 1.10?

**Comment by tothradoslav** [comment]
Thank you, fixed. Will be in 1.10. 

For now, the format is JS, so it's {_id: new ObjectId(....)} but we will probably be chaning this in near future.

**Comment by VladimirMikulic** [comment]
You're amazing @tothradoslav! Thank you so much!
