### ISSUE TITLE
Missing system app icon when installed as .deb

### ISSUE THREAD

**Issue by cmtinz** [mingo-app/mingo#462]
I have installed Mingo using the .deb installer (version 1.9). I works great but it does not show any system icon: system tray, apps menu, control panel.

I am using Ubuntu 22.04 LTS.

![image](https://user-images.githubusercontent.com/21244179/181412458-dfd70f35-33a2-4103-a9ed-ffe228400381.png)
![image](https://user-images.githubusercontent.com/21244179/181412760-071c55d7-27e5-4a27-b4ba-2eb6b5050bde.png)

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
