### ISSUE TITLE
Paste & Go results in COLLSCAN

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#463]
When I do Paste & Go on one of my collections, Mingo searches in a field that is NOT indexed, and so the query results in a COLLSCAN! Is there a way to restrict Cmd+G to only do a query on the `_id` field?

**Comment by tothradoslav** [comment]
(I've responded in discord but this is better here) 
Looking at the code, I'm wondering how this could have happened :) Mingo caches the fields it should be searching, but this is updated quite regularly. 

1. does that collection have any other indexes besides _id field?
2. if you refresh the database (button in the sidebar), does this still happen?
3. what is the string you are doing the page&go with? Is it a string? ObjectId? Number?

**Comment by brianlukoff** [comment]
Yes - it does have 2 other indexed fields (plus _id), but Mingo was also searching a 3rd field that was not indexed. After restarting Mingo, I'm not able to replicate the problem - Paste & Go seems to work properly (with a string)! It must have cached the other field from some time ago - I think it was indexed at one point but the index was never used so it was dropped. So I guess the moral of the story here is that we should refresh the database in the sidebar any time we change the indexes.

**Comment by tothradoslav** [comment]
My moral of the story here is that everytime an Index is updated / added / removed by Mingo (so it's aware of the change), it should do the update automatically. Let me keep this open and sort it out.

**Comment by brianlukoff** [comment]
Thanks! Although to be fair I don't think we used Mingo to drop the index (we probably did it within the Atlas UI) so it may be my fault! One feature request (and the only reason I'm in the Atlas UI view of indexes) is that it's easier in Atlas to get the full name of the index (which can get cut off in Mingo since the columns aren't resizable) and see usage on a per minute/hour/day basis (rather than total # of uses).

**Comment by tothradoslav** [comment]
This can now be achived by right-click on a database (in side menu) and selecting "Refresh meta information". This will update the indexes used for paste&go.
