### ISSUE TITLE
"Command is not a function" when searching by value that contains "#0000"

### ISSUE THREAD

**Issue by Icaruk** [mingo-app/mingo#465]
Empty find `{}` works fine:
![3c58c5f8b4687c3c157de3801b00acc3](https://user-images.githubusercontent.com/10779469/182962121-005faeac-c791-4f4f-95ef-377021cd221a.png)

But `{anyField: "#0000"}` causes the "Command is not a function" error:
![48168edfb4e20d60b79fde06dd4ae7b2](https://user-images.githubusercontent.com/10779469/182962924-d3ade2b5-6e0a-4b1b-9424-4578e1b6a38f.png)

Some tests:

- ✅ `{anyField: "#0"}`
- ✅ `{anyField: "#00"}`
- ✅ `{anyField: "#000"}`
- ❌ `{anyField: "#0000"}` (same with any number)
- ✅ `{anyField: "#000a"}`
- ✅ `{anyField: "0000"}`
- ✅ `{anyField: "0000#"}`
- ✅ `{anyField: "#asdf"}`
- ❌ `{anyField: "#today"}`
- ❌ `{anyField: "asdf#0000"}`
- ✅ `{anyField: "asdf#000"}`

**Comment by tothradoslav** [comment]
Thank you, this was due to our tagging system for dates. I improved the regex to exclude matches inside double or single quotes.
