### ISSUE TITLE
Regression in v1.9.1-rc1 – Clicking a collection on the sidebar only focuses an existing tab

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#466]
That change in behavior surprised me, I don't think it is intended.
When I clicked on a collection on the sidebar, I expected it to open a new tab with that collection.
What I got instead was just focusing an existing tab of that collection, that I happened to have already open, with its own filters and results. When there's no tab with a certain collection, only then it opens a new tab.

But when I right-clicked the sidebar item and chose "Open [collection name]", then it opened a new tab. A behavior, which I was already familiar with, and to be honest, is a standard one in DB admin tools like Mingo (where a single or double click always opens a new tab).

**Comment by pepkin88** [comment]
OK, I see now that it was intentional #445
At least there is an option to change it, so I guess it's fine.

**Comment by tothradoslav** [comment]
Maybe if I just change the default value to the original functionality and users may change this in settings...
