### ISSUE TITLE
Feature request: Make the _id column as functional as other columns

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#467]
Other columns are resizable, sortable (although you can just edit the query), and have other features, that the first column, the _id column, doesn't have.
But the biggest one for me is, that I can't copy distinct values from that column (for _id it would be the same as copy values), which I happen to need from time to time.
I also tried to remedy this by adding a new column with path `_id`, but I couldn't, because Mingo told me "_id already pinned".

I see, that currently it has number of documents as the label, which is good, but clicking on it just checks the checkbox on the left.
I'd propose to let the checkbox to do what it does now, but let the column label act like the other columns. Maybe leave out some, like "Rename field", "Cast values to..." and "Update values to...", because _id is immutable. But as for other features, I don't see why they shouldn't apply to _id too.

**Comment by tothradoslav** [comment]
We are actually working on this for the exact reasons you mentioned. Our biggest issue is “what to do with results coult” as it currently has a good position. We want to make the _id field just like others, but it should have its own “_id” title. Then we have to move the results count somewhere without using up extra vertical space. 

Any ideas?

**Comment by pepkin88** [comment]
I think the result count there is ok, it can stay there, a good use of space.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
