### ISSUE TITLE
Error editing document with Decimal128

### ISSUE THREAD

**Issue by anselmodev** [mingo-app/mingo#468]
When editing a document using "Edit Doc JSON" where it has some property in the "Decimal128" format, this property is wrongly saved as an "Object" and removing the "Decimal128" format. I made available an attachment of the examples, 1 of them, an edition made in MONGODB COMPASS that allows editing of values in "Decimal128".

Editing in Mingo:
![01-mingo-decimal128-on-edit](https://user-images.githubusercontent.com/14978874/183635893-fcb565a0-4dad-4bd8-8915-b1502a1efe64.png)

After edited in mingo:
![02-mingo-decimal128-edited](https://user-images.githubusercontent.com/14978874/183635936-40b24696-c920-4f1d-83f0-18051af4d9a2.png)

Editing in mongodb compass (correct type):
![03-mongodb-compass-correct-edition](https://user-images.githubusercontent.com/14978874/183635962-05f33550-7d96-410d-b13a-19640be03b77.png)

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
