### ISSUE TITLE
Schema Analysis Screen can not filter docs with Not Sets properly

### ISSUE THREAD

**Issue by kuhwar** [mingo-app/mingo#469]
On Schema Analysis screen if wanted to filter out docs that does not contain the specific fiield (Not Set) 
![image](https://user-images.githubusercontent.com/5969368/185942806-891304d7-8a1b-4fb8-99c5-7df83b90b221.png)

find query should be {"sampleField":{$exists: false}} instead of {"sampleField":{}}
![image](https://user-images.githubusercontent.com/5969368/185942509-60b660e3-9e0b-4f62-9547-7be69667cf7b.png)

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
