### ISSUE TITLE
Group by and count doesn't work for arrays

### ISSUE THREAD

**Issue by thiagotsn** [mingo-app/mingo#470]
When trying to use the **Group by and count** feature for an array record, it's aggregating all records in an empty string.
Example: 
<img width="491" alt="CleanShot 2022-08-23 at 14 59 10@2x" src="https://user-images.githubusercontent.com/11219154/186177881-21d84977-a411-4cee-be48-92a0bf37784f.png">

**Comment by tothradoslav** [comment]
Thanks for this. Could you please provide more info on where you are using this feature? It could be on a specific field in the documents view or on a column?


<img width="530" alt="column" src="https://user-images.githubusercontent.com/3465808/192868263-47ab3423-0302-4f0b-97de-5fcd3b6a3190.png">
<img width="903" alt="field" src="https://user-images.githubusercontent.com/3465808/192868274-91628e80-a2ef-468c-a6ff-16c8baba54cb.png">

**Comment by tothradoslav** [comment]
OK thanks, will correct it. I see your issue now. Can you send a small example of your doc? Or just a part of it and what you select do group-by-count? Is it an array of strings (or other primitive values) or an array of objects?

**Comment by tothradoslav** [comment]
Can you send a small example of the doc / array? Is it an array of primitive values (strings, numbers, etc...) or an array of objects?

**Comment by thiagotsn** [comment]
It's an array of objects. If I select any primitive type inside the object it'll display the values above.

{
  "item": [
    {
      "id": "12345",
      "customer": "JOHN DOE",
      "product": {
        "name": "Product Test",
        "type": "BOOK"
      },
      "quantity": 1
    },
    {
      "id": "54321",
      "customer": "JANE DOE",
      "product": {
        "name": "Product Test 2",
        "type": "PEN"
      },
      "quantity": 1
    },
  ]
}

**Comment by thiagotsn** [comment]
I was expecting to group and count all documents in the collection

**Comment by tothradoslav** [comment]
This now works both on arrays of primitive values and on nested arrays of objects. So you can now groupby and count on something like this for example: photos.0.title (will groupby / count all title in all photos)

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by thiagotsn** [comment]
It's working now. I just tested it.
Thanks!

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
