### ISSUE TITLE
Query box is too small

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#471]
Sometimes, pasting in a query results in the query box being too small to see/edit the entire query.

**Comment by Ravetracer** [comment]
+1. 
Same goes with the input box for aggregation stages. Sometimes our stages can be a bit larger and this box is then much too small.

**Comment by tothradoslav** [comment]
This actually happens to me sometimes, too, but I'm not able to reproduce this now. Is There any way you could send a way to reproduce this? Thanks!

**Comment by tothradoslav** [comment]
We improved the behaviour, let's see if it works better now.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
