### ISSUE TITLE
Field of type "$numberDecimal" is not displayed correctly

### ISSUE THREAD

**Issue by jjbc93** [mingo-app/mingo#473]
Hi,
I have seen that when showing the fields of type "$numberDecimal" they appear correct but when I try to edit them or see them in json format, they appear as (bytes)
I hope you can take a look at it and fix it. 
Thank you very much, greetings
![number_1](https://user-images.githubusercontent.com/14858699/186414360-b543d3d5-1d6e-4c49-a501-2d2ed9ec05c2.png)
![number_2](https://user-images.githubusercontent.com/14858699/186414373-1a00c70f-a6ba-4119-8425-1d0f79a3f99c.png)

**Comment by jdponomarev** [comment]
I'm having the same issue

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
