### ISSUE TITLE
Session completely lost including DB connections

### ISSUE THREAD

**Issue by mogarick** [mingo-app/mingo#474]
I closed the app and it updated to the new version (1.9) but it reset all my previous setup, including my DB connection strings, open tabs, etc.

I had previously updated from another previous version and this didn't happen.

I'm on macOS Monterey (12.5.1)

**Comment by tothradoslav** [comment]
Sorry for the late reply :(

This is quite strange and I'm not sure how to debug this. Did the app ask for closing in order to update to new version? In other words, did you know the app is going to update itself when you close it? Thank you!
