### ISSUE TITLE
Unusable collection view after a faulty column rearrangement

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#475]
I tried to reorganize some columns in the default collection view, but it didn't go well.
The columns, which order I tried to change, were the last or second to last, I don't remember well. I noticed, that after reordering the headers, the data part of the table remained the same. So I thought to myself, this is a bug, and reversed the changes I've made, so that the headers were above the correct columns.
But then, every time I clicked refresh, the table stayed unchanged. And when I opened the new tab of that collection, there was no table at all, only pagination.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/1028647/187896300-65e4b08b-ecca-4998-874c-ef15a9296ef6.png">

I don't remember the exact steps I made to stumble upon this bug. But I'm afraid to search, because I don't want to lose the access to another collection.

I tried messing around with columns on a test collection, I couldn't recreate this bug. But I found another, because I couldn't unpin any column. In fact, I seem to be unable to unpin any column anymore. I don't know, but I think it's because my copy of the app is in some botched state.
I also can't customize columns – the overlay gets rendered but with no window, so I don't event have a way to return, other than to restart the app.
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/1028647/187900605-faf66621-fe02-4d3f-aeb7-b3b0ee7a075e.png">

I assume, that all those bugs are caused by some unrecoverable exception under the hood, that caused the app to stop current task – in my case those tasks would be: update the column change on the table, render the table, unpin a column.

My machine ID is `6c5d39140a7c5076e9b965b012b56c785e02017055b9be4624e62eb9b4cc4deec9ba675b045180a4a12693924caa1f849b954e01457fc6a45c6a507f1734df8d`, hope it helps.

**Comment by tothradoslav** [comment]
Thank you for this and sorry for the late reply :(

I went through the code and trying to find what could have caused this. You are right about the possible exception in the background. This might be difficult to reproduce. Has this happened since? Has this persisted after restarting the app? I'm looking at your screenshot, you have several columns with the same name. Did you set it up in that way or is this the result of the error? Thanks!

**Comment by pepkin88** [comment]
I'm back from my vacation :)

> Has this happened since?

No other collection has broken since then, but I tried not to reorganize columns, not to break anything.

> Has this persisted after restarting the app?

Yes, the affected collection is still broken. I can't query any documents from it.

> I'm looking at your screenshot, you have several columns with the same name. Did you set it up in that way or is this the result of the error?

This is in a different collection, a test one, for experimenting/reproducing bugs. From what I remember, before this issue I couldn't add columns of the same name. Now I can and there is no (working) protection against it, I think it is connected with this issue.

---

Even if the cause is unknown, is there a way to reset this collection to a base state? Thanks.

**Comment by tothradoslav** [comment]
Hi, just a quick reply, the only way to reset the collection is to actually remove the connection from Mingo and recreate it, unfortunately :(

**Comment by pepkin88** [comment]
I manage to find what was broken in the view of this collection. I'm still trying to find out, how this happened.

So after messing with columns, somehow there was added a `null` as one of the columns. That caused an error, which disabled the view.
<img width="596" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/c53969c2-d6f5-4cd4-be3c-1f3fc793e8ba">

And indeed, when I inspected the JSON of the exported Mingo state, now I see that `null` there. I must have missed it before.
<img width="158" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/34b482fb-c747-44a3-bb8a-bd281010a399">

**Comment by pepkin88** [comment]
As for resizing the columns in other collections, it seem that there is some code triggered not only for current collection, but for the bugged one too:
<img width="454" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/1bcb0963-0bb7-46ba-a803-8c3a04e205da">

Maybe some re-render event was triggered for all collections? I don't know.
It's interesting, that in some collection I could still resize and add/remove columns. In views of those collections, there was no iterating over the bugged collection columns, so there was no error thrown.

**Comment by tothradoslav** [comment]
Thank you for the detailed info. I have honestly not idea how the "null" got there, yet, but I have updated the code to handle such cases properly. I will try to find the way this could have happened.

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
