### ISSUE TITLE
The tab bar doesn't update upon the window resize

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#476]
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/1028647/187899170-9a60dd8a-1287-4d29-883f-55ecbab6a3a1.png">

The tab bar only refreshes, when I open a new tab or close the one already existing.
But when I resize the window, it stays the same. When I increase the horizontal size, it would leave an empty space, but when I decrease it, it would make some tabs unreachable, because of the overflow.

**Comment by tothradoslav** [comment]
Wow, that's a lot of tabs :) We will take a look and correct this. Thank you!

**Comment by pepkin88** [comment]
Hehe, this is the way I roll :D
Ideally, there would be 2 rows of tabs, working in the same way like in Vivaldi Browser (top row for separate "sessions", inner row for tabs related to each other, created in current "session", like references from another collection).
But of course I don't expect anything like this to be implemented here. I'm aware my style of working is very niche.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
