### ISSUE TITLE
"Copy distinct value" converts values to string, instead of Extended JSON format

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#477]
It might be good for some use cases, when we want to extract some data for analytical purposes, but I'd argue, that the Mongo's Extended JSON format is more versatile.
- it can be easily converted to its string representation, if it's needed
- it retains the information about the type
- it can be used in other use cases, e.g. in subqueries
- it's still pretty readable, if not more readable in some cases – you get `"text"` instead of `text`, `ObjectId("5c9c241f6446c20b581772e7")` instead of `5c9c241f6446c20b581772e7`, and `ISODate("2019-03-28T02:32:15.647+0100")` instead of `Thu Mar 28 2019 02:32:15 GMT+0100 (czas środkowoeuropejski standardowy)`

If I extract a list of ObjectIds, I cannot paste it into a query without reformatting them in a text editor and wrapping all in `ObjectId('xxx')`. Yes, I unfortunately still have to add commas, but still it's an easier operation.

P.S. It is just my opinion, but I prefer this format, over the "JavaScript" one, which I've seen being used throughout the app, so `ObjectId` and `ISODate` instead of `new ObjectId` and `new Date` (which btw, should imo use an ISO formatted argument, and not the result of toString). It's a standard format in Mongo Shell, the `new` keyword for ObjectIds is unnecessary, and ISO strings are easier to read in a tabular representation and are more compact, there is no need for this long time zone name. But I'd admit, that having `new Date` is better, when we copy those values to a Node script for example.

**Comment by tothradoslav** [comment]
Yep, this is something we have been thinking about a lot lately. We get different feedback from people about what format they prefer. We should standardize this throughout the app, becuase it affects how we show, edit, parse the data and also how we export them. Maybe we should have a way to select your prefered format in settings. What do you think?

**Comment by tothradoslav** [comment]
We have decided to keep this as is now. There are several reasons, but mainly, the simple formats are more often used. 

When copying ObjectIds, it behaves as you mentioned.
