### ISSUE TITLE
Problems with adding a column with a hyphen in their name

### ISSUE THREAD

**Issue by pepkin88** [mingo-app/mingo#478]
Some field names can be legal, but might not be a legal JS identifier, like `content-type`.
I had some issues with adding a column labeled as `reqHeaders.content-type`. The value was `undefined` for all rows, so I had to change the path manually in the Customize column window to `reqHeaders['content-type']`, then it worked (I think, I'm not 100% sure, but I cannot check it now, because of #475).

I think it should work correctly from the start, without the need to manually adjust the path.

Having a dash/hyphen in a name is just an example, there are more names that are field names but not identifiers. Like starting from a digit `"2good2btrue"`, have spaces `"Mingo App"`, or some other character `"email@address.com"`, `"wait!theresmore"`, `"['I might look like an array, but I am not']"`, etc.

**Comment by tothradoslav** [comment]
Sure, we have thought of this previously, and if your identifier contains a space, for example, Mingo does this automatically. We will improve this for cases where the identifier is illegal in JS. Thanks!
