### ISSUE TITLE
"Toggle value to TRUE/FALSE" does not respect database lock

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#479]
The right-click context menu option to "Toggle value to TRUE/FALSE" seems to take effect immediately without needing to unlock the database for writes.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
