### ISSUE TITLE
Feature: Add select field

### ISSUE THREAD

**Issue by VladimirMikulic** [mingo-app/mingo#481]
Hi!

I was wondering if you could add "select" field between Query and Sort.
We have some heavy collections so being able to select only certain fields to return would be a great time saver on query time.
Another useful usecase that this would unlock be to Copy JSON/JS (copies exactly what I need without going to exported, loading data etc.)

![Screenshot_20220909_202939](https://user-images.githubusercontent.com/35997844/189420382-d1ddee38-2ae9-4e0b-8240-77b0f436cff2.png)

![Screenshot_20220909_204331](https://user-images.githubusercontent.com/35997844/189421788-7139c0bc-a176-458c-88e7-787d23118e96.png)

Thanks for amazing tool as always!

**Comment by tothradoslav** [comment]
Maybe you have noticed that we do have the "project" field in Schema analyzer, for example. With documents, we have considered this many times over and we always bumped into some issues with not showing entire documents (only the selected fields).

First issue would be the same exact advantage you mentioned. We would have to clearly specify whether people are copying the entire doc or just the projected part of it. Editing, adding fields might be another issue. A psychological UX issue might be that people don't realize they are looking at only a part of their document. And there are several other. One more example: let's say I have 10 columns pinned, but I project only one field. What happens to the 9 other columns pinned? Their "values" would be "undefined". 

I definitely understand your point. We need to think it through properly to prevent confusion. So any ideas / comments on this are very welcome! And thanks again :)

**Comment by VladimirMikulic** [comment]
Appreciate your reply @tothradoslav. You're definitely right, it is a big feature with many edge cases to account for.
It's nothing urgent though, just wanted to put it in your backlog for next major iteration :)

**Comment by frebos88** [comment]
As I mentioned in the other issue, we are sometimes using Mingo to write queries before putting them inside an application. Having the option to use projection would be very valuable in those cases. I understand the UX problematics and I agree that with Mingo's design it's really not great to put it inside the normal query view. With that said, I would still love to open up a different view (such as aggregations) with less "smart" functionality that Mingo does great, or have it as a non-default option to toggle.

**Comment by tothradoslav** [comment]
Considerations / todos:

- [x] enable projection in Documents view
- [x] when projection is entered (not equal to {}), highlight this information above results with option to clear projection with one click (Projection enabled!) (Reload entire documents)
- [x] view doc, edit doc, duplicate doc should / would not work properly
- [x] add field may overwrite existing value (which is not visible in UI)

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by VladimirMikulic** [comment]
@tothradoslav it works great. Thank you so much!
I also noticed collections search on the new tab is MUCH faster! Really great work!

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/issues/485

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
