### ISSUE TITLE
Overflow problem at right-click menu

### ISSUE THREAD

**Issue by fers4t** [mingo-app/mingo#483]
![image](https://user-images.githubusercontent.com/58539842/189931074-eedc3ca5-0e8f-441e-a8b1-e7d2918280e3.png)

**Comment by tothradoslav** [comment]
Thank you. We are aware of this problem in case the menu does not fit into your screen. Is this your usecase, too?

We'll come up with something :)

**Comment by tothradoslav** [comment]
This one is quite tricky, but we improved the behaviour a bit.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
