### ISSUE TITLE
orphan management

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#485]
Find records that are not associated with the "parent" record.

https://www.cansayin.com/orphan-records-control-on-mongodb/

**Comment by tothradoslav** [comment]
how would this look like in Mingo's UI?

**Comment by tothradoslav** [comment]
I would use this: https://stackoverflow.com/questions/65488403/how-to-get-the-documents-which-didnt-have-parents-in-mongodb

But the question is still how to do this in UI?

**Comment by tothradoslav** [comment]
We added this into Data Relations view as "Find orphaned documents". Once documents are analyzed, the number of orphans is shown with options to view these documents or delete them right away.

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
