### ISSUE TITLE
app is slow when using large DB's

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#486]
Feedback from our user:
> Your app is very usefull and your price point is fair but i have a problem.
we have a system to keep statistics. We create a new collection every day. In other words, we currently have more than 700 collections and there are millions of documents in each collection. Every time I open your app it takes too long to sync to see the collection list.

**Comment by tothradoslav** [comment]
This is edge-case, but what we could do about it:
1. in case the number of collections in a DB exceeds X, load simple stats only and don't store them for Mingo
2. other options / ideas?

**Comment by tothradoslav** [comment]
this has already been implemented in v1.12.0
