### ISSUE TITLE
Scrip generating from operations

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#488]
<img width="722" alt="image (3)" src="https://user-images.githubusercontent.com/1048212/192226658-a50c3ccf-552b-4ce7-9e73-becc6a3d4000.png">
<img width="888" alt="image (4)" src="https://user-images.githubusercontent.com/1048212/192226671-a88b53c4-f4ab-4368-a5b3-a9388f47dc4e.png">
<img width="752" alt="image (5)" src="https://user-images.githubusercontent.com/1048212/192226699-ac96f06b-befe-4936-ad6f-fd2cfaf71796.png">

then I usually change the query to fit a specific condition.
This is just a quick way to generate a script.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
