### ISSUE TITLE
Allow to clear or drop all selected collections

### ISSUE THREAD

**Issue by mogarick** [mingo-app/mingo#489]
In Studio 3T Free Edition I can select one or more collections and then choose to drop or clear all collections. I don't see this feature on Mingo. It's pretty useful in app development stage.

Although I'm a Mingo paying subscriber I'd expect this feature to be present from the Mingo Free version in order it to be on par with the Studio 3T Free edition.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/4414145/192406114-9f660d8b-c59c-4e1f-94e4-ffc592e355c0.png">

**Comment by tothradoslav** [comment]
I understand it's a bit "hidden" but you can actually do this in Mingo, too.

In the sidebar, right click on the the database and select "Collections Stats". A list of collections appears and you can select multiple or all and drop or truncate the selected ones.

Any ideas on how to implement this more clearly in Mingo's UI?

Thank you!

**Comment by tothradoslav** [comment]
A possible solution: 
- add checkboxes instead of dots by each collection in sidebar
- this very edge case and possible to do another way

**Comment by tothradoslav** [comment]
<img width="222" alt="Screenshot 2022-11-15 at 11 32 35" src="https://user-images.githubusercontent.com/3465808/202032696-7f9ded0a-cf65-40fc-a215-072d0b88039a.png">

**Comment by tothradoslav** [comment]
For now, we will keep this functionality as is, which means it's accessible from "List and manage collections".
