### ISSUE TITLE
contrast of _id values for documents in dark mode

### ISSUE THREAD

**Issue by jamesholcomb** [mingo-app/mingo#490]
![image](https://user-images.githubusercontent.com/362729/193027350-dbad2a54-277c-4475-8361-c737474a972c.png)

Can it be increased or perhaps changed to another color?

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
