### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'find')

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#492]
Just upgraded to 1.9.1 (windows) and now no localhost connection is working, query doesn't seem to matter.

Localhost is not working. Production does work.

![image](https://user-images.githubusercontent.com/3471363/193637007-fd9917e3-3f9a-42c8-ae2b-474e665572c9.png)

![image](https://user-images.githubusercontent.com/3471363/193636973-475097f4-3277-473d-9577-62293baf24d8.png)

![image](https://user-images.githubusercontent.com/3471363/193637031-8d3b5d1c-6b1e-4f99-973d-ac68be9cce80.png)

Connection seems to be okay:
![image](https://user-images.githubusercontent.com/3471363/193637216-1e378859-a45b-4ae8-97af-d6bca2c8a698.png)

Downgrading to 1.9.0 makes localhost work again.

**Comment by Christilut** [comment]
Had a Windows reinstall today, installed Mingo 1.9.1 but same problem. 

I would say this is a pretty serious bug if new users are getting this too.

**Comment by lynchem** [comment]
I had this too @Christilut  and suspected it might be something to do with the relations as it only happened in one collection. As only one of mine had an issue I was able to open the 'all relations' view and remove them. It loaded as normal then. This 'all reations' view should really be accessible from somewhere in the menu. Bit dissapointed to see how long this issue went without comment from the devs.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
