### ISSUE TITLE
Import a document date and _id issue

### ISSUE THREAD

**Issue by csonmez** [mingo-app/mingo#493]
When import a document, date and _id are string value.

**Comment by tothradoslav** [comment]
Hi, could you provide more information? The way import works is that you create your own "Document definition" object, which should parse data the way you need them to be stored in the DB

So in case of a date, for example, you could:

```
{
  date: dayjs(row[0]).toDate()
}
```

**Comment by csonmez** [comment]
Hi. When I export a document from mongodb and import it in mingo, I want to get the same view without updating if possible.
