### ISSUE TITLE
Displaying all available fiels in a collection

### ISSUE THREAD

**Issue by jamesholcomb** [mingo-app/mingo#494]
When opening a collection from the sidebar db explorer (left click on collection name), the new view does not render all available fields from the result set.  I understand I can do "+ Column" but why not show them all?

EDIT: The missing fields are all ObjectIds.  Perhaps there could be an option to override this behavior?

**Comment by tothradoslav** [comment]
When you click on +Column, the first option is to add "Top-level fields (all)" which will do exactly what you need. Mingo will then remember this for this particular collection.

**Comment by jamesholcomb** [comment]
I would suggest a global setting (default=true in my opinion) that determines if ObjectIds are rendered for collections.  New users and users coming from other GUI tools are going to be predisposed to this behavior.

**Comment by tothradoslav** [comment]
We have changed this behavior to show ObjectIds, too, by default. Anyone can easily remove them if not needed, so we didn't see a point of making this an option in Preferences. Thanks for the feedback!

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
