### ISSUE TITLE
Inline date edit changes hour from 24 to 12 format

### ISSUE THREAD

**Issue by Icaruk** [mingo-app/mingo#498]
1. Initial date:
`2022-10-27 14:00:00 +02:00` (1h ago)

2. Double click field to edit.

3. The date changes to:
`2022-10-27 2:00:00 +02:00` (13h ago)

I you don't save, nothing bad happens, but you could edit just the day without noticing the automatic hour change.

![](https://i.gyazo.com/a26d9af1f1167f82f2d1b72eaf41274f.gif)

**Comment by tothradoslav** [comment]
This has been corrected. We are now using the ISO date format without the datetime input type.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
