### ISSUE TITLE
Dates not showing in Aggregation results

### ISSUE THREAD

**Issue by lynchem** [mingo-app/mingo#499]
When looking at the results of an aggregation it seems like Dates won't show. Although after exporting they are correctly included to purely an issue displaying them. 

The sample results of the last stage show them correclty.
![image](https://user-images.githubusercontent.com/12910319/198681733-ac35aa46-6439-4d7e-a0b8-eb1b7dc41ab7.png)

But then the final results show undefined 

![image](https://user-images.githubusercontent.com/12910319/198681887-1ad4eb6c-c72f-4382-a460-67f54d822e01.png)

**Comment by tothradoslav** [comment]
This seems to have been corrected while we refactored some deeper parts of Mingo. Thank you! Ready for next release.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
