### ISSUE TITLE
Tab switching shortcuts

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#50]
For ease of use and to match the interaction of other tabbed application these shortcuts would be great:
- `cmd+0` up to `cmd+8` to switch to the tab with that index
- `cmd+9`to switch to the last tab
- `cmd+left`: one tab left
- `cmd+right`: one tab right

Bonus:
- `cmd+shift+left` and `right` to move tabs

Change `cmd` to `ctrl` for windows

**Comment by tothradoslav** [comment]
Thanks for the feedback, this has been added in the latest version released.
