### ISSUE TITLE
Feature Request: Export aggregation to CSV

### ISSUE THREAD

**Issue by lynchem** [mingo-app/mingo#500]
It would be nice to export the results of an aggregation to csv directly rather than to JSON and then turning that into CSV.

**Comment by tothradoslav** [comment]
This will surely be avaible in next release.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
