### ISSUE TITLE
Disable auto-focus on query input

### ISSUE THREAD

**Issue by fers4t** [mingo-app/mingo#501]
I can't navigate between tabs easily because Mingo auto-focusing on query input on each tab. I don't know if others use query input so much but I don't. So every time I must click outside of query input and then I am able to navigate with CMD+num shortcuts.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/58539842/199833801-abb5516e-8fc2-4690-8faf-a5924ae9aa6a.png">

**Comment by tothradoslav** [comment]
Hi, we made this optional, changable in Preferences.

**Comment by tothradoslav** [comment]
A new Mingo release candidate is available for download (v1.10.0-rc2). This issue has been fixed in this release. Please check it out and let us know if it works as expected. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.10.0-rc2
