### ISSUE TITLE
The export function is not easy to use, especially when encountering Chinese or other encodings

### ISSUE THREAD

**Issue by zhikaichen123** [mingo-app/mingo#502]
If the content exists in Chinese or other encodings, there will be problems with the format and garbled characters.

eggs:
xxx 纾佺洏鍗犵敤锛?1.16 Gb,瑙﹀彂鍒犻櫎浜嬩欢	"system"	"Delete"	"Sun Oct 09 2022 20:40:11 GMT+0800 (涓浗鏍囧噯鏃堕棿)"

**Comment by tothradoslav** [comment]
Thanks, could you send me an example document (I won't be able to read it anyway :) ) so that I can test it on real data?
