### ISSUE TITLE
missing horizontal scroll bar in Documents

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#503]
![ROr0Xy6etwtt9Lq2u8aue7Ia2FsRLfvx](https://user-images.githubusercontent.com/1048212/203552172-c789f151-7254-4d7b-80cd-acf45a02cce7.png)

**Comment by tothradoslav** [comment]
With the current html dom structure, this is impossible to achieve. Among other issues, pagination is present at the bottom below the list, which is not scrolled sideways...
