### ISSUE TITLE
Version 1.10.0 has several bugs

### ISSUE THREAD

**Issue by leonelvalentini** [mingo-app/mingo#505]
- In view mode, it shows the json wrong
- In edition mode, it shows the json wrong and with errors
- Do not copy the ObjectID

**Comment by tothradoslav** [comment]
Could you pls be more specific? Screenshots or info on what the value is and ehat is expected to see. 

Will check the copying issue

**Comment by leonelvalentini** [comment]
View mode:
![View](https://user-images.githubusercontent.com/199661/204340143-d813db1a-3d18-4302-8eb7-5a7e58d4c7c8.png)
Copy ObjectID
![Copy_value_1](https://user-images.githubusercontent.com/199661/204340161-c9a03d87-15ad-4908-9283-1676bbf4a8c8.png)
![Copy_value_2](https://user-images.githubusercontent.com/199661/204340167-f4b406ff-37f8-4303-9dd6-c512ed919ecd.png)

**Comment by arkraft** [comment]
I have the same error when I try to copy an ObjectId. Before the update, it worked fine. After the update it only copies the brackets and the result looks like this:

```
{

}
```

**Comment by tothradoslav** [comment]
Thanks for this, corrected. Will be available in next release.

**Comment by tothradoslav** [comment]
Hi, this should be fixed in the latest release: 
https://github.com/mingo-app/mingo/releases
