### ISSUE TITLE
Compare n Sync not working no 1.10

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#509]
after hitting "Compare selected collections" I'm getting the "An error occurred" message

**Comment by tothradoslav** [comment]
I can't reproduce this error, can you please provide more details?

**Comment by Icaruk** [comment]
Same here, to "fix" it I must delete the collection then sync it again.

![image](https://user-images.githubusercontent.com/10779469/217593918-e46f1b1c-9921-45c6-9425-c1a1242e34dd.png)
