### ISSUE TITLE
The errors "Invalid selector" and "Error in selector" are not informative

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#51]
There is an informative error that is being hidden here. It would be best to show it somehow, perhaps by clicking on the error toast but even better just somewhere below the query (you don't have results anyway so 90% of the screen is available for this interaction at this point)

**Comment by tothradoslav** [comment]
New version released and this has been implemented. It will need further improvements but it now shows more info on what the error actually is. Thanks for the feedback.

**Comment by GriffinSauce** [comment]
Thanks @tothradoslav, will try it out! 

Do you like these single issues for each problem/improvement or would you like it more bundled? I love the idea and execution of this app so I'll probably have more feedback :)
