### ISSUE TITLE
[feature request] Add search component instead only select

### ISSUE THREAD

**Issue by Icaruk** [mingo-app/mingo#510]
- Left side panel: each database has a dropdown with all collections, it would be cool if a search field could filter collections.
- Aggregator: "+ Add stage" button list all stages available, it would be cool another search field.

I can add screenshots if needed.

**Comment by tothradoslav** [comment]
Hi, I added the "filter" option to the aggregator "add stage" buttons. 

Regarding the collections, which "dropdown" do you mean in left side panel? BTW, to open quickly any collection, have you tried our Finder? When you press CMD+T (CTRL+T) to open a new tab, finder is shown. Then just start typing the collection name and use arrow keys to select collection / view, then enter. Very useful. 

Please let me know. Thanks!

**Comment by Icaruk** [comment]
@tothradoslav Thanks for adding that to the aggregator!

Imagine the following situation...

My (example) collections are:
- userStuff
- userFaces
- userTokens
- userForgotRequests
- userStuff2
- ...

I'm working all the time with `user*` collection but there are too many collections to open in tabs at the same time.
On the other side writing "user..." over and over is unproductive.

So having a "group" of filtered collections to work and switch fast without cluttering my tabs could be cool.
Maybe with a big screen the problem is gone, my each developer has a different setup.

New idea: now clicking a collection opens it in a new tab, what about ctrl + click replaces current tab?

**Comment by tothradoslav** [comment]
Thanks for this, thinking of your usecase. A few ideas that might help you:

1. mingo supports multiple windows, so you could have a window for the users* collections and another set of tabs in a new window. 
2. in the sidebar, you can "pin" collections, which will be kept visible even when you collapse the database. Just right-click on a collection in the left bar and pin it. 
3. ctrl+click to replace current tab: which version of mingo are you using? 1.10.0? Currently, click on a collection in the sidebar opens a new tab unless that collection is already opened in one of the tabs. To change this behaviour, go to preferences. 
4. you can "rename" a tab, which will also lock it and prevent accidentally closing it. Will prompt before closing such a named tab. 

Let me know if any of these things helped you. Than we can continue to search for a solution for you (and others, too) :)

Thanks!

**Comment by Icaruk** [comment]
> 1. mingo supports multiple windows, so you could have a window for the users* collections and another set of tabs in a new window.

That could be one solution, thanks.

> 2\. in the sidebar, you can "pin" collections, which will be kept visible even when you collapse the database. Just right-click on a collection in the left bar and pin it.

Yeah, the problem is that each few days of work I change the "target collections", so I must unpin and pin the new ones.

> 3\. ctrl+click to replace current tab: which version of mingo are you using? 1.10.0? Currently, click on a collection in the sidebar opens a new tab unless that collection is already opened in one of the tabs. To change this behaviour, go to preferences.

Latest version: 1.10.0
I changed that option on preferences, thanks!

> 4\. you can "rename" a tab, which will also lock it and prevent accidentally closing it. Will prompt before closing such a named tab.

I didn't know that, thanks!

**Comment by tothradoslav** [comment]
Great, we will still consider the filter in side bar, as you originally mentioned.

**Comment by tothradoslav** [comment]
Another option you may use is that the Finder (CMD+T or CTRL+T) remembers the last typed text. So if you type "user", select a collection (using arrow keys) and then open the finder again, the "user" is still there and the collections are filtered.

Considering all the current options you could use in mingo, we desided not to add the filter into the side bar. 

If you have futher arguments, please let us know :)
