### ISSUE TITLE
toggle on a boolean flag changes the type to a string

### ISSUE THREAD

**Issue by arkraft** [mingo-app/mingo#511]
When toggling a boolean flag, the type of the attribute is changes to a string

https://user-images.githubusercontent.com/7426376/205096392-249befaa-5c72-4fd6-9978-08aa0ffae561.mov

**Comment by tothradoslav** [comment]
Yes, thank you, we have noticed this and corrected. Available in next release.

**Comment by arkraft** [comment]
This is fixed in the new version, thanks!
