### ISSUE TITLE
Row number and collection names are joined together | Data Relations

### ISSUE THREAD

**Issue by suvradip** [mingo-app/mingo#512]
Client version: 1.10.0

Row number and collection names are joined together when the row number is greater than 99. I've attached an image file for reference. 

<img width="818" alt="Screenshot 2022-12-01 at 9 52 57 PM" src="https://user-images.githubusercontent.com/13198773/205105848-9ccda4b6-a6d9-4253-aff3-fde66d821db0.png">

**Comment by tothradoslav** [comment]
Thank you, corrected. In next release.

**Comment by tothradoslav** [comment]
Hi, this should be fixed in the latest release: 
https://github.com/mingo-app/mingo/releases
