### ISSUE TITLE
Can't delete unnamed connection

### ISSUE THREAD

**Issue by Icaruk** [mingo-app/mingo#513]
![image](https://user-images.githubusercontent.com/10779469/205251809-2046d138-0274-454e-9769-94a41b4a9a0d.png)

The only way is by adding `mongodb://localhost:27017` as URI and any name.

**Comment by tothradoslav** [comment]
wow, this is an interesting situation. How did you create an unnamed collection? Will look into this.

**Comment by Icaruk** [comment]
I'm sorry I can't remember, I was just fooling arround with projects.
My suggestion is `collectionName === "" || collectionName === undefined` the confirmation string can be empty and "Delete connection" button is always enabled.

**Comment by tothradoslav** [comment]
Hi, this should be fixed in the latest release: 
https://github.com/mingo-app/mingo/releases
