### ISSUE TITLE
Issue while change widths of node JS script

### ISSUE THREAD

**Issue by joca-immersa** [mingo-app/mingo#516]
**Describe the bug**
When I change the widths of the header dind't affect the width of the body table

**Screenshots**

https://user-images.githubusercontent.com/106625453/205352623-86d650f8-d423-46ee-8116-18cf0f42e8fc.mov

**Desktop (please complete the following information):**
 - Mingo version: 1.10.0
 - OS: Mac Os Ventura

**Comment by tothradoslav** [comment]
Yep, thank you, I can confirm this is an issue and will fix it.

**Comment by joca-immersa** [comment]
Thanks!

**Comment by tothradoslav** [comment]
Hi, this should be fixed in the latest release: 
https://github.com/mingo-app/mingo/releases
