### ISSUE TITLE
Adding a new boolean field fails

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#518]
**Describe the bug**
If I add a new field with a Boolean type, it gets the value "new value" and the update fails. When I select the option to edit the field, it looks like a Boolean field but the update fails if I try to save it.

**Desktop (please complete the following information):**
 - Mingo version: 1.10.1
 - OS: macOS 13.1

**Comment by tothradoslav** [comment]
This has been corrected in the current RC, please test it and let us know if the issue has been resolved. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.11.0-rc2

**Comment by brianlukoff** [comment]
Works now - thanks!
