### ISSUE TITLE
Some times when use restore function, the destination list is just disabled , i can not choose them

### ISSUE THREAD

**Issue by jasstionzyf** [mingo-app/mingo#519]
**Describe the bug**
_A clear and concise description of what the bug is and how to reproduce it._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Desktop (please complete the following information):**
 - Mingo version:
 - OS:

**Comment by tothradoslav** [comment]
Hi, thanks for this. I will need more information please. Ideally a way to reproduce the error.
