### ISSUE TITLE
Creating a new index: background option is missing

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#52]
Love the interface for creating an index! The mix of WYSIWYG and code is really cool and helpful. :)

That said: the option "background: true" is missing in the options buttons on the left.

Extra idea: the link between left<>right panes might be even clearer if the UI and code inputs are horizontally aligned:

```
[Index name]

[Keys]        [Keys (code)]

[Options]     [Options (code)]
```

Downside is that this makes the whole thing taller so it might be worth testing that layout with a lot of fields...

Cheers!

**Comment by tothradoslav** [comment]
Thanks for the ideas.

We'll add the background option.

Regarding the horizontal alignment, maybe removing the "name" input and just keeping it in the options as a predefined property would be sufficient, like this:

`{
name: ""
}`

How important is index name? Is it used often? We could use the saved space for the horizontal alignment.

**Comment by GriffinSauce** [comment]
Personally I do use it but I can't speak for the whole ecosystem.

Putting it in the options works but it might imply that it is required. If most people don't use it that could introduce some unneeded friction.

**Comment by tothradoslav** [comment]
A new version v0.9.13 has been released and this has been improved.

Regarding the "background" option, I just found out that the reason for missing is that it has been deprecated, so we skipped it.

Thanks for your helpfull feedback :)

**Comment by GriffinSauce** [comment]
Ah I missed that deprecation, makes sense.
Looks like you also updated the homepage, looks great!
