### ISSUE TITLE
Change property as boolean shows old string

### ISSUE THREAD

**Issue by devjoca** [mingo-app/mingo#520]
**Describe the bug**
Create a sibling property, then change it to boolean, and shows the old string instead of the boolean value

**Screenshots**

**Desktop (please complete the following information):**
 - Mingo version: 1.10.1
 - OS: Mac OS Ventura

https://user-images.githubusercontent.com/5117647/208975787-98b231a6-88ad-4598-ab02-9d3af8b2c8c8.mov

**Comment by tothradoslav** [comment]
Thank you. This is already corrected. Will be available in upcoming version.

**Comment by tothradoslav** [comment]
This has been corrected in the current RC, please test it and let us know if the issue has been resolved. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.11.0-rc2

**Comment by devjoca** [comment]
It is fixed now, thanks!

**Comment by tothradoslav** [comment]
reopening to keep track of changes for release notes :)
