### ISSUE TITLE
Really Bad use experience appears

### ISSUE THREAD

**Issue by jasstionzyf** [mingo-app/mingo#522]
**Describe the bug**
_A clear and concise description of what the bug is and how to reproduce it._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Desktop (please complete the following information):**
 - Mingo version:
 - OS:

1:  Keep force me to input one time password when login.
2: Customer problem never response.

Currently i am a little regret to use your product.
What happend with your company?

**Comment by tothradoslav** [comment]
Hi, sorry for my late response. We haven't had anyone else complain about your issue and we personally didn't experience. Could you please send us an email with your machine ID (found in the app in main menu under Mingo). I will take a look at your status. Thank you!

**Comment by jasstionzyf** [comment]
@tothradoslav   19914593f58354742bc5c1f0b45851e48156e628a65f32b6910dd183dd4f824c88f15a214494bf6602e2785334036090974e7cfe7cfa794acf8beb9efd747d95

above is machine id


my email:  onmygoing@163.com

**Comment by jasstionzyf** [comment]
also:   Your license expires on 2023-01-07.
this tips alwayes keep change 
but i actually purchase your product at middle of this year
crazy me

**Comment by tothradoslav** [comment]
This is really weird. I will reset your machine completely and you should be prompted for the email and onetime password once again. It will also ask for your license key again. I will email it to you.

**Comment by jasstionzyf** [comment]
@tothradoslav  yes it indeed ask me login again, but not ask for my license key,  also the key you give me is same as my original

**Comment by jasstionzyf** [comment]
still not work?, keep me asking one time password.....

**Comment by tothradoslav** [comment]
what operating system are you using? I honestly can't figure this one out. I'm going to try to login and use your license key on my computer, using your email addres, to see if this will happen with my computer, too.

**Comment by jasstionzyf** [comment]
I use window11,  also i use astrill vpn to use google ...  for i am in china.
Maybe has something related with network?

**Comment by tothradoslav** [comment]
This will almost definitely have something to do with network, because when I tested it with "network unavailable", it showed the signs you mentioned. Make sure all *.mingo.io requests are permitted through your network (firewall, vpn, ....)

It also means we will correct the bad behavior when network is not available. You still have to make sure network is available, otherwise mingo won't work properly.

**Comment by jasstionzyf** [comment]
But what is strange is that network is no problem and also  other apps work well, like evernote....

**Comment by tothradoslav** [comment]
Did you not have to allow these other apps in the VPN?

**Comment by jasstionzyf** [comment]
vpn is global , all app through vpn  if i switch vpn on , but for some reason , i also switch the vpn down some time . so network model is keep change
