### ISSUE TITLE
Renaming a field does not work.

### ISSUE THREAD

**Issue by laakal** [mingo-app/mingo#523]
https://user-images.githubusercontent.com/9221304/210244906-5316d0f0-9bcb-45ee-a374-f89b21177fa3.mov

**Comment by tothradoslav** [comment]
Thank you for this. Renaming doesn't work on nested array fields, such as in your video. There are ways to get this done, but we will have to ask the user, whether he wants to rename that field in all subdocuments or jus the one clicked. 

In your case, did you want to rename it in all subdocuments?

**Comment by laakal** [comment]
Thanks for your answer. It would be nice to be able to rename in all array subdocuments.

**Comment by tothradoslav** [comment]
We have decided not to implement this feature. Reasons:
- this is not supported by mongodb either
- even if we created a special script to do this, it would never be 100% safe due to some complexities we encountered
