### ISSUE TITLE
UUID is displayed as null

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#524]
<img width="947" alt="db9238dc-5394-40ca-b40a-67869de81b8a" src="https://user-images.githubusercontent.com/1048212/210781777-1f37f1d6-766c-401e-b3c7-7e1cf06e1fac.png">
UUID's in compass
<img width="758" alt="5b0b90de-ffb8-4143-8687-6e53121ded21" src="https://user-images.githubusercontent.com/1048212/210781751-a52562f9-faa6-46ed-9e80-e13db1932f66.png">

**Comment by tothradoslav** [comment]
This has been corrected in the current RC, please test it and let us know if the issue has been resolved. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.11.0-rc2
