### ISSUE TITLE
Test connection successful but the database does not load.

### ISSUE THREAD

**Issue by rafaelmauricioaraujo** [mingo-app/mingo#525]
I'm using the Mingo for a while, but after remove my local database and trying to connect again I'm facing this problem.

The mingo connection works and show success message when try to connect to my local database, but dont show any collection from database. 

![Captura de tela_20230110_140607](https://user-images.githubusercontent.com/38811953/211617777-235c611c-a0f2-4bfc-80c9-a58228cab272.png)

![Captura de tela_20230110_140629](https://user-images.githubusercontent.com/38811953/211617857-3858d462-8066-488e-b2df-00d226d1b1ed.png)

![Captura de tela_20230110_140719](https://user-images.githubusercontent.com/38811953/211617882-2eda98d9-df98-48f8-856d-c3187e57c547.png)

![Captura de tela_20230110_140743](https://user-images.githubusercontent.com/38811953/211617893-f30d224c-7b33-41ad-8cc4-f355763eb942.png)

But the database do have collection, 

![image](https://user-images.githubusercontent.com/38811953/211619577-6af3fcd8-f85b-44cb-adc7-aa482e9e5a3b.png)

![image](https://user-images.githubusercontent.com/38811953/211620080-506cd5ad-a0ab-49e3-93a7-8ea0eacae509.png)

 - Mingo version: 1.10.1
 - OS: Microsoft Windows 11 Home 22H2

**Comment by tothradoslav** [comment]
Thank you, I'l look into this and get back to you!

**Comment by rafaelmauricioaraujo** [comment]
Just an update.
I tried changing my computer's name and worked.
Don't me ask why. 
I saw in the mongodb log collections that have some items with my computer's name and I tried changing the name.
I even dont know if this was the thing that fixed my issue you guys are the experts you may know.

**Comment by tothradoslav** [comment]
Wow, this is interesting and I don't feel like an expert after this at all :(

I have honestly no idea what happened. 

BTW, have you tried the latest version? 1.11
