### ISSUE TITLE
Bad formatting Chart Widget grouping by year week

### ISSUE THREAD

**Issue by javigines** [mingo-app/mingo#527]
**Describe the bug**
The aggregation done on the Chart Widget editor is not correct when it is done grouping by year week. This is because, on the aggregation $dateToString format, the code used to represent the year is %Y and should be %G. If not the day one of January it appears as 2023 when in ISO weeks it is really from last year's weeks. Currently, the dates from 2023-01-01 appears as 2023-52.

**Screenshots**
![image](https://user-images.githubusercontent.com/15628852/212966091-0934334d-2419-46aa-95d6-2bb04216f53a.png)

**Desktop (please complete the following information):**
 - Mingo version: 1.10.0
 - OS: Windows/Mac

**Comment by tothradoslav** [comment]
Thanks, corrected. Due to the way these widgets work, you will have to edit them and save with new grouping.

**Comment by tothradoslav** [comment]
This has been corrected in the current RC, please test it and let us know if the issue has been resolved. Thank you!

https://github.com/mingo-app/mingo/releases/tag/v1.11.0-rc2
