### ISSUE TITLE
Mingo .deb package category

### ISSUE THREAD

**Issue by VladimirMikulic** [mingo-app/mingo#529]
**Describe the bug**

![Screenshot_20230118_010941](https://user-images.githubusercontent.com/35997844/213046698-8a9381ab-ac01-4ac1-be7a-67091ce79775.png)

Mingo currently has `Database;` as a value for `Categories` field.
However, `Database` category is actually [a secondary category](https://askubuntu.com/questions/674403/when-creating-a-desktop-file-what-are-valid-categories) and isn't defined on most Linux systems.
This results in Mingo being placed in "Lost & Found" category.

It would be better to add `Development;` and `Utility;` like VS Code does.

**Screenshots**

![Screenshot_20230118_011255](https://user-images.githubusercontent.com/35997844/213046612-042c0da8-08e7-4f36-8430-1f08f1809102.png)

**Desktop (please complete the following information):**
 - Mingo version: 1.10.1
 - OS: Linux (Ubuntu)

Thanks!

**Comment by tothradoslav** [comment]
Thank you, corrected!

**Comment by VladimirMikulic** [comment]
Much appreciated as always!

**Comment by VladimirMikulic** [comment]
@tothradoslav issue resolved with 1.11-rc2!

**Comment by tothradoslav** [comment]
Great, thanks for letting us know in first place!
