### ISSUE TITLE
ObjectID type is not set when updating a field + too easy to unset

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#53]
Reproduce the bug:
- Double click an ObjectID field, confirm editing
- The `type` selector is empty

Additional problem: When the type selector is empty, saving will unset the field (regardless of a value in the second input field). This might be intentional or a bug too, that's unclear but it seems safer to just block submit when the selector is empty.

**Comment by tothradoslav** [comment]
I corrected this, thank you. Please have a look.
