### ISSUE TITLE
Can no longer launch Mingo

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#530]
When trying to launch Mingo I now get a 502 error:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/518013/213825433-ff2b8d86-35e1-4f33-85ae-2f58cade51ae.png">

Is there a way that Mingo could have some kind of grace period so that the app does not break if Mingo's servers are down?

**Comment by tothradoslav** [comment]
Thanks for this. Sure, we have a grace period of 24hours, except for validating your email (which is a one-timer upon first run). This is just a "window" showing the fact that there's a problem. We will improve this, too. This is to make sure people realize Mingo does not have access to internet in cases such as VPN, firewall, etc..

**Comment by tothradoslav** [comment]
Hi, this has been included in the latest release v1.12.1:

https://github.com/mingo-app/mingo/releases/tag/v1.12.1

I'm closing this issue, but please let us know if it worked right.
