### ISSUE TITLE
The app is unable to function after it has been brought back online.

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#531]
**Describe the bug**
- go offline
- go online 
- but the app is still unusable

documents:
<img width="1225" alt="Screenshot 2023-01-25 at 08 11 10" src="https://user-images.githubusercontent.com/1048212/214501899-4e9d9f39-dd01-4132-8697-8076edaba4a3.png">

it looks like I dont have a valid license, but I do
<img width="1226" alt="Screenshot 2023-01-25 at 08 11 23" src="https://user-images.githubusercontent.com/1048212/214501913-17123ead-f1d0-4c1c-ba64-35099635d768.png">

**Desktop (please complete the following information):**
 - Mingo version: 1.10
 - OS: mac

**Comment by tothradoslav** [comment]
How long have you been offline? I tested going off and back online and worked fine. 

But I made mingo reconnect all active connections after going back online, let's see if it helps.

**Comment by sagrawal31** [comment]
This still happens to us with the latest version `1.12.2`. When we go back to the already opened window after a couple of hours (when the Mac lid was shut), and open a new collection page, it says that you are not connected.

**Comment by sagrawal31** [comment]
<img width="1202" alt="image" src="https://github.com/mingo-app/mingo/assets/1804514/61c702a1-75f4-4dcf-9566-b9f21e7830c1">

**Comment by tothradoslav** [comment]
This issue is difficult to reproduce and track down, but we have made further improvements in the next release, probably out tomorrow. Will let you know. Thanks!

**Comment by sagrawal31** [comment]
Thank you, @tothradoslav, for working on this. I'll test this once new version is out.

**Comment by tothradoslav** [comment]
Could you try this new version?

https://github.com/mingo-app/mingo/releases/tag/v1.13.1

**Comment by sagrawal31** [comment]
Thanks, @tothradoslav, for the update. I have updated it and will see if this happens again in the coming few days.

**Comment by tothradoslav** [comment]
Great, definitely let me know please. Thanks.

**Comment by sagrawal31** [comment]
Though the frequency of this issue got reduced drastically, this happened to me today again @tothradoslav when my Mac restarted after the OS upgrade.
![image](https://github.com/mingo-app/mingo/assets/1804514/d831f8d3-526b-4f78-ba51-e0899583f502)
