### ISSUE TITLE
Array indentation error

### ISSUE THREAD

**Issue by leonelvalentini** [mingo-app/mingo#532]
**Describe the bug**
Document view and editing mode.
Please correct the indentation in the arrays as it is very annoying to display the json

**Screenshots**
![MINGO](https://user-images.githubusercontent.com/199661/214647391-8e590cf4-7e9c-45b4-a54f-4a3909c9cdf7.png)

**Desktop:**
 - Mingo version: 1.10.1
 - OS: macOS Monterey

**Comment by tothradoslav** [comment]
Thanks, correct, will be in next release. Please keep open

**Comment by leonelvalentini** [comment]
The problem persists in version 1.11.0

**Comment by tothradoslav** [comment]
yes, sorry, this should be in the next release, currently in RC 1.12.0-rc1.

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.11.1
