### ISSUE TITLE
Saved pipelines disappear 

### ISSUE THREAD

**Issue by ionescurares** [mingo-app/mingo#534]
**Describe the bug**
Very annoyingly, saved pipelines from the aggregator just keep disappearing. I am not seeing any clear pattern buts its the 3rd time in the past months when this happened. First I thought it might be a mistake - but it is becoming annoying and time consuming to rewrite all the aggregations again 

**Screenshots**
![image](https://user-images.githubusercontent.com/39592181/215044001-cf0f5351-6f81-4fb2-a8d8-e12ad4700ef9.png)

**Desktop (please complete the following information):**
 - Mingo version: 1.10.1
 - OS: Windows 11

**Comment by tothradoslav** [comment]
Thanks for letting us know. Did you notice any other store info being lost? Such as saved queried (in Documents) or NodeShell scripts?

**Comment by tothradoslav** [comment]
Also, have you been making any changes to your connection? Collections have internal IDs in Mingo and if you create a new connection to the same database, those collections will have new IDs. Since pipelines are stored via IDs, these won't be able to show for the new connection.

**Comment by tothradoslav** [comment]
In fact, I have just changed this behaviour, so that collection iDs in Mingo are not "random", but real the UUID of each collection from the database.

This does not necessarily solve your issue, but removes one of the possible causes.

**Comment by tothradoslav** [comment]
One more question: Are you using Mingo in multiple separate windows?

**Comment by ionescurares** [comment]
Hey @tothradoslav 

> Thanks for letting us know. Did you notice any other store info being lost? Such as saved queried (in Documents) or NodeShell scripts?

Yes, with saved queries

> Also, have you been making any changes to your connection? Collections have internal IDs in Mingo and if you create a new connection to the same database, those collections will have new IDs. Since pipelines are stored via IDs, these won't be able to show for the new connection.

Not making any connection changes at all.

> Are you using Mingo in multiple separate windows?

Yes, I do have multiple instances open from time to time

**Comment by tothradoslav** [comment]
Thanks. Using multiple windows will probably be the reason. We found a possible cause, but removing it will require making serious changes so I can't promise it will be done "in a few days". :(

We will try to solve it asap, though. Until then, could you try not using multiple windows to see if this happens? 

Sorry for this...

**Comment by ionescurares** [comment]
Will have to try. We have our whole engineering team using mingo and it's a bummer :(

**Comment by tothradoslav** [comment]
are you still encoutering this issue?

**Comment by ionescurares** [comment]
@tothradoslav haven't seen this replicating anymore

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
