### ISSUE TITLE
Changing from a project/connection that won't connect to a project that will causes an infinite spinner until I "Reset active connections" under the "Connections" menu

### ISSUE THREAD

**Issue by mrjoesm** [mingo-app/mingo#535]
**Describe the bug**
1. Load up Mingo, automatically try to load a database that I can no longer access (in my case this is because I hit various databases via an SSH bastion server and only use this where necessary
1. Change to localhost
1. infinitely spin
1. hit connections > reset active connections
1. profit

**Desktop (please complete the following information):**
 - Mingo version: 1.10.1
 - OS: Windows

**Comment by mrjoesm** [comment]
Also, I left it spinning for a while when writing this and then I had to close and reopen mingo for it to work. It wasn't enough to just "reset active connections"

**Comment by tothradoslav** [comment]
Thanks for this, looking into it now.

**Comment by tothradoslav** [comment]
I think I identified the problem and solved it. This should be in the next RC, will let you know when it's out. Thank you!

**Comment by tothradoslav** [comment]
Please seee if it works fine now: https://github.com/mingo-app/mingo/releases/tag/v1.11.1
