### ISSUE TITLE
Adopted Arch Linux package

### ISSUE THREAD

**Issue by ghost** [mingo-app/mingo#536]
As of about 30 minutes ago, I have adopted the existing AUR package for mingo:

https://aur.archlinux.org/packages/mingo-bin

As a recommendation: please provide builds within a .tar.gz format for easier packaging, this would be highly useful!

Any issues with the package please make a comment on the aur package or submit an issue on the git repository here: https://onedev.polarian.dev/aur/mingo-bin

I will add an arch wiki page for mingo tomorrow, as one does not seem to exist https://wiki.archlinux.org/index.php?search=Mingo&title=Special%3ASearch&go=Go

If all else fails, please contact me by email: polarian@polarian.dev

Take care,
Polarian

**Comment by ghost** [comment]
Update: ArchWiki page has been added for Mingo:

https://wiki.archlinux.org/title/Mingo

This is currently just the base, more can be added in the future.

**Comment by tothradoslav** [comment]
Hi, thank you for this. 

Besides providing the tar.gz builds, what exactly is expected from us? To be honest, I have almost zero experience with linux builds and the environment in general.

**Comment by ghost** [comment]
@tothradoslav It was more a "heads up your AUR package is now maintained again", you do not need to worry about it, both the AUR package and ArchWiki page is maintained by me.

Although them tar.gz builds would be real nice, and a checksum will be nice too :P (preferably .sha256)

**Comment by ghost** [comment]
You only distribute a .deb which is currently what the AUR package has to extract and reformat into the Arch Linux format, hence why a tar.gz would be nice :)

**Comment by tothradoslav** [comment]
There's a new RC available here, please check it out

https://github.com/mingo-app/mingo/releases/tag/v1.12.0-rc1

The tar.gz should be available in the current latest official release, please check it out: 

https://github.com/mingo-app/mingo/releases/tag/v1.11.0

Thank you!

**Comment by ghost** [comment]
@tothradoslav sorry for the stupid question, but what exactly does RC stand for (I have never actually figured this out).

Also thanks for support .tar.gz, I will add an issue to the AUR package repository to transition over to .tar.gz

**Comment by ghost** [comment]
See https://onedev.polarian.dev/polarrepo/mingo-bin/~issues/1 for more information

**Comment by ghost** [comment]
Thanks for the tar.gz, the package has been updated to version 1.11.0 and also now uses the .tar.gz which allows for more flexibility

**Comment by tothradoslav** [comment]
Sorry for my late reply. RC stands for Release Candidate, which is a release version for those who like to test things out first. Once there are no issues, the RC is releaseed as a regular version. Thank you!

**Comment by ghost** [comment]
Thanks for the clarification :)
