### ISSUE TITLE
magic search: issue with ID

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#537]
**Describe the bug**
When I submit this query:
<img width="483" alt="Screenshot 2023-02-01 at 12 54 38" src="https://user-images.githubusercontent.com/1048212/216035741-3509043f-fc12-454e-ba67-19d4c5c69b63.png">

I will get the correct document, but the updated query is actually wrong. I'm not using ObjectId as _id. So when I submit this new query I'll get `No documents found...`.
<img width="1215" alt="Screenshot 2023-02-01 at 12 55 17" src="https://user-images.githubusercontent.com/1048212/216035873-d463de8d-f98c-4d14-bfa8-f7a305413478.png">

**Desktop (please complete the following information):**
 - Mingo version: 1.11
 - OS: mac

**Comment by Icaruk** [comment]
Same here, but I'm using stringified ObjectId in other field that can be found in "Documents" tab but not on "Aggregator" tab  with match stage.

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
