### ISSUE TITLE
Result projection

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#54]
I expected to be able to type a query like this:
```
{ 
  foo: 'bar'
}, {
  foo: 1
}
```
in order to project the results but that did not work. And I can't really find any way to project results. Is this not possible yet or am I missing it somewhere?

**Comment by tothradoslav** [comment]
You are right, there's no option for that now. I will add this as a feature request.

What's your use-case for this? Personally, since we have "pinned columns" I neved needed to have custom projections. Maybe in case of large documents, it could save traffic / speed. 

Do you have any other use-case?

Thanks!

**Comment by Christilut** [comment]
I guess I'm just used to typing a quick projection so I can find the data I'm looking for quicker.
But you're probably right that it's not really needed.

I can't really think of other use cases other than "I'm used to it".

**Comment by frebos88** [comment]
We'd be interested in this as well. Our use case is to prepare queries with ease and visually instead of doing it inside the applications.

**Comment by tothradoslav** [comment]
Thanks @frebos88 This question is comming back quite often, so we'll have to address it eventually. For now, here's an explanation of why this is not such a straight-forward problem to solve. Technically, we have this solved already and could be implemented in 10 minutes, but there are some UX issues mentioned here: https://github.com/mingo-app/mingo/issues/481#issuecomment-1261386574

If you can elaborate on this in that issue, it would be a great feedback to make sure we solve this properly. Thanks!
