### ISSUE TITLE
[FR] Duplicate collection removed?

### ISSUE THREAD

**Issue by consciouscoder** [mingo-app/mingo#541]
I thought Mingo had a duplicate collection function when you right-click the collection? I don't see it in the menu anymore. This is an important feature to have! Please add it it?

**Comment by tothradoslav** [comment]
Sure, this will be added!

**Comment by tothradoslav** [comment]
This has been corrected in the last version. Please let us know if it is OK.

https://github.com/mingo-app/mingo/releases/tag/v1.12.0
