### ISSUE TITLE
Does not show collections

### ISSUE THREAD

**Issue by leonelvalentini** [mingo-app/mingo#542]
I added a new connection and it didn't list the collections. Tried clearing the cache and then a factory reset. Now when I add all the connections again, I don't see any collection, and they exist. Attached evidence.

What I can do?

![Screenshot 2023-02-24 at 12 43 01](https://user-images.githubusercontent.com/199661/221222331-df0e9330-8761-4537-9a38-31694a5a5611.png)

**Comment by leonelvalentini** [comment]
macOS: Ventura 13.2.1
Mingo: 1.12.0-rc1

**Comment by tothradoslav** [comment]
Hi, thanks. Is there anything special about the connection (SSH, passwords or anything) that might help us find the issue? What version of MongodB are you using?

Also, I see you are using the 1.12.0-rc1 version. Could you please check if the same issue will happen on v 1.11.0?

https://github.com/mingo-app/mingo/releases/tag/v1.11.0

**Comment by leonelvalentini** [comment]
Thanks, in version 1.11.0 it was fixed.

Only the indentation of the Arrays was broken again.

![Screenshot 2023-03-03 at 11 29 17](https://user-images.githubusercontent.com/199661/222746557-2c0afc3e-ebd5-481a-9538-20a97fd195db.png)

**Comment by achtan** [comment]
closing this, since the original issue is resolved. For array indentation we have separate issue here: https://github.com/mingo-app/mingo/issues/532
