### ISSUE TITLE
Error during import

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#543]
**Describe the bug**
I am not able to import sample JSON data with the latest version of Mingo. I am using these datasets: https://github.com/ozlerhakan/mongodb-json-files
MongoDB compass seems to be able to import them

**Screenshots**
![image](https://user-images.githubusercontent.com/1048212/222660240-9b60ad09-6ed8-44b7-8b31-f7f158221856.png)

**Desktop (please complete the following information):**
 - Mingo version: 1.10
 - OS: WIN

**Comment by tothradoslav** [comment]
This is due to the format being JSONLines, instead of regular JSON. We added this option.

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.11.1
- we added a new option to select JSON-L format
