### ISSUE TITLE
[FR] Set collation in query

### ISSUE THREAD

**Issue by thiagotsn** [mingo-app/mingo#546]
**Is your feature request related to a problem? Please describe.**
Not sure if it's current possible outside of node shell, but I would like to set the collation in a given document query. Sometimes I need to sort strings regardless of being lower or upper case.

**Describe the solution you'd like**
Maybe have an option below sorting, or just appearing on demand.

**Describe alternatives you've considered**
Using the node shell is clearly an option.

**Additional context**

**Comment by tothradoslav** [comment]
We have added this as a new option besides "sort" in documents.

**Comment by thiagotsn** [comment]
Awesome! That will work.

**Comment by tothradoslav** [comment]
This has been corrected in the last version. Please let us know if it is OK.

https://github.com/mingo-app/mingo/releases/tag/v1.12.0

**Comment by thiagotsn** [comment]
Working good, @tothradoslav.
Thank you!

**Comment by jefft043** [comment]
Is there a way to turn off the use of collation globally? I'm connecting to an Atlas serverless instance which doesn't support this feature and now unable to view any collections since the latest update.

Thanks

**Comment by tothradoslav** [comment]
Oops, sorry about that. We will be adding "Projection" as an option, too, but it will be "optional" by default. We will also make the collation optional, too. 

I have also changed the behavior, so that if the collation is empty {} then it's ignored. This will be out in next patch.

**Comment by jefft043** [comment]
Nice one, looking forward to the patch - projection will be useful too!

**Comment by dashersw** [comment]
Oh I just updated to 1.12.1 and because of collation can't use Atlas Serverless :( really looking forward to a patch.

**Comment by tothradoslav** [comment]
Hi, this has been resolved in the latest patch, please check it out here:

https://github.com/mingo-app/mingo/releases/tag/v1.12.2

**Comment by darwin-buelo** [comment]
> Hi, this has been resolved in the latest patch, please check it out here:
> 
> https://github.com/mingo-app/mingo/releases/tag/v1.12.2

Thank I just tested this one on my machine and my problem [#569](https://github.com/mingo-app/mingo/issues/569) is now solved
