### ISSUE TITLE
NodeShell stops working if the first line is empty

### ISSUE THREAD

**Issue by Icaruk** [mingo-app/mingo#547]
In NodeShell if you add new lines above the `async function run() {...` the script won't run.

![image](https://user-images.githubusercontent.com/10779469/223684981-8fba4dcd-c006-4486-b3cb-7ec03ff25a1c.png)

![image](https://user-images.githubusercontent.com/10779469/223685121-f3a044b3-edd4-48c2-8829-43f7b8b61436.png)

---

 - Mingo version: 1.11.0
 - OS: MacOS

**Comment by tothradoslav** [comment]
This has been corrected in the last version. Please let us know if it is OK.

https://github.com/mingo-app/mingo/releases/tag/v1.12.0
