### ISSUE TITLE
[FR] Add sha256sums to builds

### ISSUE THREAD

**Issue by ghost** [mingo-app/mingo#548]
Could you add sha256sums to all the packages which are built, currently I have to compute them manually by pulling the build over 3G, which is painfully slow.

Would really help with packaging :)

**Comment by tothradoslav** [comment]
Hi, in the releases, we also include the "latest.yml" for each build / OS, so you should be able to check the sha512 there. Would this be enough?

https://github.com/mingo-app/mingo/releases/tag/v1.11.1

**Comment by ghost** [comment]
Sounds good, thank you!
