### ISSUE TITLE
Dont allow multiple inline edits

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#549]
![0e2812df-a08a-4c51-8dae-ce0f15d980cd](https://user-images.githubusercontent.com/1048212/229080414-c29a4879-5c9b-418f-af04-bbfe7965d9b4.png)

**Comment by HiepPP** [comment]
I'm asked in chat a day ago. I would like to leave this message here to keep track of it. Thank you.

**Comment by tothradoslav** [comment]
Hi, this has been included in the latest release v1.12.1:

https://github.com/mingo-app/mingo/releases/tag/v1.12.1

I'm closing this issue, but please let us know if it worked right.
