### ISSUE TITLE
Not able to find by ID

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#551]
I'm not able to submit this: 
<img width="991" alt="Screenshot 2023-04-05 at 13 44 45" src="https://user-images.githubusercontent.com/1048212/230070917-74aac1dd-2956-48c5-b87c-c427e05716e3.png">

Hitting Enter or clicking on the item works

**Desktop (please complete the following information):**
 - Mingo version: 1.12.0-rc2
 - OS: OSX

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
