### ISSUE TITLE
Mingo mixing up collections between multiple connections

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#555]
I have multiple connections (e.g., prod, dev, etc). When I'm in the dev connection and press Cmd+T, it appears to show my dev collections. But when I open up a collection, it jumps to the corresponding collection on *prod*. I seem to have no way to access collections on dev any more.

Mingo version: 1.12.0
OS: macOS 13.3

**Comment by tothradoslav** [comment]
Thanks, this is probably related to #553, but we'll investigate and release a patch asap to fix this. Meanwhile if you have any further information that could help us track this, please send it over here.

**Comment by brianlukoff** [comment]
Thanks! Quitting and restarting Mingo doesn't even fix the problem for me (like in #553). Let me know what info would be helpful to help you track it down?

**Comment by tothradoslav** [comment]
So far, I have not been able to repoduce this issue. How do those connections (URIs and options to connect to them - SSH, etc) differ? I'd like to be able to reproduce the error. 

Does it happen on other projects, too? (if you have more)

Does it help help if you "Refresh databases"?

**Comment by tothradoslav** [comment]
Also, do you see which database you are viewing? I mean, is the issue such that it shows that you are viewing a collection in dev while the data are from production? 

Maybe could you send any screenshot?

**Comment by brianlukoff** [comment]
The connections are different (one is running on localhost and the other is remote), but the collections do have the same names in each collection (since one is dev and one is prod). In my setup, I have the dev connection coded green and prod red. When I select dev from the dropdown in the left, and then press Cmd+T to open a collection, the search results are coded green (as expected). But then when I open one of them up, the tab shows data from prod (and is colored red). 

Interestingly, it doesn't seem to happen on a third staging connection -- those open up correctly (and also have the same set of collection names).

Refreshing the connection doesn't seem to help. I'm not able to post a screenshot publicly but if you send me your email I can send you something by email (showing the above in action if that would be helpful)?

**Comment by tothradoslav** [comment]
Thanks, please send an email to info@mingo.io.

**Comment by tothradoslav** [comment]
This has been reported by @brianlukoff as fixed. Thanks for cooperation!
