### ISSUE TITLE
Dashboard widget are broken after upgrade to 1.12

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#557]
I'm seeing this... but I'm connected to DB (I can open any collection and browse data)
![Screenshot 2023-04-08 at 10 00 59](https://user-images.githubusercontent.com/1048212/230710676-09ee6bc1-1d2e-46a8-b7a7-182e01790398.png)

When I start editing the widget, it is wrongly prefilled.
![Screenshot 2023-04-08 at 10 03 46](https://user-images.githubusercontent.com/1048212/230710781-f3fb4060-efae-4cc2-9248-3de5e73a0b2a.png)

After I select the DB and collection, everything is working as before.

**Desktop (please complete the following information):**
 - Mingo version: 1.12
 - OS: mac

**Comment by tothradoslav** [comment]
We have identified and removed the problem causing this, however, there is unfortunately no way back and you will have to set the collection manually again. For people who skip v1.12.0, this will not be an issue.
