### ISSUE TITLE
Headers not aligned

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#558]
The headers in the Documents view are not aligned with the underlying data. (For example, "status" should be aligned with "waiting.")

<img width="1280" alt="screenshot" src="https://user-images.githubusercontent.com/518013/230966066-999ee1f8-76b4-40e9-83e1-54053456c275.png">

**Desktop (please complete the following information):**
 - Mingo version: 1.12.1-rc1
 - OS: macOS 13.3

**Comment by tothradoslav** [comment]
Thank you, fixed!

**Comment by tothradoslav** [comment]
Hi, this has been included in the latest release v1.12.1:

https://github.com/mingo-app/mingo/releases/tag/v1.12.1

I'm closing this issue, but please let us know if it worked right.
