### ISSUE TITLE
Undo does not work

### ISSUE THREAD

**Issue by laakal** [mingo-app/mingo#559]
**Describe the bug**
Undo does not work. It shows only overlay.

**Screenshots**
<img width="1236" alt="Screenshot 2023-04-14 at 18 15 03" src="https://user-images.githubusercontent.com/9221304/232084620-c335f700-7e28-4ced-b5dc-bca8d4068063.png">

**Desktop (please complete the following information):**
 - Mingo version: v12.1
 - OS: MacOS

**Comment by tothradoslav** [comment]
Thanks for this. I was not able to reproduce the error based on the information provided. This means that it has probably something to do with the actual action taken before trying to undo. Do you remember what action you did?

**Comment by laakal** [comment]
Only updated version.

**Comment by tothradoslav** [comment]
I'm sorry, I meant what was the action you have done in MongoDB that could be undone? Do you remember? Updating a document or deleting one?
