### ISSUE TITLE
Can't find quick selector search

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#56]
I really like the idea of the quick selector search. One of my main annoyances with mongo queries is having to type `ObjectId('...')` 

But I can't seem to find how to set it, The help menu says to right click the field but I've tried right clicking everywhere but I don't see any option for it.

**Comment by tothradoslav** [comment]
This feature has been improved and we forgot to update the help section :)

Now, quick search works on all indexed fields automatically. This is OK for you?

**Comment by Christilut** [comment]
Ah okay, yeah that makes sense. Perfect :)
