### ISSUE TITLE
[FR] Export schema as a typescript interface or type

### ISSUE THREAD

**Issue by emehmet** [mingo-app/mingo#560]
Hi,

There is an Export as a Graphql Schema button under the schema.
It would also be great too if there was an Export as a Typescript feature

**Comment by tothradoslav** [comment]
We added this, thanks for the tip. In next release.

**Comment by tothradoslav** [comment]
Hi, this has been resolved in the latest patch, please check it out here:

https://github.com/mingo-app/mingo/releases/tag/v1.12.2
