### ISSUE TITLE
Export results as CSV from aggregator exports a TSV

### ISSUE THREAD

**Issue by rashikkathuria** [mingo-app/mingo#561]
I experience 3 issues when exporting aggregation results as CSV to file

1. The format of the export is Tab Separated values rather than Comma Separated
2. The column headers are no exported
3. When exporting to file, the default filename has the extension of json

The above issues have been present since the past few versions.
<img width="857" alt="Screenshot 2023-04-16 at 8 29 28 AM" src="https://user-images.githubusercontent.com/10266611/232264404-7cc6ac20-8705-4689-9c88-06b71f7692c0.png">
<img width="749" alt="Screenshot 2023-04-16 at 8 30 01 AM" src="https://user-images.githubusercontent.com/10266611/232264406-ab1ca806-52ba-41a9-8ad4-7fd28ad9952e.png">

**Desktop (please complete the following information):**
 - Mingo version: 1.12.1
 - OS: OSX 12.6.4

**Comment by tothradoslav** [comment]
thank you, all 3 issues corrected (in next release)

**Comment by tothradoslav** [comment]
Hi, this has been resolved in the latest patch, please check it out here:

https://github.com/mingo-app/mingo/releases/tag/v1.12.2
