### ISSUE TITLE
Unable to open new tab by clicking on +

### ISSUE THREAD

**Issue by rashikkathuria** [mingo-app/mingo#562]
**Describe the bug**
Unable to open a new tab by clicking on the + icon in tab bar. This issue is in the 1.12.1 update on OSX. 

Opening a new tab using CMD+T works fine.

**Screenshots**
<img width="442" alt="Screenshot 2023-04-16 at 8 47 56 AM" src="https://user-images.githubusercontent.com/10266611/232264505-14c1c51b-74bd-4e24-8cf1-6f7f34497380.png">

**Desktop (please complete the following information):**
 - Mingo version: 1.12.1
 - OS: OSX 12.6.4

**Comment by tothradoslav** [comment]
thank you, corrected (for the next release)

**Comment by tothradoslav** [comment]
Hi, this has been resolved in the latest patch, please check it out here:

https://github.com/mingo-app/mingo/releases/tag/v1.12.2
