### ISSUE TITLE
[FR] update Many documents

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#565]
One thing I do a lot in Studio 3T is updateMany queries and more batch update operations. Do you plan on doing dedicated UI for updates similar to how you have dedicated UI for queries? In Mingo the only way to do this seems to be to use the NodeShell

**Comment by tothradoslav** [comment]
We decided not to implement this as a separate view / tab. We currently have the following way to do this:
1. select the documents you'd like to update (in Documents)
2. select "Update" from the options
3. This opens up the NodeShell view with a script prepopulated, which you only need to update as you need. Then execute it.

If there's any other special feature  about updateMany you'd like to see implemented, please let us know.
