### ISSUE TITLE
[FR] Add option to auto adjust all column widths based on content on page (ideally, an option to automatically do this)

### ISSUE THREAD

**Issue by mrjoesm** [mingo-app/mingo#568]
**Is your feature request related to a problem? Please describe.**
I'd like to see more columns on screen without having to manually resize them

**Describe the solution you'd like**
A setting to be able to do this automatically, and a button to be able to do it manually (so it can still be done if not automatically set)

![mingoidea](https://user-images.githubusercontent.com/19344769/233958805-60d73a2e-957d-49d0-be2d-e03107ce96a7.png)

potentially something simple like that if not automatic

**Describe alternatives you've considered**
manually adjusting width which is a bit of a drag

**Comment by tothradoslav** [comment]
Thanks for this. We can quite easily implement this as the functionality is already in place. However, I have a question: we do set a min (40px) and max (400px) with for each column in case of extremes. Would this be OK?

**Comment by tothradoslav** [comment]
For now, we have added this as a fourth icon as you described. So it's manual. However, the widths are saved for each collection separately, so you will only have to do this manually once in a while.

**Comment by mrjoesm** [comment]
> Thanks for this. We can quite easily implement this as the functionality is already in place. However, I have a question: we do set a min (40px) and max (400px) with for each column in case of extremes. Would this be OK?

I guess being able to configure this somewhere hidden away would be good, 400px seems quite big to me as a max (maybe 'hidden' away in an advanced options area)

Thanks for the quick replies 👍🏻

**Comment by tothradoslav** [comment]
Hi, this has been resolved in the latest patch, please check it out here:

https://github.com/mingo-app/mingo/releases/tag/v1.12.2
