### ISSUE TITLE
MongoServerError: collation not allowed in this atlas tier

### ISSUE THREAD

**Issue by darwin-buelo** [mingo-app/mingo#569]
![image](https://user-images.githubusercontent.com/99205725/234424170-96881cbf-3886-4b61-9647-bcf1e705ec71.png)

**Comment by javigines** [comment]
On the serverless tier of Atlas Database, collation is not supported, [here](https://www.mongodb.com/docs/atlas/reference/serverless-instance-limitations/#operational-limitations-and-considerations) you could check it.

It would be nice to only use collation operation if there is something defined on the field. @tothradoslav 
What do you think?

---

I see this has been discussed on #546. 
We would love to see the patch with the capability optional.

I think you can close this issue @darwin-buelo

**Comment by darwin-buelo** [comment]
thanks @javigines
