### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#57]
Is there a way to add custom CSS to Mingo? 

I like the design in general but I find the fonts a bit too large sometimes, especially in the document results. I like having smaller fonts with less margin there so I can fit more text on my screen.

This is a personal preference of course which is why custom CSS would be really nice to have.

Bonus points if I can use SCSS.

**Comment by tothradoslav** [comment]
This is a good point, as we all have different screens and resolutions, etc.

I see two ways to approach this:
1. implement themes, which will be pre-generated, such as "Normal", "Compact", etc.
2. allow users to add custom CSS (SCSS), which less userfriendly, more customizable. At the end, we are developers :)

What are your thoughts?

**Comment by Christilut** [comment]
I think themes would be a good idea. Maybe a few predefined themes and a way to just drop a (S)CSS file in a folder somewhere (maybe `Documents/Mingo` or something) so themes can be easily shared between users too.

I think a lot of developers would appreciate a compact/excel-like theme. I like pretty things but I like fast and efficient things better when I'm working :) 

I always used to use Robo3T because of the speed but it's lacking so many features that I'm trying to find the more powerful version of it. But all the alternatives (including Studio3T even) are so slow and sluggish. Mingo was an unexpected breath of fresh air after trying like 6 mongo GUI's :)

**Comment by tothradoslav** [comment]
Thanks, we'll work on themes and we'll start with a "compact" one. We'll discuss the option of sharing / creating public themes by users.

It's very trendy lately to have a dark-theme, so maybe :D

If you have any ideas or issues with Mingo, please let us know. Anything...

**Comment by Christilut** [comment]
Absolutely dark theme is everything! First thing I look for in any tool that I use...

I'll keep reporting anything I come across :)

**Comment by GriffinSauce** [comment]
🙌 Another vote for dark theme!

**Comment by tothradoslav** [comment]
@Christilut is the current compact mode sufficient? Anything we missed or you’d improve?

**Comment by Christilut** [comment]
Maybe a bit less top and bottom padding on document fields?

Also, why are some field values in italics and others aren't? Makes it a bit less readable for me. I don't know what the italics mean now and for that reason I'd prefer them all to be normal

**Comment by Christilut** [comment]
In compact mode the top section (tab, navigation bar, collection title and then query field) takes up about 30% of my Mingo window now (it's not maximized but I like it floating). Maybe that can be reduced a bit for compact mode?

**Comment by Christilut** [comment]
![image](https://user-images.githubusercontent.com/3471363/70849185-496e5680-1e7b-11ea-854b-37f2c25df2a5.png)

The bottom part of the query field seems like wasted space. The button can be positioned absolute inside the field.

**Comment by Christilut** [comment]
![image](https://user-images.githubusercontent.com/3471363/70849210-89cdd480-1e7b-11ea-8a74-45cc888e1973.png)

The left part doesn't do anything and that information is already in the navigation bar above it.

The right part could be moved into the navigation bar in compact mode? Or in the query field above the button

**Comment by tothradoslav** [comment]
I've reworked the compact mode, so it's completely CSS rem units dependent. Now compact mode will change the relative size of everything.

Italics: not sure where you mean, but as document values or pinned column values, italics are objects and arrays, which can be further expanded to view sub-fields. Is this what you meant @Christilut ?

**Comment by Christilut** [comment]
![image](https://user-images.githubusercontent.com/3471363/70984783-5e392d00-20bb-11ea-8004-c0826faf4d20.png)

The booleans are in italics. So are arrays and objects. That's because they can be expanded like you said?
But I only just learned that now, until now that didn't click and it's been less readable for me. I think the arrow and the fact that the text is grey are enough hints that it can be expanded. Now it's just a bit more messy.

Same with the colors. I like colors hinting at what things are but it feels like there are too many colors. For example, the ObjectId: one is green, the other is blue. I know that's because the blue one links to a document, but it still adds mental overhead.
And boolean colors is a nice idea but I think in practice it might be a waste of the red and green colors. If they are both the same (neutral) color, I'd probably find that more readable. As a developer, I'm trained to see `true` and `false`.

Another small thing to make things a bit more calm: the timestamp next to ObjectId's, is that really necessary? I've never used the ObjectId timestamp for anything. I can understand it might be useful, but maybe as a hover tooltip or something? I don't think it should be displayed at all times.

Hope this makes sense from my perspective :)

**Comment by tothradoslav** [comment]
Sure it does. I changed / simpliefied a couple of things:
- removed all the italics
- removed the date next to ObjectIDs (added it as a tooltip)
- removed the color differences between ObjectID and ObjectID link (foreign key)
- for now, I kept the red / green for false / true

Let's see how this works.
