### ISSUE TITLE
Column reoganising in collection stats doesn't work 

### ISSUE THREAD

**Issue by mrjoesm** [mingo-app/mingo#570]
**Describe the bug**
View database stats, reorganise headers, the columns aren't reorganised

**Screenshots**
![1](https://user-images.githubusercontent.com/19344769/234550722-7e58bd23-001a-4663-bcfe-c6bb82e57e61.png)

![2](https://user-images.githubusercontent.com/19344769/234550727-b68e1077-1f90-4b21-9b78-b8f6f450c633.png)

![3](https://user-images.githubusercontent.com/19344769/234550730-a4468f0a-d176-4145-8b21-cda15c84c472.png)

**Desktop (please complete the following information):**
 - Mingo version: 1.12.1
 - OS: Windows 11

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
