### ISSUE TITLE
aggregation: DnD will insert extra text into pipeline

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#573]
**Screenshots**
https://capture.dropbox.com/rtphG546zgajWuCe

**Desktop (please complete the following information):**
 - Mingo version: 1.12.2
 - OS: mac

**Comment by tothradoslav** [comment]
- this has something to do with the sortable / draggable element
- so far, none of the solutions I tried worked

**Comment by tothradoslav** [comment]
Solution: hiding the inside of the element being dragged

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
