### ISSUE TITLE
Collarion is not supported on DocumentDB

### ISSUE THREAD

**Issue by achtan** [mingo-app/mingo#575]
**Describe the bug**

Hi!  We are getting a "MongoServerError: option collation is not currently supported" error when querying our DocumentDB instance via Mingo.  I remember you said DocumentDB isn't officially supported, but it was working well in previous versions.  Is there any way this can be solved with Mingo?

**Desktop (please complete the following information):**
 - Mingo version: 1.12.2
 - OS: mac

**Comment by joca-immersa** [comment]
This is also happening to me since a couple weeks ago

**Comment by joca-immersa** [comment]
I just try using node shell and that is working ok, the issue seems to be primarily to listing the collection documents

**Comment by PfisterFactor** [comment]
+1 for this issue, our team can no longer use Mingo until this is fixed.

**Comment by joca-immersa** [comment]
seems to be fixed in the latest release :D

**Comment by tothradoslav** [comment]
This has been resolved in the latest RC release, please check it out and let us know if the solution works as expected:

https://github.com/mingo-app/mingo/releases/tag/v1.13.0-rc1

**Comment by joca-immersa** [comment]
it works, thanks :D

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v1.13.1
