### ISSUE TITLE
[FR] Aggregate $objectToArray

### ISSUE THREAD

**Issue by BronzorX** [mingo-app/mingo#577]
There's no possible to insert a stage with the function "$objectToArray"

**Comment by tothradoslav** [comment]
$objectToArray is an operator, not an aggregation stage. You can use it inside an aggregation stage, for example: 

`
[{$project: {
item: 1,
dimensions: { $objectToArray: "$dimensions" }
}}] 
`

**Comment by tothradoslav** [comment]
While at it, I checked the current list of supported aggregation stages and added the missing (new) ones.
