### ISSUE TITLE
Editing document error

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#58]
I tried to edit a document but it is showing a validation error even though I didn't touch it yet:
![image](https://user-images.githubusercontent.com/3471363/69959081-8c890b00-1506-11ea-9c63-eedbf6a12e18.png)
I erased the cognitoUserId field.

The error is `Expected JSON value. Expected '}' but saw 'new'`

And the first time I opened this popup, I couldn't edit anything at all. Keyboard just wouldn't type in here. I opened and closed it and now I can type. Can't really reproduce that yet.

**Comment by tothradoslav** [comment]
Yes, we'll have to address the validation error shown, as "new Something()" not a standard JSON format.

However, I could not reproduce the `Expected JSON value. Expected '}' but saw 'new'` error. Has the error occured after "Save changes"?

**Comment by tothradoslav** [comment]
Oh, I got it now, it's an error shown by the editor... I will address this, thanks. 

Regarding the typing issue, maybe the editor wasn't focused? I think an "autofocus" is missing there.

**Comment by Christilut** [comment]
Not sure, I can't remember exactly. I remember clicking a bunch of times wondering why I couldn't type. Then closing it and opening it again and then I was able to type.

But I had the same problem with the query field once. I couldn't understand where to type my query because I couldn't type there. After restarting the app I was able to type in the query field so I figured it was a bug, but I couldn't reproduce. I'll let you know if it happens again.

**Comment by tothradoslav** [comment]
Are you on windows or OSX? Or maybe linux?

**Comment by Christilut** [comment]
Windows 10

**Comment by Christilut** [comment]
Fixed
