### ISSUE TITLE
Timeout is not using value from settings

### ISSUE THREAD

**Issue by matadur** [mingo-app/mingo#580]
![setting at 60sec](https://github.com/mingo-app/mingo/assets/2113643/6fc2e622-e54a-4b7d-98a7-1ba4d6d065c4)

![error always occurs at 5sec](https://github.com/mingo-app/mingo/assets/2113643/b38330e5-d85b-4d15-836d-bdbc3091ed9f)

**Comment by tothradoslav** [comment]
Thank you, we have been overriding the settings with 5000ms. Sometimes, when the connection is wrong, there's no response and so you would have to wait 60 seconds to learn that. 

I have now removed this.

**Comment by tothradoslav** [comment]
We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4
