### ISSUE TITLE
appName in connection string is not respected

### ISSUE THREAD

**Issue by sagrawal31** [mingo-app/mingo#581]
**Describe the bug**

When passing [`appName`](https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.appName) in the connection string, Mingo is not using the value and sending `mingo` instead to the server. 

**Screenshots**

![image](https://github.com/mingo-app/mingo/assets/1804514/9769f367-cff4-43c0-aba3-cb403fe76818)

![image](https://github.com/mingo-app/mingo/assets/1804514/cce44a02-07d4-4e36-b649-7bdfaa25271b)

(Same behaviour is with `mongodb+srv`.

Because of this, we aren't able to identify who from within the developer team is running queries which is resulting in CPU usage (or running queries without index) on production.

**Desktop (please complete the following information):**
 - Mingo version: 1.13.1
 - OS: macOS Ventura 13.3.1

**Comment by tothradoslav** [comment]
We were overriding this value. We changed this so that you can specify yours, and unless you provide and appName, we will send "mingo".

**Comment by sagrawal31** [comment]
That's awesome. Looking forward to the release.

**Comment by sagrawal31** [comment]
Any update here?

**Comment by tothradoslav** [comment]
sorry, yeah, we have not released it yet, will do this next week. Sorry

**Comment by tothradoslav** [comment]
We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4
