### ISSUE TITLE
[FR] Show index size (human readable) in index management

### ISSUE THREAD

**Issue by sagrawal31** [mingo-app/mingo#583]
**Is your feature request related to a problem? Please describe.**
Every time I have to see what size is being taken by an index, I have to go to `MongoDB compass`.

**Describe the solution you'd like**
It would be best if Mingo could show the index size beside each index.
![image](https://github.com/mingo-app/mingo/assets/1804514/aa4d2482-0a0f-473c-be5a-b977a1fe9238)

**Describe alternatives you've considered**

Have to go to MongoDB compass for this very useful information.

**Comment by tothradoslav** [comment]
Thank you we have added this.

**Comment by sagrawal31** [comment]
That's amazing. Looking forward to see this in the release.

**Comment by sagrawal31** [comment]
Any update on this? Seems this hasn't been rolled out for 2 months. I'm using `1.13.3` right now.
