### ISSUE TITLE
Some connections give generic error when trying to run compare & sync

### ISSUE THREAD

**Issue by matadur** [mingo-app/mingo#584]
When using the Compare & Sync feature for some connections, it is giving a generic error.

Screenshot:
![CleanShot 2023-05-30 at 12 15 07@2x](https://github.com/mingo-app/mingo/assets/2113643/ec143d7a-86c9-4c3a-8ce2-c785d41637e1)

**Desktop (please complete the following information):**
 - Mingo version: 1.13.1
 - OS: Mac 10.14.6

**Comment by matadur** [comment]
VPN used = No
Mongo version = 3.6.21
Databases being compare are for a Meteor site and are an exact copy (using dump/restore)

**Comment by tothradoslav** [comment]
Thank you, I think I found the issue and fixed it. Let's see in next release.

**Comment by tothradoslav** [comment]
We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4
