### ISSUE TITLE
[FR] Export to bson for Golang use strictly required

### ISSUE THREAD

**Issue by Deanisy** [mingo-app/mingo#587]
Export aggregation to bson for Golang is very valuable. Compass has it...

**Comment by tothradoslav** [comment]
Do you mean exporting the pipeline itself?

**Comment by tothradoslav** [comment]
if this is what you meat, we added all languages available in Compass.

**Comment by Deanisy** [comment]
I mean exporting pipeline to bson
It has now only two available in "Copy pipeline" action:
1) As JSON
2) As Node.js code

Compass has pipeline export to language: 
1) Java
2) Node
3) C#
4) Python
5) Ruby
6) Go
7) Rust
8) PHP

**Comment by tothradoslav** [comment]
Yes, we added all these. Will be available in the next release.

**Comment by tothradoslav** [comment]
We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4
