### ISSUE TITLE
Restore from archive with error

### ISSUE THREAD

**Issue by jmisur** [mingo-app/mingo#588]
**Describe the bug**
Mongorestore from archive doesn't work.

I have a gzipped archive with collections from remote database (created with mingo dump). Then I want to restore it to local database, but mongorestore fails due to missing parameter.

```
Starting mongorestore...
Executing: /opt/homebrew/bin/mongorestore
Params: --uri="mongodb://127.0.0.1:27017/?appName=mingo",--archive="/Users/xyz/archive.gz",--nsTo="test.*",--drop,--gzip
2023-06-13T09:52:18.699+0200	Failed: --nsFrom and --nsTo arguments must be specified an equal number of times
2023-06-13T09:52:18.699+0200	0 document(s) restored successfully. 0 document(s) failed to restore.
--- mongorestore completed ---
```

`--nsFrom` would be `"dev.*"` in my case. Even if nsFrom and nsTo would be the same, mongorestore requires them to be specified.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Desktop (please complete the following information):**
 - Mingo version: 1.13.3
 - OS: Ventura 13.4
- mongodb/brew/mongodb-database-tools: stable 100.7.2

**Comment by tothradoslav** [comment]
To make this work properly, mongorestore needs the name of the original database from which the dump has been created. We added a prompt to enter the name of the original DB and now it works.
