### ISSUE TITLE
[FR] Do not open new tab on each database collection clics

### ISSUE THREAD

**Issue by mctwistyup** [mingo-app/mingo#589]
**Describe the solution you'd like**
Open current already opened tab and propose to open a new tab on right clic

<img width="820" alt="image" src="https://github.com/mingo-app/mingo/assets/90046724/2a477bb7-90df-49ea-aca7-5748aeaf5842">

**Comment by tothradoslav** [comment]
You can set this in the settings / preferences. Please let me know if it worked.
