### ISSUE TITLE
Exporting documents

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#59]
I selected multiple documents and I wanted to export them with all fields. But in the export popup, I have to enter the columns I want to export and I see no way to export them all.

Also I can enter `doc` as value there which results in `[object Object]` as exported value. Maybe entering `doc` can be used to show all fields instead?

And from a user perspective, it maybe makes more sense to allow me to type `_id` instead of `doc._id` because I'm not sure what the use of the doc prefix is here?

**Comment by tothradoslav** [comment]
The "doc" is there to be able to process/parse the values before exporting. For example, you could use lodash or moment() to process the field values. 

We could come up with a way to export "all fields". You suggested "doc" to export all, but maybe we could just have the option (checkbox) to export all fields, and in that case, there's no need to specify any other fields. 

One question: what if the document contains subdocuments (objects), how would these be represented in the ouput?

**Comment by Christilut** [comment]
Checkbox sounds good.

Not sure how to represent subdocuments.. That's not really CSV compatible. Maybe `doc.subdoc.fieldname` to use the value of that field in the column instead of the entire subdocument. But subdocuments can be anything and infinitely deep... Maybe just provide the option to go 1 layer deep and no more.
If the subdocument is an array, it might be useful to have a `.length` helper property? `doc.items.length`

**Comment by tothradoslav** [comment]
This "complete" kind of export would be unusable in case of large deeply nested documents. In case of simple docs, let the user tick a checkbox and objects and arrays would be omited or just mentioned as "Array(15)" or "Object(13)". Otherwise there's no real use of such deep data in CSV anyway. I guess...

**Comment by Christilut** [comment]
I agree. It would be almost another side project to make something that supports that kind of JSON structure to CSV in a nice way.
