### ISSUE TITLE
[BUG] Unable to delete undefined project

### ISSUE THREAD

**Issue by Icaruk** [mingo-app/mingo#593]
**Describe the bug**
I had 2 projects, I deleted one of them and the other one was set to `undefined`, making me unable to edit or delete it.

**Screenshots**
![image](https://github.com/mingo-app/mingo/assets/10779469/2746a4d2-93ae-4023-aa71-f2f349783679)
![image](https://github.com/mingo-app/mingo/assets/10779469/08dc6477-ede7-411d-892c-7b3f3850dff5)
![image](https://github.com/mingo-app/mingo/assets/10779469/8255553c-25b6-4388-8349-bdf612e7b26d)

If I go to edit the project...
![image](https://github.com/mingo-app/mingo/assets/10779469/664112ce-6712-405e-8f87-f0f59afa6976)

- I can't save changes because "Projects must have at least one database"
- I can't "Add database..." because the button doesn't work

EDIT: I was playing around with the `undefined` project testing it and it seems that all my mingo data is deleted.
![image](https://github.com/mingo-app/mingo/assets/10779469/549554a6-002f-4ff4-b3e0-80905ddc8d5c)

EDIT2: I played more creating empty "New project" (because "Add database..." button doesn't work) and I switched back to the normal mode.

**Desktop (please complete the following information):**
 - Mingo version: 1.13.3
 - OS: MacOS Ventura 13.2.1

**Comment by tothradoslav** [comment]
I have no idea (yet) on how you managed to have an undefined project name, but I made it possible to delete it in such cases. Will allow you to submit an empty prompt in such case.

**Comment by tothradoslav** [comment]
We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4

**Comment by Icaruk** [comment]
> We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4

Tested and fixed!
