### ISSUE TITLE
[FR] Management: add unban functionality

### ISSUE THREAD

**Issue by brunoosilva** [mingo-app/mingo#597]
I tried to contact you by email and chat, I had no response for 2 days, let's try to respond more quickly here.

I needed to use Mingo on another machine for a few days temporarily, but the only option I saw on the panel was "Ban device", there should be an option for "Remove device" as well.

What happened was that I can no longer use Mingo on the main machine, could you remove my device from the black list, as I cannot bind the license?

If possible, they could implement the "Remove Device" logic as well.

I've been using Studio 3T for 2 days, but paying for Mingo's license.

**Comment by tothradoslav** [comment]
I think @achtan has already dealt with this. But we should definitely add the remove functionality, too.

**Comment by tothradoslav** [comment]
@achtan what is the state on this issue?

**Comment by laakal** [comment]
We banned devices by mistake. It can no longer be undone. Please add the functionality to list banned devices and unban them.

**Comment by achtan** [comment]
@brunoosilva I believe you are set right? if you still have some issues please let me know.
@laakal please send me your email to david@mingo.io so I can find your license. thanks

Regarding this issue, yes I'll add this button to management.

**Comment by achtan** [comment]
Hi, I replaced the "ban" functionality with the "disconnect". So now you can disconnect/remove a device from your license but its not banned, therefore you can connect the same device again.
