### ISSUE TITLE
Copying documents

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#60]
I selected multiple documents and right clicked and selected `Copy doc` but it only copied 1 document to the clipboard instead of all of them.

What I also notice is that the right click menu is still singular when multiple documents are selected. For example "Remove document" when I have 10 selected. That confuses me as a user. I would like to see "Remove 10 documents" there so I'm more confident as to what I'm doing.

**Comment by tothradoslav** [comment]
This is a very good comment. We will work on this.
