### ISSUE TITLE
[FR] Show index sizes in Indexes tab

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#600]
**Is your feature request related to a problem? Please describe.**
Would love to see index sizes in the Indexes tab for a collection.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
Alternative is to manually run `db.[collectionName].stats({ indexDetails: true })` in `mongosh`.

**Comment by tothradoslav** [comment]
By "index size" you mean the number of  bytes used? Because that is in the table as a column. Or do you mean something else? 

This is the new way of getting index stats: https://www.mongodb.com/docs/manual/reference/operator/aggregation/collStats/#mongodb-pipeline-pipe.-collStats

**Comment by brianlukoff** [comment]
Right, exactly! I don't have that column, though -- is there a way to add additional columns?
<img width="1152" alt="image" src="https://github.com/mingo-app/mingo/assets/518013/6f08dff0-baef-4f5e-9ac7-6099f094c3ec">

**Comment by tothradoslav** [comment]
I can't remember, but maybe this has been added already, just not released, because I see this in my version. I'll mark this as ready for release.

**Comment by tothradoslav** [comment]
We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4

**Comment by brianlukoff** [comment]
Thanks -- just tried it and the RC works well!
