### ISSUE TITLE
[FR] int types in exported csv format 

### ISSUE THREAD

**Issue by emehmet** [mingo-app/mingo#601]
Hi,

I try to export data as csv format. This is working great. But I need to export int data in csv. Because when I use import to another software lik Heidisql, it doesn't import it expectedly. All datas export as string.

Can you add customizable types like parseInt(data) or new Date(date)?

**Comment by tothradoslav** [comment]
Do you mean in this form?

<img width="805" alt="Screenshot 2023-09-20 at 21 30 39" src="https://github.com/mingo-app/mingo/assets/3465808/f369d01f-424f-495c-bdab-00ea262fa0f9">

if so, you can enter almost any JS code in the Columns textarea and even use lodash, dayjs, etc. Each row is evaluated separately, so for example, you want to export "createdAt" as a date, use:

new Date(doc.createdAt)

Please let me know if this is what you meant.

**Comment by tothradoslav** [comment]
Done, We added an option "Only wrap strings" with the value wrapper.

**Comment by tothradoslav** [comment]
Hi, this has been released in the latest version. Please check it out and let us know if there's still an issue. Thank you!
