### ISSUE TITLE
Cannot hide/unhide index without rebuilding it

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#603]
If I try to edit an index and change it from hidden to unhidden (or vice versa), Mongo will rebuild the entire index. Would be great to be able to use `hideIndex` and `unhideIndex` to hide or unhide a large index quickly without rebuilding it.

**Comment by tothradoslav** [comment]
we added a "toggle hidden" option in the context menu for each index.

**Comment by tothradoslav** [comment]
We have just released a release candidate with this issue corrected. Please check it out here: https://github.com/mingo-app/mingo/releases/tag/v.1.13.4
