### ISSUE TITLE
Compare and sync rarely works with remote connection

### ISSUE THREAD

**Issue by MathiasKandelborg** [mingo-app/mingo#604]
I'm remotely connected to a database that I want to sync with. The functionality rarely works with the remote database. I can make a dump to localhost, and the functionality works fine between my local databases. Only when I try to do it remotely, it becomes an issue.

I've found that it sometimes works by restarting Mingo, but it's still rare. And some times, I don't need to restart the application, and it just works.

It halts on the scanning collections step. Either it takes a split second, or it doesn't happen.

Update:

I've just sat and tried several things, and if I update the meta information on both databases, it's suitable for one sync, and then I have to repeat that process to do it again.

**Comment by MathiasKandelborg** [comment]
I didn't get an issue template from using the application menu to submit a bug report.

OS: Mac v13.5
Mingo: 1.13.3

**Comment by tothradoslav** [comment]
We have improved the handling of meta information. This should help.
