### ISSUE TITLE
Compare & Sync stopped working after I compared & synced once

### ISSUE THREAD

**Issue by louis77** [mingo-app/mingo#607]
**Describe the bug**
I was using compare & sync to transfer two collections from remote to local. The local was empty, so everything worked fine. Since that, Compare & Sync fails (see screenshot). The error message is very generic.

I can access all collections on both remote and local otherwise.

**Screenshots**
![Bildschirmfoto 2023-09-04 um 20 55 13](https://github.com/mingo-app/mingo/assets/1240462/dfa83d0d-bc6d-4111-b76c-41ea93f2f543)

**Desktop (please complete the following information):**
 - Mingo version: 1.13.3
 - OS: macOS 13.5.1 (22G90)

**Comment by Icaruk** [comment]
I have the same problem, if the local is empty the sync&compare works, otherwise "An error ocurred".
