### ISSUE TITLE
Pinned arrays / objects to show array.length / object.keys.length

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#61]
When I right click with multiple documents open, I can select "Expand all" which I thought would open all selected documents but only did that for one document.

I now realize "Expand all" means that it expands the document and its subdocuments. 

With multiple documents selected, I expect it to expand all of them and (maybe?) all their subdocuments.

Maybe it's an idea to move the "Expand all" option to the right click menu of an already expanded document? That makes more sense to me.

**Comment by tothradoslav** [comment]
There's a "expand all" option when you click a field of opened document, too. So this would be confusing. 

Maybe renaming the document option to "Expand all fields". And this should work for multiple docs if selected (opening and expanding all fields for each selected document).

I'm thinking of a use-case for when you need to open multiple docs and expand them all. Do you have one? :)

**Comment by Christilut** [comment]
Well I do sometimes want to quickly check fields from multiple documents, so if I could open all of them (main doc, the subdocuments can stay closed) then I can scroll past them and check visually.
The other way I do this is by projecting results, but that's not possible right now.

I guess I could use the export option and only select the fields I want for this but that seems like a workaround if I just want to quickly see/compare a field from many docs.

I agree that renaming the option is a good idea for better user expectations.

**Comment by tothradoslav** [comment]
How about pinning the field as a column, then you have a visual representation on all docs.

**Comment by Christilut** [comment]
Right, good point. Sorry, not used to some of these cool features yet :)

Small feature request there: if the pinned field is an array, show the length instead of the contents? Contents could be useful, but if its an array of objectid's then its really not useful to see that but I do like seeing the length.

**Comment by tothradoslav** [comment]
Yeah, that's a good idea. If the array contains non-scalar (not primitive) values, It would be more usefull to show the length only. If the value contains simple primitive values, a "preview" (as current solution) is better.

**Comment by tothradoslav** [comment]
I gave this a bit more thought and realized that the user should be allowed to choose what to be shown. This is currently the case, as one can customize the column to show the length of the array. 

This can be achieved: https://share.getcloudapp.com/kpumEWOQ by adding ".length" here: https://share.getcloudapp.com/6quL7GNA

What do you think?

**Comment by Christilut** [comment]
Ah yeah, that's cool. And I like that I can do `Object.keys(doc..).length` too. But maybe the default value for that field can be `doc.foo.length` for arrays? (and maybe .keys.length for objects)
I think if it starts as `doc.foo.length` it would make users quickly realize what they can do with that field.

**Comment by tothradoslav** [comment]
The question is how let people know there's a "customize" option when on pinned columns. Do you think it's intuitive enough that people will find that there's a ".length" added?

**Comment by Christilut** [comment]
Hmm maybe not. Kind of difficult to explain power tools but without ruining the nice interface with text everywhere... 
Maybe an onboarding tour with popups when things open for the first time? 
Or a help icon inside/next to the input field with a tooltip

**Comment by tothradoslav** [comment]
Yep, we'll create a tour, but, honestly, most people (including me) skip them... UI should be selfexplanatory :)

But we'll work on this.

**Comment by Christilut** [comment]
Objects show their length now but arrays still show the contents

**Comment by tothradoslav** [comment]
Corrected.
