### ISSUE TITLE
[rc] Querying directly for an `ObjectId` now leads to an error

### ISSUE THREAD

**Issue by Icaruk** [mingo-app/mingo#610]
**Describe the bug**
Querying directly for an `ObjectId` now leads to an error.

**Screenshots**
![image](https://github.com/mingo-app/mingo/assets/10779469/175de98e-d1cd-4b74-a515-d507fa388f09)
![image](https://github.com/mingo-app/mingo/assets/10779469/f08a73be-090e-4e02-8e3b-db2a11642bf7)

**Desktop (please complete the following information):**
 - Mingo version: 1.13.4-rc1
 - OS: MacOS Ventura 13.2.1

**Comment by tothradoslav** [comment]
sorry, resolved.
