### ISSUE TITLE
Manage app, company page

### ISSUE THREAD

**Issue by radumetawealth** [mingo-app/mingo#611]
**Describe the bug**
The app remains in the loading state a long while after which returns error in the company tab on https://manage.mingo.io/my/licenses/*licenseNumber*

**Screenshots**
<img width="1081" alt="Screenshot 2023-10-07 at 16 23 08" src="https://github.com/mingo-app/mingo/assets/123368430/d2b41d38-1005-499b-9780-68962628c303">
<img width="1110" alt="Screenshot 2023-10-07 at 16 21 59" src="https://github.com/mingo-app/mingo/assets/123368430/6caec0e6-bef8-464b-a149-529e2d64c1b7">

**Desktop (please complete the following information):**
 - Mingo version: -
 - OS: MacOS Chrome

**Comment by tothradoslav** [comment]
@achtan

**Comment by achtan** [comment]
Hi @radumetawealth I just released a new version. Can you please check if your error is still there?
