### ISSUE TITLE
Inline edit of field values keep "change" after pressing cancel

### ISSUE THREAD

**Issue by kb-konsultit** [mingo-app/mingo#613]
**Describe the bug**
When doing an inline edit of a field value - if you want to abort it by pressing [Cancel] you cannot get it to clear what you entered and revert to the original value. Only by closing the collection tab can you get it to 

**Screenshots**
Step 1 Open document
![billede](https://github.com/mingo-app/mingo/assets/55577897/855742b1-05b8-42f5-8184-fe8fc42cf75a)

Step 2 Double click to edit a value
![billede](https://github.com/mingo-app/mingo/assets/55577897/5ada4d74-2b7b-4ff4-b4fe-ca52b7cedb35)

Step 3 Press [Cancel] to cancel the edit

Step 4 Reopen field
altered value persists - even pressing [Refresh] does not clear. You need to close the collection before it discards the value
![billede](https://github.com/mingo-app/mingo/assets/55577897/0f15913f-dfd9-4f99-bf3f-488f4f815a68)

**Desktop (please complete the following information):**
 - Mingo version: 1.13.4
 - OS: Windows 11

**Comment by tothradoslav** [comment]
Thank you for reporting this, it's corrected. Available in next release. Please keep open until pushlished.

**Comment by tothradoslav** [comment]
Hi, this has been released in the latest version. Please check it out and let us know if there's still an issue. Thank you!
