### ISSUE TITLE
Error using "Show document in new tab" 

### ISSUE THREAD

**Issue by fernandoDinoia** [mingo-app/mingo#614]
Hi,

With the latest version I have this problem: When I want to follow the relations and open the document in a new tab. The tab opens empty and shows the error: Invalid Selector: TypeError: Class constructor ObjectId cannot be invoked without 'new'.

Version: 1.13.4 (Mac)

Thanks

**Comment by colbygreen32** [comment]
Experiencing this same issue with the current version. Was a great feature that no longer works

**Comment by tothradoslav** [comment]
Thank you, this is corrected! Will be available in next release.

**Comment by tothradoslav** [comment]
Hi, this has been released in the latest version. Please check it out and let us know if there's still an issue. Thank you!
