### ISSUE TITLE
NodeShell snippet for Update fails when collection has a dot

### ISSUE THREAD

**Issue by thiagotsn** [mingo-app/mingo#615]
**Describe the bug**
When selecting rows and clicking Update, it changes to NodeShell with a UpdateMany snippet.
The snippet works fine for a collection such **products** (`return await products.updateMany`).
When it's a collection such as **products.details** (`return await distributors.catalog.updateMany`), it won't work because of the dot, leading to a _TypeError: Cannot read properties of undefined (reading 'updateMany')_.

A suggestion would be to detect the dot and instead the snippet uses `return await db.collection("products.details").updateMany`

**Screenshots**
![CleanShot 2023-10-27 at 22 17 12@2x](https://github.com/mingo-app/mingo/assets/11219154/e845a60a-3d66-48e5-b27c-8058016ad126)

**Desktop (please complete the following information):**
 - Mingo version: 1.13.4
 - OS: MacOS Sonoma 14.1 (23B74)

**Comment by tothradoslav** [comment]
Thanks for reporting this. We fixed it. Will be available in the next release.

**Comment by tothradoslav** [comment]
Hi, this has been released in the latest version. Please check it out and let us know if there's still an issue. Thank you!
