### ISSUE TITLE
Big CSV files can't import 

### ISSUE THREAD

**Issue by fungalspores** [mingo-app/mingo#617]
Edition	Windows 10 Pro
Version	20H2
Installed on	‎07.‎07.‎2021
OS build	19042.1766
Experience	Windows Feature Experience Pack 120.2212.4180.0

Processor	AMD Ryzen 5 3600 6-Core Processor  3.60 GHz
Installed RAM	64,0 GB
System type	64-bit operating system, x64-based processor

I can't import any big csv files

**Comment by achtan** [comment]
This is still an issue. At least on windows.

**Comment by tothradoslav** [comment]
1. How large is a large CSV file?
2. Can you try importing a part of that CSV file with a few lines to make sure the size is the actual problem?
