### ISSUE TITLE
Copy as JSON

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#62]
I copied a document but the contents are not compatible with JSON. I guess the contents are compatible with Mingo to quickly create a new document and that's great.

But in this case I want to take data from the database and use it in my code as testing data so I need it to be JSON. It would be nice if I can copy documents in normal JSON format without `ObjectID`, `new` and `Date` tags.

**Comment by tothradoslav** [comment]
Regular JSON does not support such values as dates, ObjectIDs, ets. How should they be represented in JSON?

For example, ObjectId could be a string, dates, too. Would that be ok?

**Comment by Christilut** [comment]
Yeah exactly. Date would be an ISO string `"2019-12-04T10:05:51.132Z"` and ObjectId's as string.

**Comment by Christilut** [comment]
Very nice, really handy!
