### ISSUE TITLE
Mingo asks for password to my database each time I restart

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#620]
**Describe the bug**`
Every time I restart Mingo, I need to re-enter the password for my production database. After I enter the password, it connects normally. Restart Mingo and the popup appears again.

My connection has a username:password that mingo has replaced with `username:PASSWORDPLACEHOLDER`

**Screenshots**
![image](https://github.com/mingo-app/mingo/assets/3471363/164a2291-f51f-4960-b881-9890bd329965)

**Desktop (please complete the following information):**
 - Mingo version: 1.13.5
 - OS: Windows

**Comment by jefft043** [comment]
Just to add to this, I'm experiencing the same issues.

I'm not asked to re-enter passwords when I access a saved 'Connection' only if I try to access a saved 'Project'.

**Comment by tothradoslav** [comment]
I have just found out the service we used (keytar) is deprecated. We are now using electron's safeStorage API, with fallback to keytar, meaning you won't have to retype passwords. If password not found in safeStorage, will look for it in keytar and if found, automatically moves the password to safeStorage.

**Comment by sagrawal31** [comment]
Happy to see this.

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.

**Comment by lrprotexxa** [comment]
Hi all, I have the latest version of mingo and I have the same problem, both on MacOS and Windows 11. Even when navigating through projects, it keeps asking for a password. Is there a workaround? Thanks

**Comment by lrprotexxa** [comment]
Anyone? @tothradoslav
