### ISSUE TITLE
[FR] Show execution time in minutes instead of seconds

### ISSUE THREAD

**Issue by laakal** [mingo-app/mingo#621]
<img width="349" alt="Screenshot 2023-12-11 at 13 28 09" src="https://github.com/mingo-app/mingo/assets/9221304/be77b946-9d58-406c-8416-4db2055e24fe">

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.
