### ISSUE TITLE
Database name is required in MongoDB URI for a project.

### ISSUE THREAD

**Issue by yangg** [mingo-app/mingo#623]
**Is your feature request related to a problem? Please describe.**
I cannot connect to db without db name

**Describe the solution you'd like**
Allow dbnane be empty to show all databases

**Comment by pepkin88** [comment]
I accidentally managed to get this effect by connecting to the admin database (to do stuff like kill operations), but the support is still not there yet. It lists all databases, but labels each of them as admin:
<img width="225" alt="image" src="https://github.com/mingo-app/mingo/assets/1028647/2bd40cc8-9fcb-45ba-99c9-07f5a3fc884c">

**Comment by tothradoslav** [comment]
The purpose of Projects is to connect to a specific database. To use the feature you need, use regular "connections". Projects are explained here: https://www.youtube.com/watch?v=nt4xhRmaaOc
