### ISSUE TITLE
Feature request: Search databases on left column

### ISSUE THREAD

**Issue by alkanna** [mingo-app/mingo#627]
I would love to be able to have a search box, or even better, some kind of CMD+K search bar, to quickly jump to a specific one in a long list of databases on the left column of the app

**Comment by tothradoslav** [comment]
Why don't you use the finder, which shows when you open a new tab (CMD+T, or CTLR+T). Just start typing the collection name. Finder has more complex functionality, too.

https://mingo.io/wp-content/uploads/2022/05/mingo-finder.mp4

If the filter you are looking for is for a different usecase, please reopen this issue with further details. Thanks.
