### ISSUE TITLE
Are founders/maintainers sleeping?

### ISSUE THREAD

**Issue by sagrawal31** [mingo-app/mingo#628]
# There have been no updates on various Bugs/FR for over two months. Not even acknowledgement. 

- https://github.com/mingo-app/mingo/issues/612
- https://github.com/mingo-app/mingo/issues/605
- https://github.com/mingo-app/mingo/issues/624
- https://github.com/mingo-app/mingo/issues/599

Especially the `new` keyword requirement has gone frustrating. Really not sure what to do. It feels like for us, https://github.com/mingo-app/mingo/issues/296#issue-1028086439 is getting more relevant.

**I sincerely apologies for creating this issue out of frustration 🙏🏻**

**Comment by tobsn** [comment]
There's been a bunch of bugs that make the app not fully usable, like not being able to set proper relations etc.
What bothers me the most is that somehow the app is really slow lately. A query takes 200ms or 2 seconds but then it takes 10+ seconds to update the view. (it's not my machine or the 400mbit sync connection it's on)
Also compare & sync... it never worked for me ever. Great idea, but can't be used. I even reported all details of why and how it's not working and was told it will be fixed... in October.

A good indicator of what is going on might be that your issue report is 2 weeks old with no response...

Oh the irony...
![mAcIgBWkmk8qxjy3beMDLpMhrLvMsil0](https://github.com/mingo-app/mingo/assets/109529/0b001979-2785-4de3-9d1a-02dca99aadd8)

**Comment by sagrawal31** [comment]
You are right, @tobsn. No updates yet 😞

**Comment by tobsn** [comment]
They also don't respond when asked on twitter... I have a feeling they abandoned this project. Very sad. It's a great app with a whole bunch of one of a kind never before seen DB UI features... they could still open source it and earn money on licensing to enterprise etc.

https://twitter.com/mingo_io
https://twitter.com/DavidDurika
https://twitter.com/radoslavtoth

Looks like they both dipped out mid last year.

I know you two can see this, some sort of statement would be nice. Nobody is mad, you can just work with the community and have it get going again. It would be absolutely terrible if this app just slowly disappears when there's so much that could be done on top of an already great product. fairly sure even @erh might help out? :)

**Comment by fers4t** [comment]
It's a great product, but there has been no news for a really long time. I hope they're doing well and everything is fine.

**Comment by tothradoslav** [comment]
most of the referenced issues are ready for next release now. Thank you for your patience.

**Comment by sagrawal31** [comment]
> most of the referenced issues are ready for next release now. Thank you for your patience.

Seeing this message early in the morning made my day.

**Comment by Bassadin** [comment]
@tothradoslav glad you're back!

**Comment by tobsn** [comment]
> @tothradoslav glad you're back!

that didnt last long...

**Comment by Bassadin** [comment]
Yeah :(

**Comment by tothradoslav** [comment]
I understand this may seem like we are not working on Mingo, but here's what's happening: we are reworking the entire code-base of Mingo to prevent technical dept. The aim is to have Mingo's code cleaned up and updated to latest versions of everything. This actually takes a lot of hours of refactoring. This should lead to faster development and new possibilities once released. 

We will be releasing a new version in a few weeks.

**Comment by Bassadin** [comment]
Oh, I mean that's totally reasonable. Could you maybe put that information on the readme here on GitHub? More people might see it that way :)

**Comment by sagrawal31** [comment]
Hi, @tothradoslav. Do you have any updates? It's now March 2025, which is over three and a half months since we last heard from you.

**Comment by tothradoslav** [comment]
Hi, yes, the situation is this:

- we were looking for a person to help us with what i now call "bundling hell", but did not find anyone capable of solving our problem
- we have refactored mingo with all new versions of every part of the software (nodejs, electron, vue 2 => vue 3, etc), but we are now unable to bundle the app for disdtribution. 
- there are tons of new features, bugfixes and performance improvements we solved meanwhile, just can't get it bundled... crazy

If you know of anyone who really knows about electron / vite bundling, please let us know, here or email us. Thanks.

**Comment by tobsn** [comment]
is this still the problem? you can't find a person who can bundle your app for distribution? how did you do it in the past?

**Comment by tothradoslav** [comment]
Nope, fortunately we have solved the issue finally. It took terribly long... We are realeasing a release candidate in few days. Just testing it.

**Comment by Bassadin** [comment]
@tothradoslav do you need any beta testers?

**Comment by tothradoslav** [comment]
Sure, will respond here when published.

**Comment by tothradoslav** [comment]
Hi, you can find an RC for the new version here (mac only for now):

https://github.com/mingo-app/mingo/releases/tag/v2.0.0-rc1

**Comment by Bassadin** [comment]
Ahh, too bad. I'm using Linux, will wait for the AppImage :)

**Comment by hpop** [comment]
@tothradoslav I tested the RC, and it is quite buggy for me. What is the best way to submit bug reports?

**Comment by tothradoslav** [comment]
Hi, if you could submit issues here using the "v2" label please. Thanks! We have fixed a lot of bugs meanwhile, will be releasing a new RC shortly. Still mac only, sorry for that.

**Comment by tothradoslav** [comment]
https://github.com/mingo-app/mingo/releases/tag/v2.0.1-rc1
