### ISSUE TITLE
Incorrect binary data representation

### ISSUE THREAD

**Issue by laakal** [mingo-app/mingo#629]
Mingo view
<img width="918" alt="Screenshot 2024-02-17 at 21 33 56" src="https://github.com/mingo-app/mingo/assets/9221304/916cd6c9-7890-40b0-86c8-eb4c13e7a5cd">

Compass view
<img width="916" alt="Screenshot 2024-02-17 at 21 38 17" src="https://github.com/mingo-app/mingo/assets/9221304/78e1d2a9-9da8-4865-8acf-ea98731dc877">

**Comment by sagrawal31** [comment]
Please check https://github.com/mingo-app/mingo/issues/628

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.
