### ISSUE TITLE
Bug: cancel after document select

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#63]
Select a document in the query results, then press `cancel` in the header. Now all documents are selected. I would expect no documents to be selected then.

**Comment by tothradoslav** [comment]
Thanks, corrected in next release

**Comment by Christilut** [comment]
It does cancel them now but the checkboxes are no longer "checked". They stay empty but the document selected counter does increase.
Basically, invisible checkmarks

**Comment by tothradoslav** [comment]
Wow, this was completely unrelated to the "cancel" button, I it happened to me by accident, too. Only happened after "refreshing" documents and the docs had to have _id as ObjectId. If the _id was a string (which I personally often use), this didn't happen. 

Thanks, so corrected in next version :)
