### ISSUE TITLE
Showing dummy date instead of real value!

### ISSUE THREAD

**Issue by jmisur** [mingo-app/mingo#630]
**Describe the bug**
Mingo invents a date time instead of showing a real value.
   ![Screenshot 2024-02-19 at 13 57 01](https://github.com/mingo-app/mingo/assets/321761/c0c1ea3f-dcaa-451b-a8e3-ce8a95b56e57)

- startedAt shows `2024-02-14T16:00:12.1212Z`, real value is `2024-02-14T15:00:12.604Z`
   ![Screenshot 2024-02-19 at 14 02 49](https://github.com/mingo-app/mingo/assets/321761/9692cac1-491d-49cd-baee-f80ff415419e)

- finishedAt  shows `2024-02-14T16:00:26.2626Z`, real value is `2024-02-14T15:00:26.210Z`
   ![Screenshot 2024-02-19 at 14 02 54](https://github.com/mingo-app/mingo/assets/321761/581c24c2-5d82-4d76-a4d1-538db79b7208)

It seems like it would somehow show the example value from Settings instead of the real one. 
   ![Screenshot 2024-02-19 at 14 05 36](https://github.com/mingo-app/mingo/assets/321761/dd2f830b-f809-42e8-83f3-b54b908401b9)

Fortunately, when editing the value, real one is displayed. Also when copying the value to clipboard.

**Screenshots**

**Desktop (please complete the following information):**
 - Mingo version: 1.13.5
 - OS: Sonoma 14.3.1
 - MongoDB: 6.0.12

**Comment by sagrawal31** [comment]
Please check https://github.com/mingo-app/mingo/issues/628

**Comment by tothradoslav** [comment]
this was a case problem, we had "sss" in format instead of "SSS". Corrected. But you will have to go to settings and set the date format again actively for the change to take effect. Sorry...

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.
