### ISSUE TITLE
Typo of "Explain Filter" 

### ISSUE THREAD

**Issue by ozanerturk** [mingo-app/mingo#632]
**Describe the bug**
_A clear and concise description of what the bug is and how to reproduce it._
Typo of "Explain Filter" 
**Screenshots**
_If applicable, add screenshots to help explain your problem._
![image](https://github.com/mingo-app/mingo/assets/15703627/40e68dd3-f427-42d1-8f5e-192d95447c6f)
![image](https://github.com/mingo-app/mingo/assets/15703627/0c49ff41-b20f-4cda-8f7c-5c5be9b190ea)

**Desktop (please complete the following information):**
 - Mingo version: Your version: 1.13.5
 - OS: Linux/ubuntu 20.04

**Comment by sagrawal31** [comment]
Please check https://github.com/mingo-app/mingo/issues/628

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.
