### ISSUE TITLE
"Analyzing data relations" covers up import button

### ISSUE THREAD

**Issue by brianlukoff** [mingo-app/mingo#636]
**Describe the bug**
When the import page is loaded but Mingo is still analyzing the database, the "Analyzing data relations" banner covers up the import button.

**Screenshots**
![CleanShot 2024-04-22 at 08 23 47](https://github.com/mingo-app/mingo/assets/518013/fd49d28a-374f-453f-a7cc-718aa4034f0b)

**Desktop (please complete the following information):**
 - Mingo version: 1.13.5
 - OS: macOS 14.4.1

**Comment by sagrawal31** [comment]
Please check https://github.com/mingo-app/mingo/issues/628

**Comment by tothradoslav** [comment]
fixed by adding extra space below button so the banner is below

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.
