### ISSUE TITLE
Expanding a sample result document in an aggregation is unpleasant when a field is large

### ISSUE THREAD

**Issue by joe-sm** [mingo-app/mingo#637]
**Describe the bug**
1. Have a doc that has a field which is very large
1. Get it in the Aggregator tab
1. As text doesn't wrap, it'll hugely extend the page

**Screenshots**

![1](https://github.com/mingo-app/mingo/assets/22639118/858ef862-15ac-49b2-b673-312bf6d2863a)
![2](https://github.com/mingo-app/mingo/assets/22639118/5b82a263-05b6-40a9-ac40-33459c9c079a)

**Desktop (please complete the following information):**
 - Mingo version: 1.13.5
 - OS: Windows 11

**Comment by sagrawal31** [comment]
Please check https://github.com/mingo-app/mingo/issues/628

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.
