### ISSUE TITLE
Document preview issue

### ISSUE THREAD

**Issue by alfredojl** [mingo-app/mingo#639]
# Document preview issue
In the "Click to preview the document" option it always shows the ObjectId, but below it appears `null` in all collections and relations.

![DocumentPreviewIssue](https://github.com/user-attachments/assets/d8c3dcd2-91ce-4327-80de-bdf197e4cf23)
---

**Comment by tothradoslav** [comment]
fixed

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.
