### ISSUE TITLE
Editing value

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#64]
I'm guessing this is on the list but I thought I'd mention it anyway

When clicking on a value in a document to edit it (double click or right click `Edit value`), the popup is too small to be useful for many values.
Arrays and objects are really hard to edit there and the only thing I do with the popup is then click `Edit entire doc`.

It would be really nice if the popup was larger and could display atleast 5 lines (resizable even better) if there are that many lines. 
For an array, it would be nice if the values are vertical instead of horizontal. Or maybe both? Short values in a long array could in multiple columns next to eachother. But that's maybe a bit too much to ask. Anyway, for arrays, I personally don't like scrolling sideways.

Another thing that comes to mind when I play around with it... The small editing popup is nice, but is it really needed? If I double click a field, wouldn't it make sense to just edit it in place? A save button and field type dropdown can appear next to it. In fact, since arrays and objects can expand in the document view, it can solve the above problem too?
That's the minimalist in me saying that, I like quick, efficient and practical. One less popup is one less mental switch.

**Comment by Christilut** [comment]
Of course right after I make an issue I notice new things. I can already dbl click a value in the array/object expanded view, great! You can pretty much disregard my first point there.

But the inline editing is something I prefer though

**Comment by tothradoslav** [comment]
True, inline editing would be smoother, however, it could be tricky for some values (too long, arrays, etc, sometimes you need to paste in a long array JSON).

Besides, we'd still need to add the "value type" select. Not sure how much "slimmer" this could be.

Any ideas?

**Comment by Christilut** [comment]
Well, I personally don't change the field type a lot. I don't think I've ever done that really. I use mongoose/typegoose though so my types should be in order.

But if the field type select is something that is not used a lot, maybe it can be moved into a `. . .` menu when inline editing the field?
Or a tiny button/arrow/icon that shows the select when pressed.

**Comment by tothradoslav** [comment]
Considering several cases when this might be an issue:

- very long values are pruned
- complex values (arrays, objects) would be more difficult to handle and they are pruned, too
- UX wise this might not be clear whether i'm editing or not
- foreign keys are transformed to links (click finds the doc in a new tab) and this would also interfere

Feels to me, that for now, we'll stick to the tiny popup, unless you can change our minds :)

**Comment by Christilut** [comment]
You know way more use cases than I do, so I'm sure you're right :)

Maybe remove (or an option to do so) the animation though? It's very pretty but after the initial "wow this software looks great" you just want to use it to its maximum potential and not be held back by animations. That's why I've stuck with Robo3T for so long, it's super crazy fast and no fuss at all. All other mongo GUI's are slow, even though they have more and better features I still keep going back to Robo3T. Mingo isn't slow, so maybe capitalize on that.

That's a developer mindset I think, but that's your target audience :)

**Comment by tothradoslav** [comment]
True, speed is important. We were thinking of a fast UI version with all animations removed. I will create a new issue for this. The compact mode is already prepared for new release.

**Comment by Christilut** [comment]
Awesome!
