### ISSUE TITLE
[FR] Ability to sort indexes by size, number of uses and name

### ISSUE THREAD

**Issue by sagrawal31** [mingo-app/mingo#644]
**Is your feature request related to a problem? Please describe.**
Sorting collections with various indexes by use or index size is often needed. For that to be done, I/we had to go to MongoDB compass.

**Describe the solution you'd like**
The simple sorts in the columns.

**Describe alternatives you've considered**
Use MongoDB compass.

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.
