### ISSUE TITLE
[FR] prevent firing empty aggregation when "Aggregator" tab is clicked

### ISSUE THREAD

**Issue by sagrawal31** [mingo-app/mingo#645]
**Is your feature request related to a problem? Please describe.**

We have a huge collection with 240 million records. If we attempt to go to the "Aggreagtor" tab, Mingo fires a default aggregation to the collection where the first is an empty `$match` block, and another is `$sort` with `{age: -1}`. Of course, this is not backed by an index, so this query keeps running for 45-60 minutes and sucks up the entire DB resources.

**Describe the solution you'd like**

Any kind of solution would work here, like not automatically firing the aggregation query or "Autoload samples" to be off by default.

**Describe alternatives you've considered**

I moved to MongoDB for doing the aggregations, which is a serious productivity killer.

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.
