### ISSUE TITLE
[FR] Fuzzy search for collection names in new tab

### ISSUE THREAD

**Issue by Bassadin** [mingo-app/mingo#646]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I created several test collections to showcase my problem:
![image](https://github.com/user-attachments/assets/6d0541c7-aa6a-4fdd-812a-fd8c1efa9ccf)

![image](https://github.com/user-attachments/assets/83e591ae-ccb8-4643-b9cf-ba9619098210)
I'd love for this search string (`testage`) to behave like a fuzzy search, e.g. match the collection "**test**Vill**age**" that can be seen above :)

**Describe alternatives you've considered**
Typing out the whole name can be tedious for long collection names.

**Comment by tothradoslav** [comment]
This issue is fixed / available in the new release v1.14.1

https://github.com/mingo-app/mingo/releases/tag/v1.14.1

Please reopen this issue if necessary.

**Comment by Bassadin** [comment]
Damn. That was fast! Thank you so much!

**Comment by Bassadin** [comment]
Just wanted to update and give some praises, this saves me so much time every day <3
