### ISSUE TITLE
Feature: escape button on edit

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#69]
When editing a value and the popup shows, it would be nice if I can press the Escape key so that it closes and cancels.
Escape seems to work for many popups like that but not the edit value.

**Comment by tothradoslav** [comment]
Yeah. ESC works in case you are editing a focused in the input field. In case you leave it or there is no input (boolean, null) it doesnt work. We will ha to rethink this. 

Can you confirm that the above works on windows please?

**Comment by Christilut** [comment]
It's a bit weirder actually now I tried it some more.

On most fields (I tried: array, object, number, ObjectId and string), ESC works and closes the popup. Doesn't matter if I clicked the text and started editing.

On fields that are of type Date, null or boolean, ESC does not work. I didn't try all other field types.

So it seems like what you said is correct, except the Date field which doesn't respond to ESC. And date field happens to be the field about which I initially created this issue.

**Comment by tothradoslav** [comment]
Hi, I have just uploaded a new release of Mingo.

I kept its version number to prevent other users to get a download notification, yet. Just go to Mingo.io and download the latest version, replace the old one, should be working.

If you could please check your issues and close those that are resolved, or comment on them, that would be great. 

Maybe if you have a spare moment, we could talk about Mingo over phone / video call, maybe a possible collaboration. If you are interested, please send me an email to info at mingo.io. 

Thanks, Rad

**Comment by tothradoslav** [comment]
Also, I'm preparing a "release candidate" version with console available so we can test it properly, will let you know.

**Comment by Christilut** [comment]
This bug is fixed

I'll contact you in a bit
