### ISSUE TITLE
Multiple undo notifications

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#72]
It's very confusing when you edit a few documents in a row and you want to undo one, that there are multiple "Document updated" notifications hanging around. I can't tell which is which and I don't dare undo-ing anything now.

A small timestamp `3 seconds ago...` or `30 seconds ago...` might help?

Or maybe the "Undo" button can show a bigger undo modal that shows a list of my last actions with timestamp.

Also the Undo notifications seem to hang around until I close them. This makes sense because losing the opportunity to undo because I was too slow clicking the notifications is silly. But that is an extra reason to have some sort of unified undo modal that shows my last few actions.

And notifications that never close automatically are annoying.. I like my UI clean, I don't like having to clean it up myself.

**Comment by tothradoslav** [comment]
Yep, this is a good point, we should improve upon the undo UX. I will give this a thought. 

We need to consider one important fact: undo is not atomic. Basically, Mingo stores the last state of the document in question and save that document upon undo. The document could have changed meanwhile, so this is something to consider.

Any ideas?

**Comment by Christilut** [comment]
Well I was thinking, maybe a diff is a good idea here? It can grab the latest version on the server and diff it with the saved version
There could be a reload button, incase the users thinks the document may have changed on the server
And when the user has taken its time to read the diffs and presses Save, Mingo could grab the server version again and confirm it is the same as the version that it was using to diff earlier. If it isn't the same, it could notify the user. It's not quite atomic but close enough?

Maybe an option to only show the changed lines and hide the rest. 
I'm sure there's good JSON diff libraries out there that do most of the work for this

**Comment by tothradoslav** [comment]
Yes, diffs are the way to go. Here are my thoughts:

- currently, undo is only possible for one action per collection
- I'd change this to keep track of (let's say) 50 last actions in entire "mingo"
- we'd have to create a log / list of these changes so the user can choose the one to undo
- once you pick the undo, it shows you the changes made (using diff) in a nice way
- confirming undo would create a proper mongo update object ($set / $unset) and submit it
- the undone change would be removed from the list of changes that can be undone
- user should still be able to undo the last change by clicking the undo button on the notification popup

Any better ideas / improvements? Thanks!

**Comment by Christilut** [comment]
Sounds very good.
Maybe the Undo button in the notification isn't necessary? I don't think Undo is used that much and isn't it okay for to be in a taskbar menu? Like `Edit -> Show Undo Menu` or something.

Are you guys considering a custom title bar? I'm using [this](https://github.com/AlexTorresSk/custom-electron-titlebar) and it works quite well. Although the archive is read-only so I'm not sure what the deal with that is.

**Comment by tothradoslav** [comment]
I'll address the custom titlebar in a new issue, thanks.

Well, you are right. We could just keep the undo in the menu, however, we also want to make sure people understand there is UNDO available in Mingo, so we want to show it to them.

It's one of those unexpected features you wouldn't know about unless you watched a "using mingo like a pro" video :)

**Comment by Christilut** [comment]
Yeah that's true

**Comment by tothradoslav** [comment]
This was easier said than done :) as we had to create our own custom getDiff / applyChanges functions. MongoDB documents may contain special values such as ObjectID, which existing solutions couldn't handle. 

But it's done, we'll see how it goes.

**Comment by Christilut** [comment]
Excited to give it a try! :)
