### ISSUE TITLE
FR: hover hotkey to edit

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#73]
Much like how the space button selects document (which is awesome!), it would be nice if there is a different button to edit a field.

So that I can hover a field name or value, press a button (maybe `e`) and the edit popup will appear.

I like using my keyboard as much as possible, and my hand is on the left side anyway. Double clicking is slower

**Comment by tothradoslav** [comment]
True and good point, will add this. "E" sound good.

We are planning to implement "mouse-less" UX, so that you could do basically anything in MIngo without using mouse at all. Not sure if this is completely feasible, but will try to get as close as possible.

Any other hotky ideas?

**Comment by Christilut** [comment]
Not yet but I'll keep it in mind when using Mingo
