### ISSUE TITLE
Bug: popup open drag release

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#74]
When I'm editing a document (or in any other popup) and I drag my mouse to select text and release my mouse outside the popup, the popup closes. Quite annoying, happens a lot to me and I even lost the changes I wanted to do.

Which leads me to another point: maybe there should be a confirmation to close an edit popup (or atleast the full document edit popup) when there are changes?

**Comment by tothradoslav** [comment]
Both corrected. In next release.

**Comment by Christilut** [comment]
This still happens in the `Edit doc` popup when dragging some text and release.
Seems to happen only when you click `Edit value` first and then in that small popup click `Edit doc`.
