### ISSUE TITLE
Custom electron titlebar

### ISSUE THREAD

**Issue by tothradoslav** [mingo-app/mingo#76]
Consider using this:
https://github.com/AlexTorresSk/custom-electron-titlebar

**Comment by GriffinSauce** [comment]
Would this be for Windows only? On mac it's more standard to have the system menubar and no titlebar. (or only a small one like vscode)

<img width="911" alt="Screenshot 2019-12-12 at 11 39 52" src="https://user-images.githubusercontent.com/5630996/70705359-34a38e80-1cd4-11ea-8800-3b51f750f185.png">

**Comment by tothradoslav** [comment]
Yep, this is a win vs mac question. I will close this for now as it's not a big deal.
