### ISSUE TITLE
Bug: create index style

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#77]
![image](https://user-images.githubusercontent.com/3471363/70651644-848d4180-1c51-11ea-9b3b-ed7bd08597c5.png)

Speaks for itself

**Comment by tothradoslav** [comment]
This seems to be a windows platform issue only. Can you confirm if this happens on all <select> inputs or only these?

Thanks.

**Comment by Christilut** [comment]
Only on this select so far.
I'm using Compact Mode, might be related.

**Comment by tothradoslav** [comment]
It's not compact-mode related, probably windows. So I will have to get me a windows computer for testing. Meanwhile, I have tried to tweak some CSS attributes, we'll see in next release.

**Comment by Christilut** [comment]
You can download Windows VM's in any format from Microsoft: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by Christilut** [comment]
With font-size 80% the text is a bit too small. 100% is a good size here but then the text clipping occurs again

**Comment by tothradoslav** [comment]
Let's try now...

**Comment by Christilut** [comment]
Now I don't see any way of adding an index. I think the button disappear accidentally ;)

**Comment by tothradoslav** [comment]
Isnt it on the top roght because of the compact mode?

**Comment by Christilut** [comment]
![image](https://user-images.githubusercontent.com/3471363/71255554-78c70c80-232e-11ea-9dc7-b6ac8318e31a.png)

Nope, missing

**Comment by tothradoslav** [comment]
Right! corrected
