### ISSUE TITLE
Create index: duplicate key error

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#79]
I'm adding a new index based on 1 unique field and getting this message `MongoError: E11000 duplicate key error collection: rekordcloud.users index: firebaseUserId_1 dup key: { : null }`

Took me a few minutes to figure it out but it's obviously because the `null` value already exists so it can't create a unique index.

It would be nice if Mingo translates this mongo error into a more user friendly error. I suspect this is a common problem when manually adding indexes, whether the value is `null` or something else.

**Comment by tothradoslav** [comment]
Yep, that's a good idea to actually map MongoDB error codes to human-readable text.

In this case (code E11000), the text could be: 

'ERROR: This collection contains documents with non-unique values in the field you are creating a UNIQUE index on.
This may also occur if there are multiple documents having no such field (MongoDB considers missing fields to be still equal, not unique).'

Sounds a bit awkward, any ideas on making it more human? :)

**Comment by Christilut** [comment]
Shorter is better I think. Maybe in this case something like `MongoDB Error: Duplicate key value (null) for unique field firebaseUserId`

And a `More info` link to a page/popup explaining this some more?

**Comment by tothradoslav** [comment]
We'll keep the original mongodb error shown in popup (bottom left). This longer text is the explanation.
