### ISSUE TITLE
FR: Shift select document

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#80]
Would be nice if I can select one document (with the checkbox) and then hold shift, press another and all the ones in between would also be selected.

**Comment by Christilut** [comment]
As an addition: it would be cool if you could hold the spacebar and it would select any documents that the mouse goes over. If you move the mouse up, those documents get highlighted and selected when you release the spacebar.

**Comment by tothradoslav** [comment]
Shift+click is prepared.
The second one we'll skip for now, even though we thought about it, too. I will add it in our backlog for future ideas.
