### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#81]
CTRL+R and F5 seem to reload the Electron window but as a user I'd like it to refresh my current results.

CTRL+S goes into the query field which is nice but as a web developer I expected CTRL+E or F6 to do this.

Shortcut keys are very personal of course, although I'm very used to all the Chrome and VSCode shortcut keys. But better would be a shortcut key file like how VSCode has it.

**Comment by Christilut** [comment]
When editing a document, it would be nice if CTRL+ENTER would save and close the popup
Or maybe CTRL+S there. Perhaps CTRL+ENTER is too quickly used and can accidentally save

Also minor bug: pressing CTRL+S in the document edit popup, still performs the highlight query action in the background

**Comment by GriffinSauce** [comment]
On mac CMD+R does the same thing, reloads whole app.

CMD/CTRL+ENTER to save makes the most sense to me. It's a pretty ubiquitous command for "commit to whatever I just did". As an abstraction of "save this edited version" CMD/CTRL+S also works. I don't see any issues with supporting both. (except for the conflict with the query shortcut)

**Comment by Christilut** [comment]
Actually in VSCode CTRL+ENTER goes to the next line without changing your current line. So if you're used to that you might accidentally commit. But again, personal preference and best to be able to customize it

**Comment by GriffinSauce** [comment]
Ah I've never used that one haha, VSCode has every possible combination mapped to _something_. Good point though.

**Comment by tothradoslav** [comment]
We could still come up with a new shortcut for "focus query / selector" instead of CMD+S. Maybe CMD+Q :) 

For some reason, Electron is stubborn with CMD+R and can't override it with custom functionality. Maybe I'm missing something.

**Comment by GriffinSauce** [comment]
CMD+Q is "quit app" in MacOS in general so that will be a bad time for mac users. :)

Perhaps:
CMD+F: focus selector
CMD+shift+F: find in screen (seems like a lower priority function to me)

There's some info here about reserved shortcuts on MacOS:
https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/

And some on Windows, plus common patterns:
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/dnacc/guidelines-for-keyboard-user-interface-design?redirectedfrom=MSDN#windows-shortcut-keys

It seems like this is quite a deep rabbithole if you're not careful.

**Comment by tothradoslav** [comment]
Yep, CMD+Q was a joke hehe :)

We should stick to the "most commonly used shortcuts", so CMD+F should stay as is. Not sure.

**Comment by tothradoslav** [comment]
Maybe use CMD+D, which is used for duplicate in code editors, but we don't need it in Mingo. What do you think?

**Comment by Christilut** [comment]
Maybe do shortcuts later and just keep a list of all possible shortcuts functions and later assign them. Otherwise it's going to be a mess..

**Comment by tothradoslav** [comment]
Here's what we'll do: 
- create a centralized list of shortcuts first
- this could then be easily changed in the future
- or we could open it for users to customize them as preferred

**Comment by tothradoslav** [comment]
Solved the CMD/CTRL + R to reload documents (only docs, not the entire app). 

We'll work on a way to customize some keyboard shortcuts in future, I have this in our backlog. 

So I'm closing this issue for now.
