### ISSUE TITLE
Object keys width

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#84]
Maybe this can use more horizontal space in case keys are long?

![image](https://user-images.githubusercontent.com/3471363/70849087-37d87f00-1e7a-11ea-8ec2-5b48f499c9b7.png)

**Comment by tothradoslav** [comment]
Yep, we tried solving this, however, it can only be done by JS calculations and made the whole thing too slow. 

Also, this is extreme edge case, I've never seen such object keys :)

So even though I like Fatboy, i'm going to close thisone for now :) If you have an idea on solution, let me know. Thanks.

**Comment by Christilut** [comment]
No problem, I understand :)
