### ISSUE TITLE
Copying pinned values

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#86]
Would be nice if I can right click a value from a pinned column and select `Copy value`
Now I have to open the document, find the right key and right click that value.

In my case it's because I have external user ID's pinned. Often I need to copy that value and paste it in some external website to find the right user. 
I think users would usually pin values that they have to work with a lot so quick actions like this can be very helpful

**Comment by tothradoslav** [comment]
Yep, was thinking about that too. Will make it happen. 

We were also thinking about custom actions on documents for your usecase: 

For example, an action could be to open an external link with variable from the doc. 

Both these features should be created, they don’t go against each other.

**Comment by Christilut** [comment]
That would be very cool. I was thinking something like that too, but it could lead to Mingo becoming too bloaty.. 
With custom actions and views, Mingo would become something like ForestAdmin, which could be super interesting but also dangerous.

Maybe stuff like this is suitable for extensions at a later time? People (businesses) would pay good money for integrations

**Comment by tothradoslav** [comment]
Yep thats a good point. 

Back to copying pinned columns: here’s my thought on how to implement it:

Rightclick on doc:
The “copy” option would get new sub-options with each column’s value to copy (besides the current copy options). 

What do you think?

**Comment by Christilut** [comment]
Yeah sounds good. Keeps things nice and clean

**Comment by tothradoslav** [comment]
@Christilut I have released a new "hidden" version, with all issues marked "next release" done. I didn't bother creating an RC version, because we stopped any marketing for now, so there are few downloads now.

This version includes the devtools, so you can see any logs / errors, for better reporting. Opens / closes just like in Chrome. 

Please check all your open issues marked for "next release" and close / comment on them. Thanks for all feedback!

**Comment by Christilut** [comment]
Alright, I'll check it out today.

Just a quick thing I noticed already: I tried deleting my old mingo folder but it said a file was in use. Turns out there are about 50 mingo.exe instances running according to my task manager. Maybe they never truly exit? I open and close Mingo a lot.

**Comment by tothradoslav** [comment]
wow, that's weird. could you create this as a new issue pls
