### ISSUE TITLE
Windows keeps old mingo.exe alive

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#87]
I tried deleting my old mingo folder but it said a file was in use. Turns out there are about 50 mingo.exe instances running according to my task manager. Maybe they never truly exit? I open and close Mingo a lot.

![image](https://user-images.githubusercontent.com/3471363/70994657-fee51800-20ce-11ea-9ff8-2a2073b4dc82.png)

**Comment by tothradoslav** [comment]
I found tons of related electron issues, but we've got covered everything they mention. Can you tell me how you close you app? What shorcut? Thanks.

**Comment by Christilut** [comment]
Just pressing the X in the top right corner.

**Comment by Christilut** [comment]
Just closed Mingo a few times to get the white screen bug but no extra processes stuck this time.

**Comment by tothradoslav** [comment]
Ok. Please let me know if it happens again ot have further info. Thansk

**Comment by tothradoslav** [comment]
I found that sometimes when you minimize app window, windows let's you open multiple electron apps without knowing. I added some code to prevent that, let's see how it goes.

**Comment by Christilut** [comment]
Haven't seen this since but I'll re-open if it happens again
