### ISSUE TITLE
Fighting with the filter history dropdown

### ISSUE THREAD

**Issue by GriffinSauce** [mingo-app/mingo#88]
The history for query filter shows whenever you focus the input and they obscure the entire screen. I don't know exactly why but this interaction annoys me.

Quite often I'm looking at a result while deciding how to continue filtering, so this interrupts that flow. Maybe reducing the history amount to 5 + "...more" or something would solve it. 

Some feedback from other users might be helpful here to find the best interaction pattern.

**Comment by tothradoslav** [comment]
Another option: when you focus, it opens. Once you start typing, it hides. 

Question is how to reopen it when visitor wants it. 

Or add an explicit history button to toggle it

**Comment by Christilut** [comment]
Not sure if hiding it while typing would solve it. That just makes it show (focus) and then hide (typing) which is a bit annoying. I'm not too bothered by the history but after I click the field, things shouldn't change anymore.

Also something that would make the field much more usable, it starts off like this:
![image](https://user-images.githubusercontent.com/3471363/71065357-6489e080-2171-11ea-9c98-cac18627f92e.png)

When you click it the cursor is at the end, after the brackets... But I don't want to type there.
![image](https://user-images.githubusercontent.com/3471363/71065416-7b303780-2171-11ea-90d9-8d314a46c77f.png)

This is where I want to start typing. My routine is already: `click`, `mouse left`, `enter` and then I can start. So maybe when the input is empty or `{}`, it can auto expand to the above when clicked.

**Comment by tothradoslav** [comment]
History - I'd like users to see there's a history option. I'll keep it as described above and you tell me what you think. We'll also use it for a while and we'll discuss it further then.

Regarding the focus of cursor: I've done it so that when the selector is "{}" then it focuses inbetween the brackets. However, I didn't make it expand it to 3 lines as most usecases use one attribute to filter docs, such as {name: 'Christiaan'} and then one line is enough. But again, we'll see how it behaves.

**Comment by tothradoslav** [comment]
@GriffinSauce  I have just released another "hidden" version. Please check out all issues marked "next release". Thanks!

**Comment by Christilut** [comment]
Merry Christmas :)

The query field now does this when I click it:
![image](https://user-images.githubusercontent.com/3471363/71253610-b88af580-2328-11ea-86a1-102da60fcfa9.png)

When I click it again when it's like that, it does put the cursor in between the brackets

**Comment by tothradoslav** [comment]
I had this issue on OSX, too, but got it working with setTimeout before moving the cursor. I increased the timeout from 0 to 100ms so let's see.
