### ISSUE TITLE
Undo document changes

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#91]
Pressing the Undo button in a popup or from the taskbar shows me a grey overlay but nothing else.

![image](https://user-images.githubusercontent.com/3471363/71007794-e1707800-20e7-11ea-9ca4-2beecb952b8a.png)

**Comment by tothradoslav** [comment]
I will need more information, can't reproduce. 

Is the error in screenshot shown upon click to "undo" or maybe it was there before that event?

Could you maybe provide a screenshot of what you see after clicking "undo"?

**Comment by Christilut** [comment]
Now it works properly. I'll add more info if it happens again

The above error was when I clicked the Undo button.
