### ISSUE TITLE
Title bar in compact mode

### ISSUE THREAD

**Issue by tothradoslav** [mingo-app/mingo#93]
![image](https://user-images.githubusercontent.com/3471363/70849210-89cdd480-1e7b-11ea-8a74-45cc888e1973.png)

The left part doesn't do anything and that information is already in the navigation bar above it.

The right part could be moved into the navigation bar in compact mode? Or in the query field above the button

_Originally posted by @Christilut in https://github.com/mingo-app/mingo/issues/57#issuecomment-565715948_

**Comment by tothradoslav** [comment]
This is a standard title bar with title on left and options (buttons) on the right. I was thinking about completely removing it in compact mode, but not sure where to put the options. 

In some cases there are 5+ buttons there. The only option seems to be to move it into / after the navigation bar because that's standard, too. 

Just not yet sure how to position it there...

**Comment by tothradoslav** [comment]
Ok, this is done, tell me what you think (applies to compact mode only).

**Comment by Christilut** [comment]
Love it, I didn't even notice at first because it felt natural

**Comment by Christilut** [comment]
Maybe the insert document + icon is now in an "unlogical" place, but if you press it once, you know what it does and I like that it's not too much "in your face".

**Comment by tothradoslav** [comment]
I’ll improve the settings dialog to inform the user that some features may be “hidden” in compact mode so its recommended only after some time of using mingo. 

Do you have any better solution?

**Comment by Christilut** [comment]
Sounds good!
