### ISSUE TITLE
Bug: Unlock icon doesn't change

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#97]
![image](https://user-images.githubusercontent.com/3471363/71253712-ef610b80-2328-11ea-86c4-7e618fb2968b.png)

After I click "Unlock for ..", it stays like this. In the dropdown, the correct state is selected and I can edit documents.

**Comment by tothradoslav** [comment]
Ok, another quick release :) sorry for so many downloads...

**Comment by Christilut** [comment]
Haha don't worry, I like quick development :)

**Comment by Christilut** [comment]
Now it's acting weirder

It doesn't always change to the right option in the dropdown now. It won't allow me to go from `Unlock database` to `Unlock in this tab`. Same with lock.
Going from unlock -> lock does work and vice versa.

**Comment by tothradoslav** [comment]
Yep, some scenarios are not valid, actually. If database is unlocked, there's no point unlocking it in this tab - it's unlocked globally. But it's a UX question, because this scenario actually would do 2 things:

- lock the database (globally) because there's no point in unlocking a unlocked DB
- then unlock it in this tab

Which we didn't want to happen as there's too much magic. 

So maybe "graying out" these scenarios?

**Comment by Christilut** [comment]
Yeah but if the database is unlocked globally from that tab and I want to unlock it only in this tab, isn't that still valid?

If other tabs also lock it globally then it would need to be grayed out

**Comment by tothradoslav** [comment]
If it's unlocked globally, it means it's unlocked in all tabs. That's its default state. When you open a new tab with that DB, it will automatically be unlocked. So in such case, unlocking it locally makes no sense.

I guess we should describe this better. Any ideas? So that people understand it clearly.

**Comment by Christilut** [comment]
Maybe you can move the lock icons?
![image](https://user-images.githubusercontent.com/3471363/71305521-d5c9cd80-23d5-11ea-9b66-f1051a52c51c.png)
Database lock here, where the circle is

![image](https://user-images.githubusercontent.com/3471363/71305523-e11cf900-23d5-11ea-9e6c-5876e4ca5a5c.png)

And tab lock where the 3 lines are?

Makes more sense to me if the locks are where they visually belong. Then you can also just click to lock/unlock instead of the dropdown with semi-confusing choices. Maybe a notification on lock/unlock to notify the user of what happened.

**Comment by tothradoslav** [comment]
I’m imagining this but may become even more confusing. Imagine having an unlock icon in the tab and a locked one in addressbar = unlock in this tab. 

Maybe just rewording it? Of simplifying the logic?

**Comment by Christilut** [comment]
Maybe we're overthinking this... Database lock is a great feature, that needs to stay.

But maybe tab lock is overkill and confusing. Instead of unlocking a tab before I want to edit (which is kind of annoying because I always forget), I can just get a popup that says "This database is locked, are you sure you want to continue editing?" 
And confirming that popup allows me to edit a value/document like normal. After editing, the database is still locked and any new edit action gives me the same popup again.

Maybe add extra warning colors/bars to the edit document popup to let the user visually know what they're doing is potentially dangerous. And even after that, maybe another confirm "Are you sure you want to edit this document in a locked database?"

I think that might simplify things a bit, what do you think?

**Comment by tothradoslav** [comment]
Yeah maybe removing the tab lock will suffice. 

It always comes down to having a production database you want to have locked and other dbs that are less important. 

But I usually have situations where i want to edit 10 things in a production db and 10 popups would annoy me. 

Also, this feature applies to any changes in documents, just emphasizing it in edit doc modal is not enough. 

Maybe a different approach: have dbs locked and unlocked and when locked, ask confirmation with 3 options: 
1.cancel, 
2. Ok change
3. Ok and unlock for 10 minutes. 

And yet another way:
On confirm to make change, that db would behave unlocked in that tab until other db is opened in that tab or tab closed.

**Comment by Christilut** [comment]
```
Maybe a different approach: have dbs locked and unlocked and when locked, ask confirmation with 3 options:
1.cancel,
2. Ok change
3. Ok and unlock for 10 minutes.
```

I like this way, but maybe the 10 minutes can keep the tab unlocked until user is idle for 10 minutes. Otherwise it would suddenly ask again even though I'm busy typing query's

**Comment by tothradoslav** [comment]
I’m actually thinking of removing this feature completely. Reason: its purpose is to prevent unintentional changes to documents. However, for that we have undo. Maybe we should focus on making undo more robust even for multi-document updates and we dont need writelock. 

What do you think?

**Comment by Christilut** [comment]
Well you can't undo everything though. Even if Mingo could undo everything, things may have changed meanwhile from a different process and that can mess things up. An accidental production database write can have quite some consequences. Especially because developers might be trying things out quickly and carelessly on their local database, but for some reason accidentally switched to production... I know I do things like `db.users.remove({})` on my local database when testing...

I think the write lock is a great idea, but simplicity is key here.

**Comment by tothradoslav** [comment]
Fair enough. That was the original point. Just exploring all options. 

Back to the unlock for 10 minutes solution: would that apply to all tabs??

**Comment by tothradoslav** [comment]
Ok, I think I came to a conclusion, just need your thoughts:

1. dbs can only be locked or unlocked
2. if locked and I'm going to make a change, a (custom) confirm modal comes up to confirm
3. in this modal, there could be a Cancel and a Proceed button, plus a checkbox "Don't ask me for 10 minutes".

Maybe: add another button to "Unlock database" directly in this modal (with explanation of what it means)

**Comment by Christilut** [comment]
Seems like the most balanced solution yeah. Idle check isn't really necessary, just don't ask for 10 minutes is fine. If that bothers the user too often, they should really keep it unlocked.

**Comment by tothradoslav** [comment]
completely reworked, please check it out...
