### ISSUE TITLE
Bug: CTRL+Z not working

### ISSUE THREAD

**Issue by Christilut** [mingo-app/mingo#99]
The undo popup says to press CTRL+Z to undo (to open the popup), but that key combo doesn't do anything for me

**Comment by tothradoslav** [comment]
Hm, this is using the built-in menu. Could you try opening it through the menu (Edit -> Undo document changes) ?

Works on OSX for me.

Or any logs with errors?

**Comment by Christilut** [comment]
When I do it with the menu, I get the empty overlay popup (different issue). So I guess the trigger does work, just not the key.

Nothing in the logs

**Comment by Christilut** [comment]
Works with newest release

Or did nothing change? :/

**Comment by tothradoslav** [comment]
I didnt touch it :)
